pmm/pmm-docker.groovy
=> Squash new Docker layers for smaller total size.

IaC/ps.cd/init.groovy.d/cloud.groovy, IaC/psmdb.cd/init.groovy.d/cloud.groovy
I noticed this issue when working for pt.cd.percona.com. Docker service was not started on the nodes.
=> Fix for starting docker on slaves

IaC/pt.cd/JenkinsStack.yml, IaC/pt.cd/init.groovy.d/cloud.groovy, pt/percona-toolkit-param-docker.yml, pt/percona-toolkit-pipeline-build-docker.yaml, pt/percona-toolkit-trunk-docker.yml
This is initial setup for pt.cd.percona.com
=> Initial PT jenkins master setup

psmdb/percona-server-for-mongodb-4.0-param.yml, psmdb/percona-server-for-mongodb-4.0-template.yml, psmdb/percona-server-for-mongodb-4.0-trunk.yml, psmdb/percona-server-for-mongodb-master-param.yml, psmdb/percona-server-for-mongodb-master-template.yml, psmdb/percona-server-for-mongodb-master.yml
This is to fix some issue with benchmark test suite in PSMDB templates.
=> Updated PSMDB templates to fix issue with benchmark suite

pmm/aws-staging-start.groovy
Contains newer signing key for pmm-client-1.17.1
=> PMM-3409 - updated to percona-release-1.0-3 package

psmdb/percona-server-for-mongodb-master-template.yml
This is fixing python dependencies installation for PSMDB in the master template.
=> Fix PSMDB master template for python dependencies

IaC/ps.cd/JenkinsStack.yml, IaC/ps.cd/init.groovy.d/cloud.groovy, IaC/ps.cd/plugins_info.yaml
* update plugins
* move ps.cd to 'us-west-1'
=> JEN-986 migrate ps.cd to another region

IaC/psmdb.cd/init.groovy.d/cloud.groovy
=> JEN-1039 use xfs instead of ext2 for psmdb.cd

IaC/find-ami.sh, IaC/ps.cd/JenkinsStack.yml_ps3, IaC/ps.cd/init.groovy.d/cloud-ps3.groovy, IaC/ps.cd/packer/aws-docker.json
* create ami for 'eu-west-1'
* fix 'find-ami.sh' output
* commit 'cloud-ps3.groovy'
=> JEN-1038 migrate 'ps3.cd' to 'eu-west-1' region

IaC/pxb.cd/init.groovy.d/cloud.groovy, pxb/percona-xtrabackup-8.0-param-medium.yml, pxb/percona-xtrabackup-8.0-template.yml
* add cosmic and xenial  OSs
* remove artful OS
* add xtradb80
=> JEN-1058 update 'percona-xtrabackup-8.0-param-medium' job

IaC/pxb.cd/terraform/main.tf, IaC/pxb.cd/terraform/network.tf, IaC/pxb.cd/terraform/variables.tf
* save 'terraform.tfstate' in s3
* change instance
* change keyname
=> ENG-89 save 'terraform.tfstate' in s3

IaC/psmdb.cd/JenkinsStack.yml
=> JEN-1062 increase volume size for psmdb.cd

IaC/psmdb.cd/init.groovy.d/cloud.groovy
* add centos6, centos7, ubuntu bionic, ubuntu cosmic,
debian jessie and debian stretch
=> JEN-1029 add additional worker nodes

pmm/pmm-ovf-testsuite.groovy, pmm/vbox-staging-start.groovy
This PR implements the following:
1. Updates the vbox-staging-start Job, so that the latest ovf image tags can be started along with setup for pmm-framework. 
2. Adds a new Job, which will be triggered as soon as a new OVF tag is created, which will then run UI tests on OVF installation of PMM on sauce labs.
=> PMM-3508 Adding Support for UI tests with OVF builds

pmm/pmm-codecept-saucelabs.groovy
=> PMM-3289 Adding Codecept-Saucelabs Pipeline file

pmm/aws-staging-start.groovy
To avoid failures on the job, need to debug more
=> PMM-3716 Removing the pmm-admin command

psmdb/percona-server-for-mongodb-4.0-template.yml
https://psmdb.cd.percona.com/job/percona-server-for-mongodb-4.0-param-test/
=> JEN-1077 use the same version of pip for all jobs

pmm/aws-staging-start.groovy
Sending the same IP as being sent to PMM-server for pmm1.x
=> PMM-3858 Updating the IP address sent to script

pmm/pmm-1-0-documentation.groovy, pmm/pmm-2-0-documentation.groovy
=> PMM-3763 Documentation Uploaded files missing

pmm/pmm2-ovf-test.groovy
1. Ensures PMM2 OVF images are installed and imported via virtualbox
2. Will be used to test setup of `pmm-admin` and `pmm-agent` and run some sanity tests later.
=> PMM-3864 Adding tests for PMM2 OVF images

pmm/aws-staging-start.groovy
Update the mysql version installed on AWS staging environment, start the server
=> PMM-3858 Install mysql 5.7.x on AWS staging

psmdb/percona-server-for-mongodb-master-template.yml
This change is already done in jenkins and the job updated so it can be merged.
=> Fix in percona-server-for-mongodb-master-template.yml for gotools build

pmm/aws-staging-start.groovy
Has been tested on AWS test staging job.
=> PMM-3909 Fixing pmm-agent, using pmm-admin add

pmm/aws-staging-start.groovy
Adds support for installing and setting up
1) mysql
2) mongodb
3) postgresql
=> PMM-3909 Adding Support for PMM-framework with dev-latest tag & pmm2.0

pmm/pmm2-client-autobuild.groovy, pmm/pmm2-server-autobuild.groovy
https://pmm.cd.percona.com/job/pmm2-client-autobuilds-slava/
https://pmm.cd.percona.com/job/pmm2-server-autobuild-slava/
=> JEN-3705 get version from 'vars' file only

IaC/JenkinsStack.yml, IaC/fb.cd/JenkinsStack.yml, IaC/fb.cd/init.groovy.d/cloud.groovy, IaC/ps56.cd/JenkinsStack.yml, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/JenkinsStack.yml, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/JenkinsStack.yml, IaC/ps80.cd/init.groovy.d/cloud.groovy
* update fb.cd jenkins to 2.177
* update ps56.cd jenkins to 2.177
* update ps57.cd jenkins to 2.177
* update ps80.cd jenkins to 2.177
* update pmm.cd jenkins to 2.177
=> JEN-935 update jenkins farm

pxb/percona-xtrabackup-2.3-template.yml, pxb/percona-xtrabackup-2.4-template.yml, pxb/percona-xtrabackup-8.0-template.yml
* add 'DEBIAN_FRONTEND=noninteractive' for 'apt-get install' command
to avoid deb interactive issue with ubuntu bionic instance
=> JEN-1116 fix ubuntu bionic instance

pmm/pmm2-server-autobuild.groovy
https://pmm.cd.percona.com/job/pmm2-server-autobuild-slava/
=> PMM-3629 fix build issue

psmdb/percona-server-for-mongodb-3.6-param.yml, psmdb/percona-server-for-mongodb-3.6-template.yml, psmdb/percona-server-for-mongodb-3.6-trunk.yml
* start to use build script
* fix jenkins properties in yaml files
=> PSMDB-393 update of v3.6 jobs

psmdb/percona-server-for-mongodb-3.4-template.yml, psmdb/percona-server-for-mongodb-3.6-template.yml, psmdb/percona-server-for-mongodb-4.2-param.yml, psmdb/percona-server-for-mongodb-4.2-template.yml, psmdb/percona-server-for-mongodb-4.2-trunk.yml, psmdb/percona-server-for-mongodb-master-template.yml
Added 4.2 template + trunk and param job.
Removed from template jobs some logic which is not used any more.
Jobs are already updated in jenkins.
=> Add PSMDB 4.2 jobs and minor PSMDB fixes

pmm/aws-staging-start.groovy
Reverts Percona-Lab/jenkins-pipelines#160?
Until we fix pmm2-client version on centos/amazon linux testing repos.
=> Revert "PMM-4338 Pass username and password."

IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/terraform/master_user_data.sh
* update jenkins from 2.140 to 2.176.2
* update all plugins
=> JEN-935 update pxb.cd jenkins to the latest stable version

pxc/pxc80-test-57to80upgrade.yml, pxc/pxc80-test-async-replication.yml, pxc/pxc80-test-correctness.yml, pxc/pxc80-test-crashrecovery.yml, pxc/pxc80-test-longevity.yml, pxc/qa-pxc80-build.yml, pxc/qa-pxc80-clone.yml
* adapt pxc 8.0 dev jobs for using in aws jenkins
=> JEN-1081 start using S3 bucket to save jobs artifacts

psmdb/percona-server-for-mongodb-4.0-param.yml, psmdb/percona-server-for-mongodb-4.0-template.yml, psmdb/percona-server-for-mongodb-4.0-trunk.yml, psmdb/percona-server-for-mongodb-4.2-param.yml, psmdb/percona-server-for-mongodb-4.2-template.yml, psmdb/percona-server-for-mongodb-4.2-trunk.yml
Bugfix and small change for using different branch in psmdb_misc_scripts repo for running tests.
=> Change PSMDB 4.0 and 4.2 jobs for custom psmdb_misc_scripts branch

pmm/pmm-client-autobuild.groovy, pmm/pmm-hotfix-client-autobuild.groovy, pmm/pmm2-client-autobuild.groovy
Removes `Ubuntu 14.04` and `Ubuntu 18.10` support
=> JEN-1113 remove unsupported OSs

pmm/pmm2-api-tests.groovy
=> Improve testing reports

pmm/pmm-server-release.groovy, pmm/pmm2-server-release.groovy, vars/sync2Prod.groovy
P.S. I will commit it after GA
=> JEN-1133 Clean CDN cache

IaC/pxc.cd/init.groovy.d/cloud.groovy
=> JEN-1172 increase disk size for 'performance-centos-6-x64' worker

pmm/aws-staging-start.groovy, pmm/pmm2-ovf-test.groovy
This task Covers Part of PMM-4869, to add Sanity checks for PMM2.x OVF images, and it also covers PMM-4868 & PMM-3864, to run UI tests on PMM-server based out of OVA image. 
The idea is to use Digital Ocean Node for running OVA based PMM-Server and then use our AWS node to connect to it as a PMM-client with Different Db configured, run UI tests on this server Instance and then destroy the server and client instances.
=> PMM-3864 PMM-4868 PMM-4869 Adding Job for OVF image test and UI

pmm/aws-staging-start.groovy, pmm/pmm2-ovf-test.groovy
This is to fix the issue with starting job without any value for server_IP
=> PMM-4869 Fix for Server_IP Null error

IaC/psmdb.cd/JenkinsStack.yml, IaC/psmdb.cd/init.groovy.d/cloud.groovy
* update jenkins to the latest version
* update all plugins
=> PBM-350 change IPs for psmdb.cd jenkins

cloud/jenkins/psmdb_operator_aws_openshift.groovy, cloud/jenkins/psmdb_operator_gke_version.groovy, cloud/jenkins/psmdb_operator_minikube.groovy, cloud/jenkins/psmdb_operator_openshift.groovy
=> JEN-1191 Add possibility of specifying 'custom' docker images

pmm/aws-staging-start.groovy, pmm/pmm2-ui-compare-tests.groovy
Useful for Upgrade testing and UI tests
=> PMM-5030 Enable testing repo for PMM-Server

cloud/jenkins/pxc_operator_aws_openshift-4.groovy
* always download the latest openshift-install and openshift-client tools
=> CLOUD-451 improve 'pxc_operator_aws_openshift-4' job

pmm/pmm2-ami-test.groovy, pmm/pmm2-ami.groovy, pmm/pmm2-ui-compare-tests.groovy
Triggers a UI tests Job on the newly built AMI Instance for PMM2
=> PMM-4826 Adding job to test AMI Instance, UI tests for newly built image

pmm/aws-staging-start.groovy
Changing Percona Release version to `1.0.13`
=> PMM-4826 Updating Percona Release version

pmm/aws-staging-start.groovy
Reverts Percona-Lab/jenkins-pipelines#317
=> Revert "PMM-4826 Updating Percona Release version"

pmm/pmm2-rewind-submodules-fb.groovy, pmm/pmm2-submodules-rewind.groovy
1. Removed the trigger, so it can only be manually triggered
2. Removed the use of version, honestly, we don't use it hence not needed.
=> PMM-5064 Job for Submodule rewind for FB branches. 

IaC/psmdb.cd/init.groovy.d/cloud.groovy
* fix 'min-centos-6' worker
* fix 'min-bionic' worker
=> PSMDB-575 Start to use 'm5.2xlarge' instance for psmdb tests

dbaas/jenkins/percona-dbaas-cli-doc-html.groovy, pmm/pmm-1-0-documentation.groovy, pmm/pmm-2-0-documentation.groovy
* IT team changed the destination servers so we need to update␠
it in our jobs too
=> ENG-814 Update docs jobs

pmm/pmm2-server-autobuild.groovy
Added alertmanager to pmm autobuild
=> PMM-5558 Alertmanager (PMM autobuild)

pmm/pmm2-api-tests.groovy
Dependent on API tests changes for SAAS-76
=> SAAS-76 Adding support for Security Check in API tests

cloud/jenkins/pbm_docker_build.groovy
https://cloud.cd.percona.com/job/pbm-docker-build/183/
=> PBM-475 Fix 'pbm-docker-build' job

cloud/jenkins/psmdb_docker_build.groovy
Add debug build arg to psmdb docker build to build debug images
=> K8SPSMDB-133: Add psmdb debug container build

cloud/jenkins/psmdb_operator_lke_version.groovy, cloud/jenkins/pxc_operator_lke_version.groovy
Make CSI driver to avoid repeatable volume attachment
=> CLOUD-515 Change default storageClass

cloud/jenkins/pxc_operator_gke_version.groovy
Fixing error "message=Auto_upgrade cannot be false when release_channel RAPID is set."
=> CLOUD-556 Remove breaking option

cloud/jenkins/pxc_operator_aws_openshift-4.groovy, cloud/jenkins/pxc_operator_aws_openshift.groovy, cloud/jenkins/pxc_operator_eks.groovy, cloud/jenkins/pxc_operator_gke_version.groovy, cloud/jenkins/pxc_operator_lke_version.groovy, cloud/jenkins/pxc_operator_minikube.groovy
New functional test has been introduced
Test timeout has been set
=> K8SPXC-356 Tests enhancement

pmm/pmm2-api-tests.groovy, pmm/pmm2-ui-tests.groovy
- https://jira.percona.com/browse/SAAS-175
I need to set Dev Auth service host to pass API tests in my feature build: https://github.com/Percona-Lab/pmm-submodules/pull/967
=> SAAS-175 Add dev auth service host

pmm/pmm-client-autobuild.groovy, pmm/pmm-hotfix-client-autobuild.groovy, pmm/pmm2-client-autobuild.groovy
Removed build steps for Debian Jessie (EOL)
=> PMM-6311 removed debian jessie

pmm/pmm-server-autobuild.groovy, pmm/pmm2-server-autobuild.groovy
Added build for dbaas-controller
=> PMM-6119 added build for dbaas-controller

pmm/aws-staging-start.groovy
This is only a temporary request to nail down the actual issue we have with false positives, I will revert this back to original instance type by end of this week.
=> PMM-5740 Change instance Type Request

pmm/aws-staging-start.groovy
Reverts Percona-Lab/jenkins-pipelines#526
=> Revert "PMM-5740 Change instance Type Request"

IaC/rel.cd/JenkinsStack.yml, IaC/rel.cd/init.groovy.d/cloud.groovy
Netmaps:
```
netMap = [:]
netMap['eu-west-1b']
```
Will be updated after approval & stack run as we don't know their new ids yet
=> ENG-909: Change CIDR for rel.cd

pmm/pmm2-server-autobuild.groovy
Added **errexit** and **xtrace** for multiline shell steps
```
set -o errexit
set -o xtrace
```
=> PMM-6410 added errexit & xtrace for shell steps

IaC/ps80.cd/init.groovy.d/cloud.groovy
After approval, I'll enroll this config to ps80 jenkins & test it out, then I'll share the details and/or implement needed changes
=> ENG-906: Add CentOS 8 and Ubuntu Focal AMI support

IaC/rel.cd/JenkinsStack.yml, IaC/rel.cd/init.groovy.d/cloud.groovy
EC2 plugin was updated: https://github.com/jenkinsci/ec2-plugin/blob/ec2-1.53/src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java#L72
=> ENG-733: Update rel.cd jenkins and EC2 settings

IaC/cloud.cd/init.groovy.d/cloud.groovy
**Note**: Pricemap changes was pulled from instance
=> ENG-733: Update cloud.cd jenkins and EC2 settings

pxb/percona-xtrabackup-8.0-template.yml
In new version of bootstrap.sh, flags were slightly changed
=> PXB-2248: Handle new bootstrap.sh properly

pmm/aws-staging-start.groovy
Requires: https://plugins.jenkins.io/build-user-vars-plugin/ (already installed)
=> ENG-921: Rework gathering userId

pmm/aws-staging-start.groovy
Test job result: https://pmm.cd.percona.com/job/aws-staging-test-job/399/console
=> Update spot price for PMM's aws-staging

pxb/percona-xtrabackup-2.4-param-medium.yml, pxb/percona-xtrabackup-2.4-param.yml, pxb/percona-xtrabackup-2.4-template.yml, pxb/percona-xtrabackup-8.0-param-medium.yml, pxb/percona-xtrabackup-8.0-param.yml, pxb/percona-xtrabackup-8.0-template.yml
Implemented by the hands, works as expected https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param/161/
=> PXB-2248: Add parameters for handling bootstrap.sh version

cloud/jenkins/pxc_operator_gke_version.groovy
For some reason test reporter in gke param job was not running ok, so made it the same like in other jobs.
Had a test run here: https://cloud.cd.percona.com/job/tomislav-test/2/testReport/
=> Fix test reporter in pxc_operator_gke_version.groovy

pmm/pmm-2-0-documentation-md.groovy
In preparation for move from Sphinx to MkDocs as primary way to create static web site for PMM documentation.
=> PMM-6341 New for PMM + MkDocs

docker/docker_builder.sh, docker/percona-docker.groovy
Test pipeline job available at rel.cd
=> ENG-879: Implement pipeline for releasing dockers

cloud/jenkins/psmdb-docker.yml, cloud/jenkins/psmdb_docker_build.groovy
1. rename `IMAGE_PREFIX` to `IMAGE_SUFFIX` since it's not prefix
2. in `pushImageToDocker` function fix the tag construct which is pushed
=> K8SPSMDB-290 - fix pushing PSMDB docker images to dockerhub

pxb/percona-xtrabackup-2.4-template.yml
As we discussed in thread, I've already added them to template job in Jenkins
=> PXB-2248: Add missing types for template job of 2.4

pxb/percona-xtrabackup-8.0-template.yml
Builds: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/322/
=> PXB-2316: Add DEBIAN_FRONTEND before installing percona-release

pxb/percona-xtrabackup-2.4-param-medium.yml, pxb/percona-xtrabackup-2.4-param.yml, pxb/percona-xtrabackup-2.4-template.yml, pxb/percona-xtrabackup-8.0-param-medium.yml, pxb/percona-xtrabackup-8.0-param.yml, pxb/percona-xtrabackup-8.0-template.yml
This required for downloading a custom bootstrap.sh, without cherry-picking / altering branch
=> PXB-2325: Add ability to use custom bootstrap.sh

IaC/pxb.cd/init.groovy.d/cloud.groovy
It is required for new single-run jenkins job.
=> PXB-2333: Add 'docker' worker for PXB Jenkins

IaC/pxb.cd/init.groovy.d/cloud.groovy, pxb/percona-xtrabackup-2.4-param-medium.yml, pxb/percona-xtrabackup-2.4-param.yml, pxb/percona-xtrabackup-8.0-param-medium.yml, pxb/percona-xtrabackup-8.0-param.yml
@hors @EvgeniyPatlan Please review IaC before, so that I can start testing the pipelines
And xenial-x32 is not supported, should I implement the dockers for it? TIA
=> PXB-2327: Restructure OS for Param and Param-Medium 

cloud/jenkins/pxc_operator_aws_openshift-4.groovy, cloud/jenkins/pxc_operator_aws_openshift.groovy, cloud/jenkins/pxc_operator_eks.groovy, cloud/jenkins/pxc_operator_gke_version.groovy, cloud/jenkins/pxc_operator_lke_version.groovy
This needs to be merged when https://github.com/percona/percona-xtradb-cluster-operator/pull/649
gets merged.
=> CLOUD-579 - add upgrade group of tests for PXC operator

IaC/cloud.cd/JenkinsStack.yml, IaC/fb.cd/JenkinsStack.yml, IaC/pg.cd/JenkinsStack.yml, IaC/ps.cd/JenkinsStack.yml_ps3, IaC/ps56.cd/JenkinsStack.yml, IaC/ps57.cd/JenkinsStack.yml, IaC/ps80.cd/JenkinsStack.yml, IaC/psmdb.cd/JenkinsStack.yml, IaC/pt.cd/JenkinsStack.yml, IaC/pxc.cd/JenkinsStack.yml, IaC/rel.cd/JenkinsStack.yml
Implemented on rel:
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#rules:name=jenkins-rel-TerminationRule1-PNXYFNIJI18Z
https://eu-west-1.console.aws.amazon.com/sns/v3/home?region=eu-west-1#/topic/arn:aws:sns:eu-west-1:119175775298:jenkins-rel-TerminationSNSTopic-1P6FQMOOUZP09
=> ENG-937: Implement SNS alerting on spot termination

IaC/pxb.cd/init.groovy.d/cloud.groovy, pxb/percona-xtrabackup-2.4-template.yml, pxb/percona-xtrabackup-8.0-template.yml
8.0: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/342/
=> PXB-2342: CentOS 8 dependencies fixes

IaC/report-uptime.yml
It is required to have 1 executor on master instance.
Builds: https://rel.cd.percona.com/job/uptime-report/
=> ENG-936: Implement job for reporting a downtime

IaC/ps57.cd/init.groovy.d/cloud.groovy
Deployed on PS57, switched due to alerts
=> ENG-938: Change PS57 Spot instance type

IaC/SpotTerminationReport.yml, IaC/cloud.cd/JenkinsStack.yml, IaC/fb.cd/JenkinsStack.yml, IaC/pg.cd/JenkinsStack.yml, IaC/ps.cd/JenkinsStack.yml_ps3, IaC/ps56.cd/JenkinsStack.yml, IaC/ps57.cd/JenkinsStack.yml, IaC/ps80.cd/JenkinsStack.yml, IaC/psmdb.cd/JenkinsStack.yml, IaC/pt.cd/JenkinsStack.yml, IaC/pxc.cd/JenkinsStack.yml, IaC/rel.cd/JenkinsStack.yml
Deployed: 
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#rules:name=spot-termination-report-TerminationRule1-197XG7HDR3X22
https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/events?stackId=arn%3Aaws%3Acloudformation%3Aeu-west-1%3A119175775298%3Astack%2Fspot-termination-report%2F2059b470-2d9c-11eb-a5c2-0a0379f35b22&filteringText=&filteringStatus=active&viewNested=true&hideStacks=false
=> ENG-937: Rework SNS alerting of termination as single stack

pmm/pmm2-api-tests.groovy
https://jira.percona.com/browse/PMM-5106
=> PMM-5106 Disable STT tests for now

IaC/ps57.cd/init.groovy.d/cloud.groovy
=> ENG-947: Add CentOS 8 and Ubuntu Focal AMIs for ps57.cd

psmdb/jenkins/get-psmdb-branches-4.4.groovy, psmdb/jenkins/get-psmdb-branches-4.4.yml, psmdb/jenkins/percona-server-for-mongodb-4.4.groovy, psmdb/jenkins/percona-server-for-mongodb-4.4.yml
1. remove centos6 support from pipeline
2. rework approach to build all RPMs/DEBs/Binary tarballs in parallel
=> PSMDB-786 remove centos6 support

psmdb/jenkins/get-psmdb-branches-4.2.groovy, psmdb/jenkins/get-psmdb-branches-4.2.yml, psmdb/jenkins/percona-server-for-mongodb-4.2.groovy, psmdb/jenkins/percona-server-for-mongodb-4.2.yml
1. remove centos6 support from pipeline
2. rework approach to build all RPMs/DEBs/Binary tarballs in parallel
=> PSMDB-763 remove centos6 support 4.2

IaC/rel.cd/init.groovy.d/cloud.groovy
Deployed on rel.cd
As it was discussed on 1:1 with Mykola, we decided to unblock at least with m1 instance for now
=> ENG-933: Add xenial 32-bit support for rel.cd Jenkins

pxb/percona-xtrabackup-2.4-template.yml
Deployed: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/159/
=> PXB-2368: Update hardcoded galera57 tests and add additional checks

pmm/pmm2-api-tests.groovy, pmm/pmm2-ui-tests-nightly.groovy, pmm/pmm2-ui-tests.groovy
[PMM-6982](https://jira.percona.com/browse/PMM-6982)
https://github.com/percona/pmm-managed/pull/564
https://github.com/Percona-Lab/jenkins-pipelines/pull/681
https://github.com/Percona-Lab/pmm-submodules/pull/1286
=> PMM-6982 Remove PERCONA_TEST_IA.

pmm/aws-staging-start.groovy
Reverts Percona-Lab/jenkins-pipelines#680
=> Revert "PMM-7083 fix the pipeline aws-staging-start"

cloud/jenkins/psmdb_docker_build.groovy
* check of debug images fails due to timeout
=> CLOUD-600 fix timeout issue

pmm/pmm-2-0-documentation-md.groovy
Added boolean to trigger PDF build (which takes 3-4x longer than HTML). PDF is only needed for releases so this option saves time when building HTML previews.
=> Option to build PDF with MkDocs for PMM2

vars/uploadDEB.groovy, vars/uploadRPM.groovy, vars/uploadTarball.groovy
Reverts Percona-Lab/jenkins-pipelines#691
maintenance is over
=> Revert "ENG-956 Disable artifacts upload to storage"

IaC/pxc.cd/init.groovy.d/cloud.groovy
Tested and deployed on pxc.cd.percona.com, all workers created by this change were created and reported as "Online"
AMI which were added are official, and found on https://wiki.centos.org/Cloud/AWS & https://cloud-images.ubuntu.com/locator/ec2/
=> ENG-955: Add CentOS8 and Focal AMI images for PXC Jenkins

pmm/pmm2-client-autobuild.groovy
Tested on https://pmm.cd.percona.com/job/pmm2-client-autobuilds/2138/replay/
=> PMM-7138 fix pmm2-client-autobuild pipeline

pmm/pmm2-testsuite.groovy
Removing the Server_IP changes because they could not be fully implemented, this PR is to update the script with the one being run.
=> PMM-7151 & PMM-7083 Update testsuite job with node based changes 

pbm/jenkins/get-pbm-branches.groovy, pbm/jenkins/percona-mongodb-backup.groovy
1. remove centos6 support
2. add slack notifications,
3. build rpms\debs\tarball in parallel
4. fix upload path
=> PBM-611 PBM autobuild task rework

IaC/SpotTerminationReport.yml
Deployed:
Non PMM region: https://eu-central-1.console.aws.amazon.com/sns/v3/home?region=eu-central-1#/topic/arn:aws:sns:eu-central-1:119175775298:spotterminationnonpmm-SNSTopicREL-Y68Z3K9SIPC4
PMM region: https://console.aws.amazon.com/sns/v3/home?region=us-east-1#/topic/arn:aws:sns:us-east-1:119175775298:spotterminationpmm-SNSTopicPMM-1UMARZ1NAGHXU
=> ENG-961: Add alerting for PMM members

psmdb/jenkins/get-psmdb-branches-4.0.groovy, psmdb/jenkins/get-psmdb-branches-4.0.yml, psmdb/jenkins/percona-server-for-mongodb-4.0.groovy, psmdb/jenkins/percona-server-for-mongodb-4.0.yml
1. update task
2. set proper channel for notifacations releases-ci -> releases
3. remove centos6 support
=> PSMDB-768 update psmdb-40 autobuild task

IaC/psmdb.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
Currently deployed on REL.cd, the purpose is to remove infra/workers-related code from pipelines and move it to workers configruation
=> ENG-960: Add repo.ci definition to hosts file of PSMDB.cd and REL.cd Jenkins

IaC/pxb.cd/init.groovy.d/cloud.groovy
=> PXB-2327: Add xenial-32 for PXB.cd 

IaC/pxb.cd/init.groovy.d/cloud.groovy
=> PXB-2396: Correct devnames for PXB workers

pxc/local/build-binary-pxc, pxc/local/test-binary-pxc, pxc/pxc80-build.yml, pxc/qa-pxc80-build.yml
Build:https://pxc.cd.percona.com/job/pxc-8.0-pipeline-pxc-3490/1/
=> PXC-3490: Switch to devtoolset-8 for CentOS

pmm/pmm2-server-release.groovy
[PMM-7252 ](https://jira.percona.com/browse/PMM-7252)
Pls refer to the ticket for the details.
=> PMM-7252 fix dockerhub permissions

pmm/aws-staging-stop-robot.groovy
Tested on https://pmm.cd.percona.com/job/aws-staging-stop-robot/24423/console
=> PMM-7301 handle empty tags in pmm aws-stop-robot

IaC/pg.cd/JenkinsStack.yml, IaC/pt.cd/JenkinsStack.yml, IaC/rel.cd/JenkinsStack.yml
Deployed and synced with AWS
Removed instances types for pt, as they have high interruption rate.
=> ENG-970: Update rel/pg/pt Jenkins and sync with AWS

IaC/fb.cd/JenkinsStack.yml, IaC/ps.cd/JenkinsStack.yml_ps3, IaC/ps56.cd/JenkinsStack.yml, IaC/pxb.cd/terraform/master_user_data.sh
Deployed, no major errors spotted, EC2 and AWS SDK plugin were updated on PXB.
=> ENG-970: Update ps3/ps56/fb/pxb Jenkins and sync with AWS

IaC/ps57.cd/JenkinsStack.yml, IaC/ps80.cd/JenkinsStack.yml, IaC/psmdb.cd/JenkinsStack.yml, IaC/pxc.cd/JenkinsStack.yml
Deployed on mentioned jenkins.
=> ENG-970: Update ps57/ps80/psmdb/pxc Jenkins and sync with AWS

pmm/kubernetes-cluster-staging.groovy
Test Job Link: https://pmm.cd.percona.com/blue/organizations/jenkins/kubernetes-cluster-staging/detail/kubernetes-cluster-staging/2/pipeline
=> PMM-7304 Adding Job to create Cluster 

IaC/ps.cd/init.groovy.d/cloud-ps3.groovy, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy, IaC/psmdb.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxc.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
=> PS-7515: Use Percona CentOS 6 mirror for CentOS 6 workers

pmm/aws-staging-start.groovy
Tested the changes here: https://pmm.cd.percona.com/view/all/job/aws-staging-test-job/503/console
=> PMM-7352 Update AWS-Staging Job to use Library for spot Instance

IaC/pxb.cd/init.groovy.d/cloud.groovy, pxb/v2/docker/run-build, pxb/v2/docker/run-test, pxb/v2/jenkins/percona-xtrabackup-2.4-compile-param.yml, pxb/v2/jenkins/percona-xtrabackup-2.4-compile-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-2.4-compile-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-2.4-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-2.4-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-2.4-test-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-2.4.yml, pxb/v2/local/build-binary, pxb/v2/local/checkout, pxb/v2/local/test-binary, pxc/docker/install-deps
Link to job: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-multijob/3/
To remove before merge:
* Should be tracking percona-lab/jenkins-pipelines instead of my local repository
* Any yum/apt install command should be removed and pxc-build image updated
* IaC deployed permanently(currently just enabled in configureClouds jenkins menu)
=> PXB-2330: Implement split-job pipeline for PXB 2.4

IaC/rel.cd/init.groovy.d/cloud.groovy
Deployed on rel.cd
yum update is required to work with HTTPS repositories
=> PS-7513: Add min-centos-6-x32 for REL.cd Jenkins

pxb/v2/docker/run-test, pxb/v2/jenkins/percona-xtrabackup-8.0-compile-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-compile-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-compile-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.0.yml, pxb/v2/local/build-binary, pxc/docker/install-deps
Builds: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-multijob/1/
=> PXB-2330: Implement split-job pipeline for PXB 8.0 and little fixes for 2.4

IaC/pg.cd/JenkinsStack.yml, IaC/pt.cd/JenkinsStack.yml, IaC/rel.cd/JenkinsStack.yml
Deployed across all mentioned
Used latest AMI
=> ENG-970: Update rel.cd/pt.cd/pg.cd Jenkins to 2.263.3 and their OS

IaC/rel.cd/init.groovy.d/cloud.groovy
c4.xlarge interruption rate is 5-10%
=> Replace c4.xlarge with c5.xlarge for REL.cd Jenkins

IaC/ps57.cd/JenkinsStack.yml, IaC/pxc.cd/JenkinsStack.yml
=> ENG-970: Update ps57/pxc Jenkins to 2.263.3

IaC/ps80.cd/JenkinsStack.yml
=> ENG-970: Update ps80 Jenkins to 2.263.3

IaC/rel.cd/init.groovy.d/cloud.groovy
=> ENG-975: Add docker-32gb executor for REL.cd

pmm/kubernetes-cluster-staging.groovy, pmm/pmm2-ui-tests.groovy
Tested here: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-temp/detail/pmm2-ui-tests-temp/95/pipeline 
Allows UI tests pipeline to use the kubeconfiguration from cluster staging job.
=> PMM-7374 Preparing for using cluster setup job in UI tests

IaC/cloud.cd/JenkinsStack.yml
=> ENG-970: Update cloud.cd Jenkins to 2.263.3

pxb/jenkins/pxb24-single-platform-run.yml, pxb/jenkins/pxb80-single-platform-run.yml
Link to build: https://pxb.cd.percona.com/job/pxb80-single-platform-run/13/
=> PXB-2416: Add lz4 installation on Debian/Ubuntu for PXB8.0 single-run pipeline

IaC/cloud.cd/init.groovy.d/matrix.groovy
=> ENG-921: Implement matrix auth as IaaC for cloud.cd

pxb/percona-xtrabackup-8.0-template.yml
This was missed on friday, re-adding to old job as well
=> PXB-2416: Add missing lz4 on Debian/Ubuntu for old PXB8.0 job

IaC/cloud.cd/init.groovy.d/cloud.groovy, IaC/fb.cd/init.groovy.d/cloud.groovy, IaC/ps.cd/init.groovy.d/cloud-ps3.groovy, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxc.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
=> ENG-968: Rework AWSCLIv2 unzip with 7za

pxb/v2/docker/run-test, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy, pxb/v2/local/test-binary
Builds:  https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/13/
Will be reverted: 5f795fb before merge
=>  PXB-2423: Fix Junit not getting read

IaC/pmm.cd/init.groovy.d/matrix.groovy
=> PMM-7594: Add more rights for ext-sde on PMM.cd

pxc/local/test-binary-pxc57
Test job https://pxc.cd.percona.com/job/pxc-5.7-pipeline-pxc-3591/5/
=> PXC-3591: Replace broken sed statement for generating an JUnit for PXC

pxb/v2/jenkins/percona-xtrabackup-2.4-compile-param.yml, pxb/v2/jenkins/percona-xtrabackup-2.4-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-2.4-trunk.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-compile-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-trunk.yml, pxb/v2/local/test-binary
2.4 build: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-trunk/2/
8.0 build: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-trunk/2/
=> PXB-2329: Implement PXB 8.0 & 2.4 trunk and needed changes

pmm/pmm2-ovf-test.groovy, pmm/pmm2-ui-tests.groovy
This PR introduces a new option to enable running tests only for features that we support in OVF
=> Skip Dbaas Tests for OVF based UI tests execution

IaC/psmdb.cd/init.groovy.d/cloud.groovy
=> ENG-733: Update workers AMI for PSMDB.cd

IaC/ps.cd/init.groovy.d/cloud-ps3.groovy
=> ENG-733: Update workers AMI for PS3.cd

IaC/pg.cd/init.groovy.d/cloud.groovy
=> ENG-733: Update workers AMI for PG.cd

pxb/jenkins/pxb80-single-platform-run.yml
Needed for PXB single-run on 8.0.22 innodb target
=> PXB-2382: Add missing library needed for execution innodb80 target tests

IaC/fb.cd/init.groovy.d/cloud.groovy
=> ENG-733: Update workers AMI for FB.cd

IaC/cloud.cd/init.groovy.d/cloud.groovy, IaC/fb.cd/init.groovy.d/cloud.groovy, IaC/ps.cd/init.groovy.d/cloud-ps3.groovy, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxc.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
Deployed on rel `docker` worker
=> ENG-981: Cleanup /tmp from *aws* files before installing awscliv2

IaC/pmm.cd/init.groovy.d/cloud.groovy
=> ENG-979: Add missing workers for PMM.cd Jenkins

vars/installDocker.groovy
=> Change the Url for Pip

IaC/pmm.cd/init.groovy.d/cloud.groovy, vars/installDocker.groovy
Frontend job test: https://pmm.cd.percona.com/job/pmm2-frontend-amzn2/view/change-requests/job/PR-1/2/
UI-tests https://pmm.cd.percona.com/job/pmm2-ui-tests-amzn2/1/
Upgrade tests: https://pmm.cd.percona.com/job/pmm2-upgrade-tests-amzn2/3/
Deployment plan:
* Deploy new cloud.groovy, restart Jenkins
* Confirm by deploying workers manually
* Merge changes and perform test run
=> PMM-7672: Update PMM.cd IaC and PMM's pipelines for AMZN Linux 2 workers

IaC/pmm.cd/JenkinsStack.yml, IaC/pmm.cd/init.groovy.d/matrix.groovy
=> Correct matrix auth due to PMM Github-team rename

IaC/cloud.cd/init.groovy.d/cloud.groovy, IaC/fb.cd/init.groovy.d/cloud.groovy, IaC/pg.cd/init.groovy.d/cloud.groovy, IaC/pmm.cd/init.groovy.d/cloud.groovy, IaC/ps.cd/init.groovy.d/cloud-ps3.groovy, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy, IaC/psmdb.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxc.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
Mykola's variant of my PoC deployed on REL.cd for buster
Cleanup of obsolete OS will be in AMI&Plugins update PR
Further reconstruction of this file will be presented at rel-team channel by docs.google
=> ENG-733: Discover workers disks automatically without markers

pmm/pmm2-ui-tests.groovy
To avoid https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7412/pipeline
=> Fix the Flow with Stop job being called

pxb/percona-xtrabackup-8.0-template.yml, pxb/v2/local/test-binary
Build: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium-illiatests/2/BUILD_TYPE=debug,Host=min-centos-8-x64,xtrabackuptarget=xtradb80/
=> PXB-2437: Update PXB 8.0 pipelines to support working with Debug binaries

pmm/pmm2-ui-tests.groovy
https://github.com/Percona-Lab/pmm-submodules/pull/1610/files
=> UI test job without clients

IaC/ps56.cd/init.groovy.d/cloud.groovy
=> ENG-733: Update workers AMI for PS56.cd

IaC/pxb.cd/init.groovy.d/cloud.groovy
=> ENG-733: Update workers AMI for PXB.cd

pmm/kubernetes-cluster-staging.groovy
Have been tested with: https://github.com/percona/pmm-qa/pull/381 changes run on: https://pmm.cd.percona.com/job/kubernetes-cluster-staging/497/
=> Change Operator Version Default

pmm/pmm2-api-tests.groovy, pmm/pmm2-ui-tests-nightly.groovy
[PMM-7697](https://jira.percona.com/browse/PMM-7697)
PMM-managed: https://github.com/percona/pmm-managed/pull/704
=> PMM-7697 Enable backup management

pxc/local/test-binary-pxc
Build: https://pxc.cd.percona.com/job/pxc-8.0-pipeline-pxc-3621/2/
=> PXC-3621: Replace broken sed statement for generating an JUnit for PXC80

IaC/cloud.cd/JenkinsStack.yml, IaC/fb.cd/JenkinsStack.yml, IaC/pg.cd/JenkinsStack.yml, IaC/pmm.cd/JenkinsStack.yml, IaC/ps56.cd/JenkinsStack.yml, IaC/ps57.cd/JenkinsStack.yml, IaC/ps80.cd/JenkinsStack.yml, IaC/psmdb.cd/JenkinsStack.yml, IaC/pxb.cd/terraform/master_user_data.sh, IaC/pxc.cd/JenkinsStack.yml
PS3 implemented in: https://github.com/Percona-Lab/jenkins-pipelines/pull/858/commits/5f78052303d4c5105bde2a28b824ad7f3d04523e
REL implemented in: https://github.com/Percona-Lab/jenkins-pipelines/pull/861/commits/c8ed6ebb7f79fd003332e829e5bda9c7d6abf93c
=> ENG-994: Install latest version of java unconditionally

IaC/ps.cd/JenkinsStack_ps3.yml, IaC/ps.cd/init.groovy.d/cloud-ps3.groovy
Deployed on ps3 with plugins and workers update
Test Job URL: https://ps3.cd.percona.com/view/8.0/job/percona-server-8.0-param/197/
=> ENG-989: Update ps3.cd to 2.277.1

IaC/LambdaVolumeCleanup.yml
Deployed, little fix to correct python's code
=> ENG-984: Correct Python syntax in Cleanup Lambda

IaC/fb.cd/JenkinsStack.yml, IaC/fb.cd/init.groovy.d/cloud.groovy
Deployed with plugins and workers update
URL: https://fb.cd.percona.com/job/fb-mysql-server-8.0-param/251/
(please ignore failed tests, I've disabled them that's why they failed)
=>  ENG-989: Update fb.cd to 2.277.1

IaC/pg.cd/JenkinsStack.yml, IaC/pg.cd/init.groovy.d/cloud.groovy
Deployed on pg with plugins update and workers update,
job url: https://pg.cd.percona.com/job/pdmdb-parallel/92/
(failed few steps,  but no errors overall related to DSL)
=> ENG-989: Update pg.cd to 2.277.1

IaC/ps56.cd/JenkinsStack.yml, IaC/ps56.cd/init.groovy.d/cloud.groovy
Updated with plugins and workers update
URL: https://ps56.cd.percona.com/job/percona-server-5.6-param/147/
=> ENG-989: Update ps56.cd to 2.277.1

IaC/cloud.cd/init.groovy.d/cloud.groovy, IaC/fb.cd/init.groovy.d/cloud.groovy, IaC/ps.cd/init.groovy.d/cloud-ps3.groovy, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxc.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
Uninstall awscli v1 before, replace broken find by xargs(for PXC)
Tested on ps3
=> PS-7623: Update AWSCLI installation

pmm/pmm2-server-autobuild.groovy, pmm/pmm2-server-release.groovy, pmm/pmm2-submodules-rewind.groovy
Adding more parameters for the PMM server build to be able manually
release from the release branch.
DO NOT MERGE
=> PMM-6014 adding parameters for the builds

IaC/pmm.cd/JenkinsStack.yml, IaC/pmm.cd/init.groovy.d/cloud.groovy
Deployed with plugins and workers update
URL https://pmm.cd.percona.com/job/aws-staging-start/34435/
=> ENG-989: Update pmm.cd to 2.277.1

IaC/fb.cd/init.groovy.d/matrix.groovy, IaC/ps.cd/init.groovy.d/matrix.groovy, IaC/ps56.cd/init.groovy.d/matrix.groovy, IaC/ps57.cd/init.groovy.d/matrix.groovy, IaC/ps80.cd/init.groovy.d/matrix.groovy, IaC/psmdb.cd/init.groovy.d/matrix.groovy, IaC/pxb.cd/init.groovy.d/matrix.groovy, IaC/pxc.cd/init.groovy.d/matrix.groovy
Not deployed yet.
Current permissions created based on existing.
=> ENG-998: Matrix IaC for PXB/PXC/PS/PSMDB

proxysql/test-proxysql
- Added logic for installing mysql client when PXC version is 8.0
- Added logic for installing mysql client when PXC version is 5.7
- Adeed logic for installing proxysql package from testing repo
- Fixed the workdir structure
- Fixed the issue with localhost mapping in ipv6 enabled machines
=> PSQLADM-302 - Fixing the Jenkins job for ProxySQL (test-proxysql script)

proxysql/qa-proxysql2-pipeline.groovy
- Updated the ProxySQL fetch branch to 2.0.17
- Updated the ProxySQL admin branch to 2.0
- Set the default value to PXC-80 for running ProxySQL admin test suite
=> PSQLADM-302: Follow-up fix

pxc/docker/run-test56, pxc/local/test-binary-pxc56
Param job URL: https://pxc.cd.percona.com/job/pxc-5.6-param-junittest/1/
Can be merged only after https://github.com/Percona-Lab/jenkins-pipelines/pull/874 PR as it requires additional dependency in container.
=> PXC-3622: Implement JUnit output feature for 5.6

pxc/docker/install-deps, pxc/docker/run-test57, pxc/local/test-binary-pxc57
Param job URL: https://pxc.cd.percona.com/job/pxc-5.7-param-junittest/3/
Requires a rebuild of pxc-build docker image, should be performed after merge immediately.
=> PXC-3622: Implement JUnit output feature for 5.7

pxc/pxc57-build.yml
URL: https://pxc.cd.percona.com/view/PXC%205.7/job/pxc57-build/88/
=> ENG-1001: Fix installation of python for RHEL in pxc57-build job

pxc/jenkins/param.yml, pxc/jenkins/param56.yml, pxc/jenkins/param57.yml, pxc/jenkins/pxc56-pipeline.groovy, pxc/jenkins/pxc57-pipeline.groovy, pxc/jenkins/pxc57-pipeline.yml, pxc/jenkins/pxc80-pipeline.groovy, pxc/jenkins/pxc80-pipeline.yml, pxc/local/checkout, pxc/local/checkout56, pxc/local/checkout57
Build URL: https://pxc.cd.percona.com/view/PXC%208.0/job/pxc-8.0-pipeline-PXC-3481/7/
I used Kamil's PR(1409) to test it
=> PXC-3481: Add ability to build PXC56/57/80 from PR sources

IaC/fb.cd/JenkinsStack.yml, IaC/pg.cd/init.groovy.d/matrix.groovy, IaC/ps.cd/JenkinsStack_ps3.yml, IaC/ps.cd/init.groovy.d/matrix.groovy, IaC/ps56.cd/JenkinsStack.yml, IaC/ps56.cd/init.groovy.d/matrix.groovy, IaC/ps57.cd/JenkinsStack.yml, IaC/ps57.cd/init.groovy.d/matrix.groovy, IaC/ps80.cd/JenkinsStack.yml, IaC/ps80.cd/init.groovy.d/matrix.groovy, IaC/psmdb.cd/init.groovy.d/matrix.groovy, IaC/pxb.cd/init.groovy.d/matrix.groovy, IaC/pxc.cd/JenkinsStack.yml, IaC/pxc.cd/init.groovy.d/matrix.groovy
Deployed on FB/PSMDB/PS3/PS56/PS57/PXB/PG
=> ENG-998: Deploy Github OAuth across fb/psmdb/ps3/ps56/ps57/pxb/pg

proxysql/build-binary-proxysql
Missed to add cmake package for CentOS 8
=> PSQLADM-317 - Followup fix

IaC/fb.cd/JenkinsStack.yml, IaC/fb.cd/init.groovy.d/cloud.groovy, IaC/ps.cd/JenkinsStack_ps3.yml, IaC/ps.cd/init.groovy.d/cloud-ps3.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/terraform/master_user_data.sh
=> ENG-1000: Update ps3/fb/pxb Jenkins to 2.277.2

IaC/ps56.cd/JenkinsStack.yml, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/JenkinsStack.yml, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/pxc.cd/JenkinsStack.yml, IaC/pxc.cd/init.groovy.d/cloud.groovy
Deployed with plugins & workers update
=> ENG-1000: Update ps56/ps57/pxc to 2.277.2

pmm/pmm2-package-testing.groovy, pmm/pmm2-package-tests-matrix.groovy
Ready for Reivew: 
Matrix job example is [here](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-package-tests-matrix/detail/pmm2-package-tests-matrix/2/pipeline)
Package Testing Job Example [here](https://pmm.cd.percona.com/blue/organizations/jenkins/package-testing-temp/detail/package-testing-temp/41/pipeline)
Will rename the job and change configuration as soon as PR is ready for merge.
=> PMM-7945 Package Testing Job for PMM Client

IaC/ps57.cd/init.groovy.d/cloud.groovy
=> PS-7650: Install AWSCLI for CentOS platforms as well

IaC/psmdb.cd/JenkinsStack.yml, IaC/psmdb.cd/init.groovy.d/cloud.groovy
Deployed on Friday with plugins & workers update
=> ENG-1000: Update PSMDB.cd to 2.277.2

IaC/pmm.cd/init.groovy.d/matrix.groovy
Rights are read-only and build
=> Add PMM Contributors team to have an access on PMM.cd

pmm/aws-staging-start.groovy, pmm/pmm2-package-tests-matrix.groovy, pmm/pmm2-testsuite.groovy, pmm/pmm2-ui-tests.groovy, pmm/pmm2-upgrade-tests-matrix.groovy, pmm/pmm2-upgrade-tests.groovy
Along with some changes for testing-related jobs, to be able to test upgrades and packages for both dev-latest and RC builds. 
some test AWS-Staging jobs executed with new changes: https://pmm.cd.percona.com/job/aws-staging-test-job/538/
https://pmm.cd.percona.com/job/aws-staging-test-job/539/
=> PMM-6014 AWS Staging changes for Default repo's 

IaC/pmm.cd/init.groovy.d/cloud.groovy, vars/installDocker.groovy
Needed for https://github.com/Percona-Lab/percona-images/pull/102/files#diff-42ed8fd585d0c3b70f931aed28b8974160bf9267254c51011bb25a21ef7ce08dR89
=> PMM-3352: Set higher limits for Docker

IaC/ps80.cd/init.groovy.d/cloud.groovy
=> ENG-1011: Increase disk size of PS80 workers for package-testing job

IaC/JenkinsArtifactoryIAM.yml, IaC/StagingStack.yml, pmm/aws-staging-start.groovy, pmm/aws-staging-stop-robot.groovy, pmm/aws-staging-stop.groovy, pmm/kubernetes-cluster-staging.groovy, pmm/pmm2-ami-staging-start.groovy, pmm/pmm2-ami-staging-stop.groovy, pmm/pmm2-ami.groovy, pmm/pmm2-ovf.groovy, pmm/pmm2-server-autobuild.groovy, pmm/pmm2-server-release.groovy, vars/launchSpotInstance.groovy
* AWS-Staging-start: https://pmm.cd.percona.com/job/aws-staging-start-illiatests/6/
* AWS-Staging-stop: https://pmm.cd.percona.com/job/aws-staging-stop-illiatests/3/
* K8S https://pmm.cd.percona.com/job/kubernetes-cluster-staging-illiatests/4/
StagingStack.yml changes -- only for PMM / PMM jobs
JenkinsArtifactoryIAM.yml -- for other Jenkins which are using AMI/OVF credentials(binded to Jenkins-pmm-slave), for example: PSMDB/PG/PS80/57/ETC
=> ENG-1009: Implement IAM components which are used in PMM in pmm-staging stack

pmm/pmm2-package-tests-matrix.groovy
exclude install and update, just run integration tests on cron.
=> PMM-7908 remove parallel execution

pmm/kubernetes-cluster-staging.groovy
Due to request failure, changing instance type.
=> Changing Instance type for Cluster Instances

IaC/JenkinsArtifactoryAndSpawnIAM.yml
Deployed on psmdb/pg and tested
=> ENG-1009: Implement separate user with spawning instances permissions

pmm/pmm2-upgrade-tests.groovy
Has been tested here: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests-temp/detail/pmm2-upgrade-tests-temp/14/pipeline
=> PMM-8123 get Agent Log

pmm/pmm2-ui-tests-nightly.groovy
Need to be able to set multiple client instances with different DB combinations as part of our Nightly job setup, currently, the instance runs out of memory in 30 mins resulting in tests failures and blocking us from adding more tests scenarios to the nightly job, the setup was already tested last week. 
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-nightly-temp/detail/pmm2-ui-tests-nightly-temp/31/pipeline (ignore failure on UI tests)
=> PMM-7993 use multiple client nodes to avoid client run out of memory

pmm/pmm2-ovf-test.groovy, pmm/pmm2-ui-tests.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ovf-image-test/detail/pmm2-ovf-image-test/2221/pipeline
=> PMM-7983 fix OVF job

IaC/psmdb.cd/init.groovy.d/cloud.groovy
Issue appeared in https://psmdb.cd.percona.com/job/percona-server-for-mongodb-master-param/240/
Test build: https://psmdb.cd.percona.com/job/percona-server-for-mongodb-master-param/246/
Deployed on PSMDB.cd
=> ENG-1016: Increase disk sizes of workers on PSMDB.cd

pxb/percona-xtrabackup-8.0-template.yml, pxc/docker/install-deps
Builds: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/76/
=> PXB-2509: Add GCC 10 support for PXB

IaC/rel.cd/init.groovy.d/cloud.groovy
=> Fix /mnt mount for CentOS 6 x32 on REL.cd

IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy
=> PS-7701: Add min-amazon-2-x64 worker for package-testing

pmm/aws-staging-start.groovy
Reverts Percona-Lab/jenkins-pipelines#984
=> Revert "PMM-3352: Set higher limits for Docker in aws-staging-start job"

rel/jenkins/check-remote-repo.groovy
Deployed and tested, notification after this change was delivered to corresponding channel
=> ENG-1018: Correct stash() in check-remote-repo pipeline

IaC/cloud.cd/init.groovy.d/cloud.groovy
Old AMI's stuck on spawning, deployed on cloud.cd
=> Update Cloud.cd's workers AMI

IaC/ps57.cd/init.groovy.d/cloud.groovy
Deployed on ps57, needed for package-testing
=> Increase disk sizes for package-testing on PS5.7.cd

pxc/jenkins/pxc80-pipeline.groovy, pxc/jenkins/pxc80-pipeline.yml
Already set in Jenkins GUI, but I forgot to commit into pipeline sources
=> PXC-3671: Set PXB80_LATEST true by default

IaC/psmdb.cd/init.groovy.d/cloud.groovy
=> Increase disk size of psmdb-bionic for PSMDB.cd

pxb/percona-xtrabackup-2.4-template.yml, pxb/percona-xtrabackup-8.0-template.yml
Builds: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/183/
=> PXB-2523: Correct issues with building and testing

pxc/local/build-binary-pxc
Builds: https://pxc.cd.percona.com/job/pxc-8.0-pipeline-PXC-3672/2/
=> PXC-3672: Do not replace dash with dot in PERCONA_SERVER_EXTENSION variable for PXC80

IaC/ps56.cd/JenkinsStack.yml, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/JenkinsStack.yml, IaC/ps57.cd/init.groovy.d/cloud.groovy
ps57: https://ps57.cd.percona.com/job/percona-server-5.7-param/461/
ps56: https://ps56.cd.percona.com/job/percona-server-5.6-param/149/
=> ENG-733: Update ps56/57.cd to 2.289.1 and AMI to latests

cloud/jenkins/pbm_docker_build.groovy, cloud/jenkins/psmdb_docker_build.groovy
* top to build psmdb 3.6 docker images
* update go version to fix pbm build
=> CLOUD-627 update go version to fix pbm build

pxb/percona-xtrabackup-2.4-template.yml, pxb/v2/local/test-binary
Builds: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium-illiatest/7/
=> PXB-2512: Update PXB 2.4 pipelines to support working with Debug binaries

IaC/psmdb.cd/JenkinsStack.yml, IaC/psmdb.cd/init.groovy.d/cloud.groovy
Builds: https://psmdb.cd.percona.com/job/percona-server-for-mongodb-4.2-param/173/
=> ENG-733: Update psmdb.cd to 2.289.1

cloud/jenkins/psmdb_operator_aws_openshift-4.groovy, cloud/jenkins/psmdb_operator_aws_openshift.groovy, cloud/jenkins/psmdb_operator_eks.groovy, cloud/jenkins/psmdb_operator_gke_version.groovy, cloud/jenkins/psmdb_operator_lke_version.groovy, cloud/jenkins/psmdb_operator_minikube.groovy, cloud/jenkins/pxc_operator_aws_openshift-4.groovy, cloud/jenkins/pxc_operator_aws_openshift.groovy, cloud/jenkins/pxc_operator_eks.groovy, cloud/jenkins/pxc_operator_gke_version.groovy, cloud/jenkins/pxc_operator_lke_version.groovy, cloud/jenkins/pxc_operator_minikube.groovy
Fix for PSMDB GKE job not showing test results in jenkins.
=> Fixes for cloud PSMDB GKE pipeline

IaC/pmm.cd/JenkinsStack.yml, IaC/pmm.cd/init.groovy.d/cloud.groovy
Builds:  https://pmm.cd.percona.com/job/aws-staging-start/38365/
=> ENG-733: Update pmm.cd to 2.289.1

IaC/fb.cd/JenkinsStack.yml, IaC/fb.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/terraform/master_user_data.sh
PXB: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/80/
FB: https://fb.cd.percona.com/job/fb-mysql-server-8.0-param/254/ (ignore failed builds, tests were disabled)
=> ENG-733: Update fb.cd/pxb.cd to 2.289.1

pxb/percona-xtrabackup-2.4-param-medium.yml, pxb/v2/jenkins/percona-xtrabackup-2.4-test-param.yml, pxb/v2/local/test-binary
Builds: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-multijob/19/
=> PXB-2512: Correct execution of run.sh script for Debug builds

pxc/jenkins/pxc56-pipeline.groovy, pxc/jenkins/pxc57-pipeline.groovy
PXC57 and PXC56 uses PXC57_BRANCH and PXC56_BRANCH variables as parameter instead of BRANCH like PXC80
=> PXC-3693: Correct variable usage for USE_PR feature

IaC/pxc.cd/JenkinsStack.yml, IaC/pxc.cd/init.groovy.d/cloud.groovy
Update was deployed
ENG-1023 commit:
I've added corresponding labels for each worker, to decrease billing, I've made micro-amazon & docker multiuse
Tests can be demonstrated on DS
=> ENG-733: Update pxc.cd to 2.289.1

pbm/pbm-documentation.groovy, pbm/pbm-documentation.yml
pbm/pbm-documentation.groovy
pbm/pbm-documentation.yml
=> PBM doc build with Sphinx

pxb/percona-xtrabackup-2.4-param-medium.yml, pxb/percona-xtrabackup-2.4-param.yml, pxb/percona-xtrabackup-2.4-template.yml
Builds: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-illiatest/20/
=> PXB-2533: Fix galera56/xtradb56 failures

IaC/JenkinsArtifactoryAndSpawnIAM.yml
=> ENG-1033: Add needed permissions to JenkinsSpawn IAM user

IaC/JenkinsArtifactoryIAM.yml, IaC/JenkinsImagesECR.yml, IaC/pmm.cd/init.groovy.d/cloud.groovy
Pipeline part: https://github.com/Percona-Lab/pmm-submodules/pull/1873
RPMBuild job: https://pmm.cd.percona.com/job/prepare-rpmbuild-docker-ecr/9/
=> PMM-8279: Create ECR repo for rpmbuild image

pmm/pmm2-server-autobuild.groovy
Reverts Percona-Lab/jenkins-pipelines#1068
=> Revert "Revert "PMM-8266 remove prometheus from autobuild""

IaC/rel.cd/init.groovy.d/cloud.groovy, ps/jenkins/percona-server-for-mysql-8.0.groovy
Build: 
Part of: https://github.com/Percona-Lab/jenkins-pipelines/pull/1075
=> PS-7764: Add support for ZenFS building on REL.cd

pxb/v2/jenkins/percona-xtrabackup-2.4-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy, pxb/v2/local/test-binary
Builds: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-multijob-illiatests/3/
=> PXB-2546: Convert unreadable characters properly for JUnit

IaC/cloud.cd/init.groovy.d/cloud.groovy
Test results: https://cloud.cd.percona.com/view/PSMDB/job/psmdb-docker-build/839/
=> ENG-1032: Increase root volume for cloud.cd's docker workers

pxc/jenkins/pxc56-pipeline.groovy, pxc/jenkins/pxc57-pipeline.groovy, pxc/jenkins/pxc80-pipeline.groovy
Builds: https://pxc.cd.percona.com/job/pxc-8.0-param-PXC-3705/1/
=> PXC-3705: Implement cleanup steps on test stage for PXC pipelines

IaC/pg.cd/JenkinsStack.yml, IaC/pg.cd/init.groovy.d/cloud.groovy
Builds: https://pg.cd.percona.com/view/PDMDB/job/pdmdb-parallel/139/
=> ENG-733: Update pg.cd to 2.289.2

pmm/pmm2-ui-tests.groovy
as part to stabilize the UI tests builds, we need to reduce the number of false positives 
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-temp/detail/pmm2-ui-tests-temp/582/pipeline
=> PMM-8423 move dbaas tests to seperate job

pmm/pmm2-ami-upgrade-tests-matrix.groovy, pmm/pmm2-ami-upgrade-tests.groovy, pmm/pmm2-ovf-test.groovy
Fixed AMI upgrade setup, OVF UI test job with docker-compose setup
=> PMM-8339 fix OVF UI tests job

IaC/ps3.cd/JenkinsStack.yml, IaC/ps3.cd/init.groovy.d/cloud.groovy
=> ENG-733: Update ps3.cd to 2.289.2

IaC/ps3.cd/init.groovy.d/cloud.groovy, IaC/ps56.cd/init.groovy.d/cloud.groovy, IaC/ps57.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy, IaC/psmdb.cd/init.groovy.d/cloud.groovy, IaC/pxb.cd/init.groovy.d/cloud.groovy, IaC/pxc.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
FB / CLOUD / PG are using docker only structure
=> ENG-1039: Add Debian 11 for all Cloud Jenkins

pmm/pmm2-dbaas-e2e-tests.groovy
To avoid failing FB's and to reduce time on FB's we want to separately run dbaas e2e post pmm2-server autobuild. 
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/activity
=> PMM-8423 adding seperate job for dbaas e2e

pmm/pmm2-ui-tests.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-temp/detail/pmm2-ui-tests-temp/598/pipeline
=> PMM-8361 passing credentials for S3

pmm/aws-staging-start.groovy, pmm/pmm2-ami-staging-start.groovy, pmm/pmm2-upgrade-tests.groovy
Sorry for the format fixes, there are not many of them.
=> Use latest percona release

pxc/docker/run-test, pxc/local/test-binary-pxc
Builds: https://pxc.cd.percona.com/job/pxc-8.0-param-PXC-3622/4
=> PXC-3622: Implement junit-output feature for 8.0

IaC/ps3.cd/init.groovy.d/cloud.groovy, IaC/ps80.cd/init.groovy.d/cloud.groovy, IaC/rel.cd/init.groovy.d/cloud.groovy
=> PS-7836: Add ZenFS patched focal for ps3/ps80/rel

cloud/jenkins/psmdb-operator-gke-version.yml, cloud/jenkins/psmdb-operator-lke-version.yml, cloud/jenkins/psmdb_operator_aws_openshift-4.groovy, cloud/jenkins/psmdb_operator_aws_openshift-latest.groovy, cloud/jenkins/psmdb_operator_eks.groovy, cloud/jenkins/psmdb_operator_gke_latest.groovy, cloud/jenkins/psmdb_operator_gke_version.groovy, cloud/jenkins/psmdb_operator_lke_version.groovy, cloud/jenkins/psmdb_operator_minikube.groovy, cloud/jenkins/pxc-operator-gke-version.yml, cloud/jenkins/pxc-operator-lke-version.yml, cloud/jenkins/pxc_operator_aws_openshift-4.groovy, cloud/jenkins/pxc_operator_aws_openshift-latest.groovy, cloud/jenkins/pxc_operator_eks.groovy, cloud/jenkins/pxc_operator_gke_latest.groovy, cloud/jenkins/pxc_operator_gke_version.groovy, cloud/jenkins/pxc_operator_lke_version.groovy, cloud/jenkins/pxc_operator_minikube.groovy
This adds platform version to test results file name in S3 where missing and replaces `GKE_VERSION`, `LKE_VERSION`, `OS_VERSION`, `KUBER_VERSION` with just `PLATFORM_VER` so it's the same in all files.
=> Add platform version to test result file name

pmm/pmm2-dbaas-e2e-tests.groovy, pmm/pmm2-e2e-master.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-e2e-master/
To help test changes on all jobs at one go, to be manually run only by Automation Team
=> PMM-8423 add PMM e2e master pipeline

cloud/jenkins/pgo_operator_aws_openshift-4.groovy, cloud/jenkins/pgo_operator_eks.groovy
gsutil is used in demand-backup test for container
cleanup
=> K8SPG-90 Add auth for gsutil

IaC/psmdb.cd/JenkinsStack.yml, IaC/psmdb.cd/init.groovy.d/cloud.groovy
=> ENG-733: Update psmdb.cd to 2.289.2

pxb/v2/docker/run-test, pxb/v2/jenkins/percona-xtrabackup-2.4-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-2.4-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy, pxb/v2/local/test-binary
Builds: https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param-illiatests/13/
=> PXB-2572: Archive results directory for debugging purposes for both PXB

IaC/JenkinsImagesECR.yml, pmm/aws-staging-start.groovy, pmm/pmm2-api-tests.groovy, pmm/pmm2-package-testing.groovy, pmm/pmm2-package-tests-matrix.groovy, pmm/pmm2-server-autobuild.groovy, pmm/pmm2-server-release.groovy, pmm/pmm2-testsuite.groovy, pmm/pmm2-ui-compare-tests.groovy, pmm/pmm2-ui-tests-nightly.groovy, pmm/pmm2-ui-tests.groovy, pmm/pmm2-upgrade-tests.groovy, vars/installAWSv2.groovy
Builds:
* AWS: https://pmm.cd.percona.com/job/aws-staging-start-illiatests/
* Autobuild: https://pmm.cd.percona.com/job/pmm2-server-autobuild-illiatests/3/
* UI tests: https://pmm.cd.percona.com/job/pmm2-ui-tests-illiatests/2/
=> PMM-8309: [Pipelines] Migrate pmm-server:dev-latest to ECR

pmm/aws-staging-start.groovy, pmm/pmm2-ui-tests.groovy
Changing default MS version to setup as 8.0.x
=> PMM-8328 Adding setup for ssl mongodb and mysql options

IaC/scripts/cleanup_repo_script.sh
Introducing repo cleanup script
It supports two modes:
* Cleanup by date `--mode=date --older_than=<days>`
* Remove all except latest versions: `--mode=latest`
By date:
* Supports excludes without <ELVER>.rpm suffix
* Excludes mentioned version from ALL EL versions at the same time
Results of cleanup posted in rel-team as txt files
=> ENG-881: Implement repo cleanup script

psmdb/jenkins/percona-server-for-mongodb-4.0.groovy
1. minor improvements: add used branch to job build info
=> PSMDB-898 add build for Debial 11

pmm/pmm-ami.groovy, pmm/pmm-ovf.groovy, pmm/pmm2-ami.groovy, pmm/pmm2-ovf.groovy
https://github.com/Percona-Lab/pmm-submodules/pull/2015
=> PMM-6013 rename pmm-server main branch

pmm/pmm2-ui-tests.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/9962/pipeline/
=> PMM-8754 MongoDB backup restore

psmdb/psmdb-multi-parallel.groovy, psmdb/psmdb-multi.groovy, psmdb/psmdb-tarball-all-os.groovy, psmdb/psmdb-tarball-all-os.yml, psmdb/psmdb-tarball-all-setups.groovy, psmdb/psmdb-tarball-all-setups.yml, psmdb/psmdb-tarball-multi.groovy, psmdb/psmdb-tarball-multi.yml, psmdb/psmdb-tarball.groovy, psmdb/psmdb-tarball.yml
1) **psmdb-tarball**  for running upgrade/functional tests on specific os and specific setup
2) **psmdb-tarball-all-setups** for running upgrade/functional tests on specific os and all possible setups
3) **psmdb-tarball-all-os** for running upgrade/functional tests on all possible os
4) main release job **psmdb-tarball-multi** which should run tests on all setups and os
=> PSMDB-919 tests for psmdb tarball

ppg/ppg-12-documentation-md.groovy
modified:   ppg/ppg-12-documentation-md.groovy
=> DISTPG-323 Updated the job to build docs with changed MkDocs configuration

ppg/ppg-13-documentation-md.groovy
modified:   ppg/ppg-13-documentation-md.groovy
=> DISTPG-323 Updated the job to build docs with changed MkDocs configuration PPG 13

pmm/pmm2-ami-upgrade-tests.groovy, pmm/pmm2-dbaas-e2e-tests.groovy, pmm/pmm2-testsuite.groovy, pmm/pmm2-ui-pmmdemo-tests.groovy, pmm/pmm2-ui-tests-nightly.groovy, pmm/pmm2-ui-tests.groovy, pmm/pmm2-upgrade-tests.groovy, vars/setupNodejs.groovy
We have an ongoing issue with the latest release https://github.com/nodesource/distributions/issues/1290 and this causes all test jobs to fail, I need this hotfix and once the issue will be fixed, I will change the install script file with a proper fix. 
A test job was triggered here: 
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-temp/detail/pmm2-ui-tests-temp/636/pipeline
=> PMM-7 Fix issue with Node setup failure on test jobs. 

psmdb/psmdb-regression.groovy
Separate node for running unittests on. To run tests we have to build binaries and store them locally to have possibility to reuse them if needed. Node label could be changed in the future according to the required free disk space.
=> PSMDB-938 unittests

pxc/pxc80-build.yml
=> PXC-3808 Add libkrb5-dev libsasl2-dev and libsasl2-modules

cloud/jenkins/pgo_operator_gke_version.groovy
As a step to parallelization we need to differentiate
cluster by PG version
=> K8SPG-145 Add PG major version to cluster names

orchestrator/jenkins/orchestrator-pipeline.groovy, orchestrator/jenkins/orchestrator.yml, orchestrator/local/checkout, orchestrator/local/run-integration-tests, orchestrator/local/run-system-tests
https://jira.percona.com/browse/DISTMYSQL-140
Jenkins scripts for Orchestrator development purposes
=> DISTMYSQL-140: Create dev Jenkins pipeline for Orchestrator

IaC/ps3.cd/JenkinsStack.yml, IaC/ps3.cd/init.groovy.d/matrix.groovy
Update jenkins to 2.319.1
Fix groups names in matrix.groovy due to the changes in github-oauth 0.35 plugin
=> ENG-733 ps3.cd update to 2.319.1

pmm/infrastructure/rpm-build.groovy
We build rpmbuild image by hand. It doesn't look right. I added a pipeline for this.
=> PMM-7 create a pipeline for rpmbuild

pmm/pmm2-release.groovy, pmm/v1/pmm-server-release.groovy, ps-pxc-dist/Jenkinsfile.groovy, vars/sync2Prod.groovy, vars/sync2ProdAutoBuild.groovy, vars/sync2ProdDBaas.groovy, vars/sync2ProdPMM.groovy, vars/syncRepo.groovy
Repo CDN nodes were taken down and there is no need to run the clear cdn cache process anymore
=> [ENG-1089] Remove CDN sync

pxb/v2/local/checkout
https://jira.percona.com/browse/PXB-2693
Adjusted checkout script to also initialize submodules.
=> Fixed PXB-2693 - initialize submodules

pxb/percona-xtrabackup-8.0-template.yml
https://jira.percona.com/browse/PXB-2686
Adjusted list of packages to install procps.
=> Fixed PXB-2686 (install procps on jenkins images)

pmm/pmm2-ui-tests-nightly.groovy, pmm/pmm2-ui-tests.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-nightly-temp/detail/pmm2-ui-tests-nightly-temp/80/pipeline/
=> PMM-9514 tweak nightly job

pmm/aws-staging-start.groovy, pmm/pmm2-ui-tests-nightly.groovy, pmm/pmm2-ui-tests.groovy, pmm/pmm2-upgrade-tests.groovy
[nightly](https://pmm.cd.percona.com/job/pmm2-ui-tests-nightly-temp/114/allure/)
[staging](https://pmm.cd.percona.com/blue/organizations/jenkins/aws-staging-start-temp/activity/)
=> PMM-9677 change admin password

pmm/pmm2-server-autobuild.groovy, pmm/pmm2-submodules.groovy
=> PMM-9752 add pmm-dump to the build

pmm/kubernetes-cluster-staging.groovy, vars/launchSpotInstance.groovy
I fixed the issue when the price of the spot instance was lower than the FAIR price (for example it may have changed during job execution)
Also, we'll need to rewrite to Python.
=> PMM-9438 fix FAIR price for AWS

pmm/pmm2-ami.groovy, pmm/pmm2-client-autobuild.groovy, pmm/pmm2-prepare-release-candidate.groovy
I want to move `pmm2-prepare-release-candidate.groovy` to docker-farm
+ added `pmm-dump`
=> PMM-7 add PMM dumb to RC

pmm/pmm2-ovf-test.groovy
I moved the DO agent to our regular agent template and now agent in DO and AWS are almost the same
=> PMM-7 move pmm2-ovf-test to a new agent

pxc/jenkins/pxc80-pipeline.groovy
=> PXC-3730 PXC8 jenkins jobs should use lates PXB version

ps/jenkins/percona-server-for-mysql-8.0.groovy
=> PS add tarball build on Ubuntu 18.04

pmm/aws-portal-start.groovy, pmm/aws-staging-start.groovy, pmm/kubernetes-cluster-staging.groovy, vars/getSHHKeysPMM.groovy
1. I added default SSH keys for GitHub to stagings.
2. Switched to a new docker farm for a staging job
3. Use `FAIR` price. It should reduce price on 1/3
=> Pmm 7 add default keys for staging

pmm/aws-staging-start.groovy
Yeah, id does look ugly on the blue interface and does not render the link
=> PMM-7 revert the instance description

pxb/jenkins/checkout, pxc/jenkins/pxc80-pipeline.groovy
Changes are tested [here](https://ps3.cd.percona.com/view/PXC/job/pxc-8.0-test-pipeline/)
=> PXC-3707 Use PXB packages/tarballs in PXC Jenkins pipeline

ppg/get-pg_stat_monitor-branches.groovy, ppg/get-pg_stat_monitor-branches.yml, ppg/pg_stat_monitor-autobuild.groovy, ppg/pg_stat_monitor-autobuild.yml
=> PG-348 Create an automated daily build process

pmm/pmm2-ui-tests.groovy
Temp Run:
https://pmm.cd.percona.com/job/pmm2-ui-tests-temp/804/
https://pmm.cd.percona.com/job/pmm2-ui-tests-temp/804/allure/#suites
=> PMM-7 Skipped PMM-Portal-Upgrade Tag

pmm/aws-staging-start.groovy, vars/launchSpotInstance.groovy
We use our `agent` image instead base Amazon Linux 2 for staging.
=> PMM-7 use agent on staging

pmm/pmm2-package-testing.groovy
Reverts Percona-Lab/jenkins-pipelines#1523
=> Revert "PMM-7 remove conditional bullseye execution"

pmm/pmm2-ami-upgrade-tests.groovy
Disable upgrading packages, causing DB docker containers to stop working
=> PMM-7 AMI upgrade 

cloud/jenkins/pxc_containers_docker_build.groovy
Use junit template to make  the report  more distinct
=> CLOUD-702 improve Trivy report

pmm/kubernetes-cluster-staging.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/kubernetes-cluster-staging-temp/detail/kubernetes-cluster-staging-temp/11/pipeline/
=> add kubernetes version choice

pmm/aws-staging-start.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/aws-staging-start-beata-temp/detail/aws-staging-start-beata-temp/5/pipeline
=> add option to pass dev or prod version service

pmm/kubernetes-cluster-staging.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/kubernetes-cluster-staging-beata-temp/detail/kubernetes-cluster-staging-beata-temp/9/pipeline
=> PMM-7 add option to install operators

pmm/pmm2-upgrade-portal-tests.groovy
Added autobuild according to conversation with Puneet, and added ability to be notified about job result. Default value is no personal notification
https://pmm.cd.percona.com/job/pmm2-upgrade-portal-tests-temp/235/
=> Autobuild and slack noitification

pmm/pmm2-prepare-release-candidate.groovy
https://jira.percona.com/browse/PMM-10008
=> PMM-10008 Move pmm-agent and pmm-admin to pmm repo

pmm/pmm2-ui-tests.groovy
UI tests were failing on password change on PMM 2.26.0 and older this PR fixes that
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-temp/detail/pmm2-ui-tests-temp/811/pipeline
=> Fix UI tests for PMM 2.26.0 and older

proxysql/build-binary-proxysql, proxysql/qa-proxysql2-pipeline.groovy
=> PSQLADM-396 proxy sql jenkins job is failing on centos 8

cloud/jenkins/pgo_operator_gke_latest.groovy, cloud/jenkins/pgo_operator_gke_version.groovy, cloud/jenkins/ps_operator_gke_version.groovy, cloud/jenkins/psmdb_operator_gke_latest.groovy, cloud/jenkins/psmdb_operator_gke_version.groovy, cloud/jenkins/pxc_operator_gke_latest.groovy, cloud/jenkins/pxc_operator_gke_version.groovy
https://cloud.cd.percona.com/job/pxc-operator-gke-latest/152/ 
you can check these logs and see that there no errors connected with gke-gcloud-auth-plugin anymore.
=> Cloud-710 use gke-gcloud-auth-plugin by default

pmm/pmm2-package-testing.groovy
Reverts Percona-Lab/jenkins-pipelines#1624
=> Revert "PMM-7 disable RHEL-9"

pmm/pmm2-package-testing.groovy
=> PMM-7 Remove Rhel9 for test jobs

pmm/pmm2-release.groovy
We moved content from pmm-managed to pmm repo
=> PMM-7 fix pmm-managed repo name

vars/pdmdbOperatingSystems.groovy
We will merge this after 4.2.21 and 4.4.15 releases
=> PSMDB-1041 added ubuntu jammy

cloud/jenkins/pgo_operator_gke_latest.groovy, cloud/jenkins/pgo_operator_gke_version.groovy
- use pg specific VPC
- set actual GKE default version
=> K8SPG-239 Minor update

pmm/pmm2-submodules.groovy
We can't use bashslashes in pipelines
=> PMM-7 fix pmm-submodules pipeline

pmm/pmm2-dbaas-e2e-tests.groovy
I removed internal stage from the job
=> PMM-7 fix dbaas job

pmm/pmm2-submodules.groovy
add correct branch name and fix api url
=> fix github workflow trigger

cloud/jenkins/psmdb_operator_aws_openshift-4.groovy, cloud/jenkins/psmdb_operator_eks.groovy, cloud/jenkins/psmdb_operator_gke_version.groovy, cloud/jenkins/psmdb_operator_lke_version.groovy, cloud/jenkins/psmdb_operator_minikube.groovy, cloud/jenkins/pxc-operator-gke-version.yml, cloud/jenkins/pxc-operator-lke-version.yml, cloud/jenkins/pxc-operator-minikube.yml, cloud/jenkins/pxc_operator_aws_openshift-4.groovy, cloud/jenkins/pxc_operator_eks.groovy, cloud/jenkins/pxc_operator_gke_version.groovy, cloud/jenkins/pxc_operator_lke_version.groovy, cloud/jenkins/pxc_operator_minikube.groovy
Add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG to operator pipelines
=> CLOUD-714 - Add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG to operator pipelines

pmm/pmm2-client-autobuild.groovy, pmm/pmm2-prepare-release-candidate.groovy, pmm/pmm2-release.groovy, pmm/pmm2-server-autobuild.groovy, pmm/pmm2-submodules.groovy
=> PMM-10036 migrate build script directory

pt/jenkins/pt-package-testing.groovy
Install python 3.6
Create ansible.cfg file with python 3.6 as interpreter
=> Resolve disable-selinux issue for oracle linux 8

proxysql/build-binary-proxysql
fatal error: 'uuid/uuid.h' file not found
Added library:
For CentOS: libuuid libuuid-devel
For Ubuntu: uuid-dev
=> Proxysql job is failing in compilation phase due to below error

cloud/jenkins/ps_operator_gke_version.groovy
Once this passes review I'll make the same/similar change for the PR job.
TEST JOB: https://cloud.cd.percona.com/job/tomislav-ps-operator-gke-version/
=> K8SPS-123 - Run PS operator tests in parallel

pmm/pmm2-upgrade-tests.groovy, resources/pmm/check_upgrade.py
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests-matrix/detail/pmm2-upgrade-tests-matrix/996/pipeline/44
=> PMM-7 upgrade check verification

ps/jenkins/package-testing-ps-8.0.groovy, ps/jenkins/package-testing-ps-8.0.yml, ps/jenkins/package-testing-ps-build-8.0.groovy, ps/jenkins/package-testing-ps-build-8.0.yml
MYSQL Shell installation parameter for ps80
=> PS-8347 add parameter for mysql shell installation for ps80

pmm/aws-staging-start.groovy
* disable hashicorp, pull from fedora
* tested with https://pmm.cd.percona.com/job/aws-staging-start/55346/console
=> PMM-10582 fix aws-staging-start pipeline

pdps/pdps-multi-parallel.groovy, pdps/pdps-multi.groovy, pdps/pdps-parallel.groovy, pdps/pdps.groovy, pdpxc/pdpxc-multi-parallel.groovy, pdpxc/pdpxc-multi.groovy, pdpxc/pdpxc-parallel.groovy, pdpxc/pdpxc.groovy
MYSQL distribution packages are located in 2 repos: pd[pxc,ps]-8.0 and pd[pxc,ps]-8.0.xx (full version). The tests were extended to check pass MAJOR_REPO variable used to define which repo to use for tests.
Tested on: https://pxc.cd.percona.com/job/pdpxc-multi-parallel-eleonora/ https://ps80.cd.percona.com/job/pdps-multi-parallel-eleonora/
=> Distmysql 213 repo pull

cloud/jenkins/psmdb_operator_aks_latest.groovy, cloud/jenkins/psmdb_operator_aks_version.groovy, cloud/jenkins/psmdb_operator_aws_openshift-4.groovy, cloud/jenkins/psmdb_operator_aws_openshift-latest.groovy, cloud/jenkins/psmdb_operator_eks.groovy, cloud/jenkins/psmdb_operator_gke_latest.groovy, cloud/jenkins/psmdb_operator_gke_version.groovy, cloud/jenkins/psmdb_operator_lke_version.groovy, cloud/jenkins/psmdb_operator_minikube.groovy, cloud/jenkins/pxc_operator_gke_latest.groovy
Depends on: https://github.com/percona/percona-server-mongodb-operator/pull/973
=> K8SPSMDB-203 - Add support for PSMDB operator cluster wide mode

vars/pmmVersion.groovy
=> PMM-7 add a new PMM ami version

pmm/pmm2-upgrade-portal-tests.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-portal-tests-temp/detail/pmm2-upgrade-portal-tests-temp/284/pipeline/76/
=> PMM-7 Fix selecting repo for pmm portal upgrade job

pmm/pmm2-upgrade-tests-matrix.groovy, pmm/pmm2-upgrade-tests.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests-matrix/detail/pmm2-upgrade-tests-matrix/1082/pipeline
=> PMM-7 Fix Upgrade matrix failure

pmm/pmm2-testsuite.groovy
Reverts Percona-Lab/jenkins-pipelines#1753
=> Revert "PMM-7 Fix testsuite"

ps/jenkins/package-testing-ps-8.0.groovy, ps/jenkins/package-testing-ps-8.0.yml, ps/jenkins/package-testing-ps-build-8.0.groovy, ps/jenkins/package-testing-ps-build-8.0.yml
Added Kmip tests and support in PS jenkins pipeline job.
=> PS-8092: Add Kmip tests

ps/jenkins/test-ps-innodb-cluster.groovy, ps/jenkins/test-ps-innodb-cluster.yml
* Fix naming convention for Oracle-8
=> Fix naming convention for Oracle-8

psmdb/jenkins/percona-server-for-mongodb-6.0.groovy
Add path to build to job build imformation.
=> ENG-7 update psmdb-60 job

pmm/pmm2-submodules.groovy
This is to ensure clean exit for the post stage, i.e. prevent errors like the one below:
`
Error when executing always post condition:
11:56:44  groovy.lang.MissingPropertyException: No such property: BATS_TESTS_URL for class: groovy.lang.Binding
`
=> PMM-7 check the validity of envvars

psmdb/jenkins/percona-server-for-mongodb-6.0.groovy, vars/uploadTarballToDownloadsTesting.groovy
1. Use builders with 64GB RAM instead of 32GB
2. Add stage wchi pushes binary tarballs to TESTING download area
=> PSMDB-1150 psmdb60: use docker-64gb builders

IaC/ps57.cd/init.groovy.d/cloud.groovy
- replace docker-32gb instance due to price and interruption rate increase
- fix fips node startup script(remove outdated java-1.8.0-openjdk)
=> ENG-7 ps57 jenkins fixups

IaC/pmm.cd/init.groovy.d/cloud.groovy, pmm/pmm2-ovf-staging-start.groovy, pmm/pmm2-ovf-test.groovy, pmm/pmm2-ovf.groovy, pmm/pmm2-submodules.groovy
- Protect the droplets' and the agents' traffic with a firewall
- A bit of code cleanup, as usual
It was fine in a test run https://pmm.cd.percona.com/job/pmm2-ovf/4035/consoleFull
=> PMM-11025 use firewall on do

pxc/jenkins/pxc-package-testing.yml
Renamed few variables that were pending
=> renaming few variables.

pxc/docker/install-deps
Fix by mistake removed sudo when installing memcached.
=> PXC-3998: fixed centos:7 Docker image generation

pmm/pmm2-release-candidate.groovy
[PMM-11081](https://jira.percona.com/browse/PMM-11081)
=> PMM-11081 launch a staging instance for RC

pbm/jenkins/percona-mongodb-backup.groovy
- add OL9 support
- change Centos8 to OL8
- add path to built packages to description
=> PBM-1013 add OL9 support, minor fixups

pxc/local/build-binary-pxb80, pxc/local/build-binary-pxc57
https://jira.percona.com/browse/PXC-4093
Fixes a minor version computation issue.
=> PXC-4093 ADD DEBIAN-11, ORACLE LINUX-9, UBUNTU-22.04 TO PXC 5.7

pmm/aws-staging-start.groovy
=> Pmm 7 add variables for portal dev

pmm/pmm2-ui-tests-nightly.groovy
This change is required because of UI tests for[ PMM-1328 ](https://github.com/percona/pmm-ui-tests/pull/484)
=> Fix env variables for portal api

orchestrator/jenkins/orchestrator-pipeline.groovy, orchestrator/jenkins/orchestrator.yml, orchestrator/local/run-integration-tests, orchestrator/local/run-system-tests
https://ps80.cd.percona.com/job/mysql-orchestrator-pipeline/
builds 68-71
Stage result reported correctly.
Build result reported correctly.
=> DISTMYSQL-251: better error handling in Orchestrator's jobs

ps-pxc-dist/apt_release.sh
=> PREL-216 Missing source packages on pdps repo

pxb/jenkins/pxb-package-testing-all.groovy, pxb/jenkins/pxb-package-testing.groovy, pxb/jenkins/pxb-package-testing.yml
PR to add OL9 os for PXB package tests.
=> Updates for OL9

pxc/docker/run-build-pxc-parallel-mtr, pxc/docker/run-test-parallel-mtr, pxc/jenkins/param-parallel-mtr.yml, pxc/jenkins/pxc80-pipeline-parallel-mtr.groovy, pxc/jenkins/pxc80-pipeline-parallel-mtr.yml, pxc/local/build-binary-pxc-parallel-mtr, pxc/local/test-binary-pxc-parallel-mtr
This PR introduces parallel execution of build stages and testing stages into PXC.
The main part is groovy script which was implemented from scratch.
docker/local scripts are based on previous (not parallel versions). I introduced changes necessary for parallel execution.
Matrix job: https://pxc.cd.percona.com/job/pxc-8.0-param-parallel-mtr-refactor/
Pipeline job: https://pxc.cd.percona.com/view/8.0%20parallel%20MTR/job/pxc-8.0-pipeline-parallel-mtr-refactor/
Matrix job is 'red' because it had badly configured copyArtifactPermission. It is already fixed, so next runs should be OK. Will trigger them in the meantime.
All paths point to my repository/branch. Once approved I will change them to the Percona-Lab master.
=> Introduced parallel Jenkins pipeline for PXC

cloud/jenkins/psmdb_operator_eks_latest.groovy, cloud/jenkins/psmdb_operator_eks_version.groovy, cloud/jenkins/pxc_operator_eks_latest.groovy, cloud/jenkins/pxc_operator_eks_version.groovy
We are hitting quota limitation in eu-west-3 for IPs.
=> Change region for running EKS clusters

cloud/jenkins/psmdb_operator_aks_latest.groovy, cloud/jenkins/psmdb_operator_aks_version.groovy, cloud/jenkins/psmdb_operator_aws_openshift-4.groovy, cloud/jenkins/psmdb_operator_aws_openshift-latest.groovy, cloud/jenkins/psmdb_operator_eks_latest.groovy, cloud/jenkins/psmdb_operator_eks_version.groovy, cloud/jenkins/psmdb_operator_gke_latest.groovy, cloud/jenkins/psmdb_operator_gke_version.groovy, cloud/jenkins/psmdb_operator_minikube.groovy
Implement dynamic test assignment to clusters for PSMDB operator pipelines.
Depends on this one: https://github.com/percona/percona-server-mongodb-operator/pull/1197
=> K8SPSMDB-877 - Implement dynamic test execution in PSMDB pipelines

cloud/jenkins/pgo_operator_aws_openshift-4.groovy
Thanks to @nmarukovich for the path provided
=> K8SPG-286 Run test in parallel on openshift

pxc/jenkins/pxc80-pipeline-parallel-mtr.groovy
(glibc 2.12 -> glibc 2.17 change)
=> Adjusted PXB 2.4 package name

IaC/pmm.cd/init.groovy.d/cloud.groovy
(https://jira.percona.com/browse/ENG-1182)
Add accurate labels for pmm.cd.percona.com
- min-centos-7-x64
- min-ol-8-x64
- min-ol-9-x64
=> ENG-1182 Add accurate labels for pmm.cd.percona.com

pxc/local/build-binary-pxc-parallel-mtr
https://jira.percona.com/browse/PXC-4186
Additionally enabled MYSQL_MAINTAINER_MODE.
=> PXC-4186: Adjust dev Jenkis scripts to use cmake for Galera building

pxc/jenkins/proxysql-package-testing-all.groovy, pxc/jenkins/proxysql-package-testing-all.yml, pxc/jenkins/proxysql-package-testing.groovy, pxc/jenkins/proxysql-package-testing.yml
Successful job run with changes: https://pxc.cd.percona.com/job/proxysql-package-testing-all/35/
=> Proxysql: skip update for main repo and add description

pmm/pmm2-image-scanning.groovy, pmm/pmm2-release-candidate.groovy, pmm/pmm2-release.groovy
There is no good documentation on how to add json output, but based on what is there:
- https://docs.lacework.com/onboarding/integrate-inline-scanner
- https://docs.lacework.com/onboarding/integrate-the-lacework-inline-scanner-with-ci-pipelines#integrate-with-aws-codebuild
- https://github.com/lacework/lw-scanner-action/blob/c518fa9e4c88161804b2fc401170bed3729b2995/docker-entrypoint.sh#L40
This one could work. I don't know if it will work :) With Jenkins, it looks like we wouldn't know until we land and run :)
=> PMM-7 add json output to image scans for post processing

pmm/aws-staging-start.groovy
- PoC - https://pmm.cd.percona.com/job/VokoTrimTest/11/
- Trim any white space in the CLIENT_VERSION input field
=> ADD Fix for CLIENT_VERSION input field

IaC/rel.cd/init.groovy.d/cloud.groovy
ENG-1184 increase worker root partition space
ENG-1185 rel.cd: add min-amazon-2-x64 worker for ps80 tests
=> Eng 1184 increase worker root partition space

pdps/orchestrator_docker.groovy
Changes for the pakcage-testing PR: https://github.com/Percona-QA/package-testing/pull/426/files
=> DISTMYSQL-278: Docker orchestrator - add PS version for tests with PS

cloud/jenkins/pgo-operator-minikube.yml, cloud/jenkins/pgo_operator_aws_openshift-4.groovy, cloud/jenkins/pgo_operator_aws_openshift-latest.groovy, cloud/jenkins/pgo_operator_eks.groovy, cloud/jenkins/pgo_operator_gke_version.groovy, cloud/jenkins/pgo_operator_minikube.groovy, cloud/jenkins/psmdb_operator_minikube.groovy
Depends on: https://github.com/percona/percona-postgresql-operator/pull/445
Test run: https://cloud.cd.percona.com/view/PG/job/pgo-operator-minikube/
=> K8SPG-302 - Add minikube pipeline for PostgreSQL operator

pmm/pmm2-ami-staging-start.groovy
https://jira.percona.com/browse/PMM-12085
=> PMM 12085 Fix ssh access to AMI images for el7 and el9.

ps/jenkins/percona-server-for-mysql-8.0.groovy
slack notification for the ps80 package testing trigger.
unstash the properties stash.
set REVISION groovy variable.
trigger build of package testing for ps80.
=> PS-8.0 Automate trigger for ps80 package testing job on the rel.cd jenkins from ps80 build job

proxysql/build-binary-proxysql
Reverts Percona-Lab/jenkins-pipelines#2162
=> Revert "Added a softlink to find go binaries"

ppg/component.groovy, ppg/ppg-multi-parallel.groovy
--Added two new components, popool and postgis, to available components list.
--Disabled checks with vanila postgres. Enabled pgpool and postgis components jobs in ppg-multi-parallel.
=> Disable vanila postgres check.

pxc/jenkins/pxc-package-testing-parallel.groovy, pxc/jenkins/pxc-package-testing-parallel.yml, pxc/jenkins/pxc-package-testing.groovy, pxc/jenkins/pxc-package-testing.yml
remove wip from job name
move pxc package testing job from ps80.cd jenkins to pxc.cd jenkins server
=> move pxc package testing job from ps80.cd jenkins to pxc.cd jenkins server

misc/ec2-instance-checks.groovy, misc/ec2-instance-checks.yml
Check the running ec2 instances since past 2 days
=> Add a jenkins job to check for running ec2 instances

pxc/jenkins/pxc-keyring-test-pkgs.groovy
=> modify the ssh key from ssh_key-us-west-2 to ssh_key-us-west-1 for pxc.cd jenkins

pmm/pmm2-submodules.groovy
PMM-12136
I have implemented a default feature build using EL-9 and included a new parameter called BUILD_OS in the pmm2-submodule pipeline.This parameter allows users to build it for EL-7 if needed.  You can find EL-9 based client/server in the following pull request: https://github.com/Percona-Lab/pmm-submodules/pull/3312
=> PMM-12136 Create EL-9 based feature build by default.

pdps/orchestrator_docker.groovy
Tested changes in https://ps80.cd.percona.com/view/PDPS/job/orchestrator_docker/
=> Add trivy analyzer checks for orchestrator test

pmm/pmm2-image-scanning.groovy, pmm/pmm2-release.groovy, pmm/pmm2-server-autobuild-el7.groovy, pmm/pmm2-server-autobuild-el9.groovy
PMM-7 Fix release pipeline for both el7 and el9.
PMM-7 Fix image scanning pipeline.
=> PMM-7 Fix release pipeline el9

pmm/pmm2-ui-tests-matrix.groovy
Making this change, as Github actions cover these tests run's there.
=> Remove tag @pgsm-pmm-integration from Jenkins w/ setup

pmm/pmm2-submodules-rewind.groovy
This should fix the failing pipeline
=> PMM-7 fix the pipeline

pxb/jenkins/pxb-80.groovy
1. Automate PXB80 related VERSION file modification
2. pxb-80 package testing job trigger on the release jenkins for pxb80 build job
=> pxb80 package testing job trigger for pxb80 build job

vars/sync2ProdPMM.groovy
PMM-12367 Fix rsync related errors when running EL7 and EL9 pipelines in parallel.
=> PMM-12367 Fix rsync related errors

psmdb/psmdb-regression.groovy
=> PSMDB disable featureFlagDeprioritizeLowPriorityOperations by default

pxc/docker/install-deps, pxc/jenkins/param-parallel-mtr.yml, pxc/jenkins/param57.yml, pxc/jenkins/pxc57-pipeline.groovy, pxc/jenkins/pxc57-pipeline.yml, pxc/jenkins/pxc80-pipeline-parallel-mtr.groovy, pxc/jenkins/pxc80-pipeline-parallel-mtr.yml
https://jira.percona.com/browse/PXC-4254
=> PXC-4254: Add Debian 12 to supported operating systems (5.7 and 8.0)

pxb/v2/docker/run-test, pxb/v2/jenkins/percona-xtrabackup-8.0-test-cloud-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-test-cloud-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.0.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-compile-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-compile-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.1-compile-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-test-cloud-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.1-test-cloud-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.1-test-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-trunk.yml, pxb/v2/jenkins/percona-xtrabackup-8.1.yml, pxb/v2/local/build-binary, pxb/v2/local/checkout, pxb/v2/local/test-binary
Added support for keyring tests on jenkins
Added support for xbcloud tests via minio
Added 8.1 tests
=> Added 8.1 jobs and KMIP / VAULT / XBCLOUD

cloud/jenkins/psmdb_operator_gke_version.groovy
Add missing options to GKE parametrized job
=> K8SPSMDB-886 - Fix GKE-version cloud pipeline for MCS test

pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-test-param.yml, pxb/v2/jenkins/percona-xtrabackup-8.1-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.1-test-pipeline.yml, pxb/v2/local/test-binary
Enable keyring and xbcloud by default
Fixed missing lib on GR
=> Enable tests by default and install missing lib

pxb/jenkins/pxb-80.groovy
Add conditional block for pushing if there are any git diff (PXB80 VERSION file mod)
=> PXB 80 build git push issue

pxb/v2/local/build-binary
Build team added annobin as part of base image.
=> Revert Temporary Fix for PXB-3192.

ppg/component.groovy, ppg/ppg-12-full-major-upgrade-parallel.groovy, ppg/ppg-12-full-major-upgrade.groovy, ppg/ppg-multi-parallel.groovy, ppg/ppg-multi.groovy, ppg/ppg-parallel.groovy, ppg/ppg-upgrade-parallel.groovy, ppg/ppg-upgrade.groovy, ppg/ppg.groovy
Changed worker for ppg release testing from min-centos-7-x64 to min-ol-8-x64.
=> Changed worker for ppg release testing, min-centos-7-x64 to min-ol-8-x64.

ppg/component.groovy, ppg/docker-parallel.groovy, ppg/docker-parallel.yml, ppg/docker.groovy, ppg/docker.yml
1. ppg/docker for testing a ppg docker container on a single platform.
2. ppg/docker-parallel for testing a ppg docker container on all supported platforms.
=> Added following Jobs for ppg-docker testing:

pmm/pmm2-release.groovy, ps-pxc-dist/sync_repos_prod.sh, vars/sync2PrivateProdAutoBuild.groovy, vars/sync2Prod.groovy, vars/sync2ProdAutoBuild.groovy, vars/sync2ProdDBaas.groovy, vars/sync2ProdPMM.groovy, vars/sync2ProdPMMClient.groovy, vars/sync2ProdPMMClientRepo.groovy, vars/sync2ProdPPG.groovy, vars/syncRepo.groovy
The ip has been changed from 10.10.9.209 to 10.30.9.32
=> ENG-7 change main repo internal ip for pkg uploads

cloud/jenkins/pgo_operator_aws_openshift-4.groovy, cloud/jenkins/pgo_operator_aws_openshift_latest.groovy, cloud/jenkins/pgo_operator_eks_latest.groovy, cloud/jenkins/pgo_operator_eks_version.groovy, cloud/jenkins/pgo_operator_gke_latest.groovy, cloud/jenkins/pgo_operator_gke_version.groovy, cloud/jenkins/pgo_operator_minikube.groovy
`PGO_POSTGRES_HA_IMAGE` was used in `v1` operator and we don't use it any more so better to rename.
=> Update parameters for PGO v2 (rename PGO_POSTGRES_HA_IMAGE)

cloud/jenkins/pgo_v1_operator_aws_openshift-4.groovy, cloud/jenkins/pgo_v1_operator_eks.groovy, cloud/jenkins/pgo_v1_operator_gke_version.groovy
=> K8SPG-471 Add data-migration-gcs test for sandbox

IaC/spot-price-auto-updater.yml
Example: https://ps3.cd.percona.com/view/spot-price-auto-updater/job/spot-price-auto-updater/
Example output:
```shell
17:11:11  [Pipeline] Start of Pipeline
17:11:12  [Pipeline] echo
17:11:12  Availability Zone: eu-west-1b
17:11:12    Availability Zone: eu-west-1b
17:11:12    Instance Type: c5n.2xlarge
17:11:12    Max Bid Price: 0.395099
17:11:12    Current AWS Spot Price: 0.275100
17:11:12    New Max Bid Price: 0.345099
17:11:12    Timestamp: Tue Nov 28 09:16:50 UTC 2023
17:11:12  
17:11:12    Availability Zone: eu-west-1b
17:11:12    Instance Type: i4i.2xlarge
17:11:12    Max Bid Price: 0.871899
17:11:12    Current AWS Spot Price: 0.301900
17:11:12    New Max Bid Price: 0.371899
17:11:12    Timestamp: Tue Nov 28 12:31:38 UTC 2023
17:11:12  
17:11:12    Availability Zone: eu-west-1b …
```
=> ENG-7 Jenkins spot instances price auto updater

IaC/spot-price-auto-updater.yml
1. Fix cloud add/remove in case only 1 cloud configured
2. Set job status and description if prices were changed
=> ENG-7 spot-price-auto-updater: script improvals

ppg/component.groovy, ppg/docker-parallel.groovy, ppg/docker.groovy, ppg/ppg-12-full-major-upgrade-parallel.groovy, ppg/ppg-12-full-major-upgrade.groovy, ppg/ppg-parallel.groovy, ppg/ppg-upgrade-parallel.groovy, ppg/ppg-upgrade.groovy, ppg/ppg.groovy
=> Updated PPG Release Testing pipelines to use installMoleculePPG function to setup Molecule.

pdps/pdps-site-check.groovy, pdps/pdps-site-check.yml, pdpxc/pdpxc-site-check.groovy, pdpxc/pdpxc-site-check.yml, ps/ps-site-check.groovy, ps/ps-site-check.yml, pxb/pxb-site-check.groovy, pxb/pxb-site-check.yml, pxc/pxc-site-check.groovy, pxc/pxc-site-check.yml
Hi. The successfully run jobs with my repo (distros links will be fixed in scope of DISTMYSQL-380 ):
https://ps80.cd.percona.com/job/ps-site-check/
https://ps80.cd.percona.com/job/pdps-site-check/
https://pxc.cd.percona.com/job/pxc-site-check/
https://pxc.cd.percona.com/job/pdpxc-site-check/
https://pxb.cd.percona.com/view/all/job/pxb-site-check/
=> Add PS/PDPS/PXC/PDPXC/PXB tasks to check download links

cloud/jenkins/pgo_operator_aws_openshift-4.groovy, cloud/jenkins/pgo_operator_aws_openshift_latest.groovy, cloud/jenkins/pgo_operator_eks_latest.groovy, cloud/jenkins/pgo_operator_eks_version.groovy, cloud/jenkins/pgo_operator_gke_latest.groovy, cloud/jenkins/pgo_operator_gke_version.groovy
2 retries for failed test is too much, 0 is not enough, 1 is perfect
=> K8SPG-358 - Decrease retryCount for failed PG tests

pxc/docker/install-deps
=> Install OpenSSL 1.1 on centos:7 as it is the dependency

ppg/pg_tarballs.groovy, ppg/pg_tarballs.yml
Jenkins pipeline will automatically get version from stable branches and generates tarballs of all versions in parallel.
=> [DISTPG-664]: Adds Jenkins groovy and yml files to build PG tarballs.

ps/jenkins/package-testing-ps-build-innovation-lts.groovy, ps/jenkins/package-testing-ps-build-innovation-lts.yml, ps/jenkins/package-testing-ps-innovation-lts.groovy, ps/jenkins/package-testing-ps-innovation-lts.yml
use lts_innovation for testing
Add upgrade
Add KMS for testing..
Set Fix ansible version
Check version
replace ps80 with innovation-lts for package testing
=> Adding innovation job

ps/jenkins/package-testing-ps-build-innovation-lts.groovy
=> ps innovation lts package testing job disable ansible debug

ppg/docker-parallel.groovy, ppg/docker.groovy, ppg/pgsm-parallel.groovy, ppg/pgsm-parallel.yml, ppg/pgsm.groovy, ppg/pgsm.yml
1. pgsm.groovy --> support selection of platform and repo for testing.
2. pgsm-parallel.groovy --> support selection of platform and repo for testing.
=> Added two jenkins pipelines for pgsm testing.

IaC/cloud.cd/JenkinsStack.yml, IaC/fb.cd/JenkinsStack.yml, IaC/pg.cd/JenkinsStack.yml, IaC/pmm.cd/JenkinsStack.yml, IaC/ps3.cd/JenkinsStack.yml, IaC/ps57.cd/JenkinsStack.yml, IaC/ps80.cd/JenkinsStack.yml, IaC/psmdb.cd/JenkinsStack.yml, IaC/pxb.cd/terraform/master_user_data.sh, IaC/pxc.cd/JenkinsStack.yml, IaC/rel.cd/JenkinsStack.yml
1. update all jenkins servers to 2.426.3 version
2. add new team member
=> PKG-9 jenkins farm version update to 2.426.3

psmdb/psmdb-regression.groovy
PSMDB added featureFlagQueryStats,featureFlagTransitionToCatalogShard to the default exclude list
=> PSMDB added new excludes for 7.0.7

pxc/local/test-binary-pxc57
https://perconadev.atlassian.net/browse/PXC-4395
Post push fix. Correct a syntax error.
=> PXC-4395 Fix minor jenkins issues

pxc/docker/run-test57, pxc/local/test-binary-pxc57
https://perconadev.atlassian.net/browse/ENG-1235
=> ENG-1235 Adds "--sanitize" to MTR arguments for ASAN runs

pxb/jenkins/pxb-package-testing-all.groovy, pxb/jenkins/pxb-package-testing-all.yml, pxb/jenkins/pxb-package-testing.groovy, pxb/jenkins/pxb-package-testing.yml
PXB innovation lts add ps, ms and all tests support
PXB zip and archive the logs
PXB add kmip, kms support
=> PXB MS package testing innovation lts support addition

proxysql/proxysql.groovy, proxysql/qa-proxysql2-param.yml, proxysql/qa-proxysql2-pipeline.groovy, proxysql/run-build-proxysql, proxysql/test-proxysql
https://perconadev.atlassian.net/browse/RM-1376
***
Updated the defaults placeholders for Jenkins jobs.
***
Modified the scripts to download recent PXC binaries.
***
Fix wget failures on CentOS-8.
=> RM-1376: Jenkins adjustments for ProxySQL-2.6.2

pmm/infrastructure/rpm-build-3.groovy
This PR adds a pipeline for building the `rpmbuild` image specifically for v3.
=> PMM-7 Add rpm-build-3 pipeline for v3

ppg/pg_stat_monitor-autobuild.groovy, ppg/pgpool2-build.groovy
Reverts Percona-Lab/jenkins-pipelines#2614
=> Revert "[PKG-33]: Uses docker label for build instance."

pxc/jenkins/pxc-package-testing-parallel.groovy, pxc/jenkins/pxc-package-testing-parallel.yml, pxc/jenkins/pxc-package-testing.groovy, pxc/jenkins/pxc-package-testing.yml
Add Support for Major and Minor Uprade
Mods for innovation lts for Minor Upgrade support
Add new jenkins node for each parallel test to ensure no env overriding
=> Add PXC 57 EOL support

ppg/component.groovy, ppg/docker-parallel.groovy, ppg/docker.groovy, ppg/pgsm-parallel.groovy, ppg/pgsm.groovy, ppg/ppg-multi-parallel.groovy, ppg/ppg-multi.groovy, ppg/ppg-parallel.groovy, ppg/ppg-upgrade-parallel.groovy, ppg/ppg-upgrade.groovy, ppg/ppg.groovy, ppg/tde-parallel.groovy, ppg/tde.groovy, vars/installMoleculePython39.groovy
Added new function to use python39 in set up that is used for PPG testing. Now using agent min-ol-9-x64.
=> Using agent min-ol-9-x64 & python 3.9 for PPG release testing. 

pmm/infrastructure/rpm-build-3.groovy, pmm/infrastructure/rpm-build.groovy
This PR is fixing a few things in `rpmbuild` pipelines
=> PMM-13137 sha1 deprecation in rpmbuild ol9

pxc/jenkins/pxc-rhel-tarballs-86-89.groovy
=> rhel 86-89 pxc/pxb package tests

pdpxc/pdpxc-parallel.groovy, pdpxc/pdpxc-upgrade-parallel.groovy, pdpxc/pdpxc-upgrade.groovy, pdpxc/pdpxc.groovy, pt/jenkins/pt-package-testing-all.groovy, pt/jenkins/pt-package-testing.groovy
- Updated Percona Toolkit version to 3.6.0
- Added Bookworm and Noble Numbat tests for the Percona Toolkit
=> Bookworm, Noble, v3.6.0 for Percona Toolkit

pxc/docker/install-deps, pxc/jenkins/param-parallel-mtr.yml, pxc/jenkins/pxc80-pipeline-parallel-mtr.groovy, pxc/jenkins/pxc80-pipeline-parallel-mtr.yml
https://perconadev.atlassian.net/browse/PXC-4446
=> PXC-4446: Add ubuntu:noble to dev Jenkins pipelines

pxc/docker/install-deps
1. fixed bracket typos
2. added percona repository for qpress installation
=> PXC-4446: post push fix

pmm/pmm2-ami-staging-start.groovy, pmm/pmm2-ami.groovy, pmm/pmm2-ovf-staging-start.groovy, pmm/pmm2-ovf.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/tbr-pmm2-ami/detail/tbr-pmm2-ami/5/pipeline/
https://pmm.cd.percona.com/blue/organizations/jenkins/tbr-pmm2-ovf/detail/tbr-pmm2-ovf/1/pipeline/
=> PMM-13237 fix pmm2 ami and ovf pipelines

pmm/v3/pmm3-api-tests.groovy
This PR fixes a typo that prevented PMM Server logs from being archived.
=> PMM-7 Fix log archival in API tests

pmm/aws-staging-start.groovy
https://pmm.cd.percona.com/job/aws-staging-start/75260/console
=> Update mysql client binary name

pmm/pmm2-ui-tests-nightly.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/2612/pipeline
=> Update modify pxc runs group include with pdpgsql

pxc/jenkins/param57.yml, pxc/jenkins/pxc57-pipeline.yml, pxc/local/build-binary-pxc57
https://perconadev.atlassian.net/browse/PXC-4474
* Post push fix to preserve the env variable while invoking another bash script.
* Updates the default version of the PXB used to 2.4.29.
=> PXC-4474 Update sudo path

pmm/pmm2-ui-tests-nightly.groovy
https://github.com/percona/pmm-ui-tests/pull/861
=> PMM-13355 Update modify MongoDb runs to use sharding instead of replicaset

cloud/jenkins/pg_containers_docker_build.groovy
* build images only for PGO v2
* change the tag for upgrade image, now it is "main-upgrade"
=> K8SPG-604 fix build job for upgrade image

pmm/pmm2-upgrade-tests.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/334/pipeline
=> PMM-7: Remove percona release

pmm/pmm2-package-testing.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-package-testing-arm/detail/pmm2-package-testing-arm/3239/pipeline/
=> PMM-7 Change agent for package test arm

pmm/pmm2-submodules.groovy, pmm/v3/pmm3-submodules.groovy
Ref: https://github.com/percona/pmm/pull/3184
=> PMM-7 Move build scripts to monorepo

pxc/jenkins/pxc-package-testing-parallel.groovy, pxc/jenkins/pxc-package-testing-parallel.yml, pxc/jenkins/pxc-package-testing.groovy, pxc/jenkins/pxc-package-testing.yml
PXC PT Modifications
Add ARM support
=> PXC PT job mods

pmm/pmm2-ui-tests-nightly.groovy, pmm/v3/pmm3-ovf-staging-start.groovy, pmm/v3/pmm3-ui-tests-nightly.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/476/pipeline/114
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/480/pipeline/107/
=> PMM-13422: Ovf and AMI support in nightly ui tests

proxysql/qa-proxysql2-param.yml, proxysql/qa-proxysql2-pipeline.groovy, proxysql/test-proxysql
https://perconadev.atlassian.net/browse/PSQLADM-534
Job link: https://pxc.cd.percona.com/job/qa-proxysql2-pipeline/build
- Modified the scripts now support testing with PXC-8.4.
=> PSQLADM-534: ProxySQL 2.7.1-1

ppg/component-generic-parallel.groovy, ppg/component-generic.groovy, ppg/component-multi-parallel.groovy, ppg/pdp-installcheck-world-parallel.groovy, ppg/pdp-performance-test.groovy, ppg/pdp-performance-test.yml, vars/ppgOperatingSystemsPerformance.groovy
Adding pgvector to component testing job. Adding new test jobs for pdp-check tests and peformance tests.
=> Adding pgvector to component testing job.

pbm/jenkins/percona-mongodb-backup.groovy
1. add cloud infra selector
2. combine x86_64 and arm64 arch builds
=> PKG-333 psmdb.cd: migrate pbm to hetzner

ppg/psp-installcheck-world-parallel.groovy, ppg/psp-installcheck-world-parallel.yml, ppg/psp-installcheck-world.groovy, ppg/psp-installcheck-world.yml, ppg/psp-performance-test.groovy, ppg/psp-performance-test.yml
Added tests jobs for Percona Server of PostgreSQL-17 to check performance.
=> Added tests jobs for Percona Server of PostgreSQL-17 to check performance.

cloud/jenkins/pg_containers_docker_build.groovy
PG12 reached EOL, so removing from PG operator container build job.
=> K8SPG-721 Remove PG12 from PG operator container build job

vars/uploadRPMfromAWS.groovy
There is an issue with how a shell script is invoked from inside the Groovy script
=> PKG-476 rel.cd: fix uploadRPMfromAWS func

pmm/v3/pmm3-ui-tests.groovy
https://pmm.cd.percona.com/job/pmm3-ui-tests-copy/40/
PR: https://github.com/percona/pmm-ui-tests/pull/932 for ui changes
=> 13783 Updates create n/w and add to pmm-server

pmm/v3/pmm3-package-testing.groovy, pmm/v3/pmm3-package-tests-matrix.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-package-testing-arm-matrix/detail/pmm3-package-testing-arm-matrix/254/pipeline/20/
=> PMM-13803: Package test for pmm matrix

cloud/jenkins/pg_containers_docker_build.groovy
* add build of pgbackrest and pgbouncer images using official Dockerfiles
=> K8SPG-613 add build of pgbackrest and pgbouncer images

pdpxc/pdpxc-pxco-integration-scheduler.groovy, pdpxc/pdpxc-pxco-integration-scheduler.yml, pdpxc/pdpxc-upgrade-parallel.groovy
ready pdpxc upgrade parallel job for pr
=> pdpxc upgrade parallel pxco intergation trigger addition

proxysql/qa-proxysql2-param.yml, proxysql/test-proxysql
https://perconadev.atlassian.net/browse/PSQLADM-555
Replaces the hardcoded values to fetch the PXC packages to run in the jenkins job with a mechanism to always fetch the latest version of the packages available.
=> PSQLADM-555 Fetches the latest versions of PXC packges

proxysql/test-proxysql
https://perconadev.atlassian.net/browse/PSQLADM-555
=> PSQLADM-555 Fixes the URL to fetch PXC packges

.github/CODEOWNERS, pml/pml-functional-tests.groovy, pml/pml-functional-tests.yml
@hors approved removal of ptankov in https://github.com/Percona-Lab/jenkins-pipelines/pull/3270
=> PML. Move functional tests job to Hetzner

orchestrator/jenkins/orchestrator-pipeline.groovy
Post push fix: corrected label for Integration Tests stage.
=> Integrated Orchestrator Jenkins pipeline with Hetzner Docker hosts

ppg/component-generic-parallel.groovy, ppg/component-generic.groovy, ppg/component-multi-parallel.groovy, ppg/component.groovy, ppg/docker-parallel.groovy, ppg/docker.groovy, ppg/pgsm-parallel.groovy, ppg/pgsm.groovy, ppg/ppg-12-full-major-upgrade-parallel.groovy, ppg/ppg-12-full-major-upgrade.groovy, ppg/ppg-parallel.groovy, ppg/ppg-upgrade-parallel.groovy, ppg/ppg-upgrade.groovy, ppg/ppg.groovy, ppg/psp-installcheck-world-parallel.groovy, ppg/psp-installcheck-world.groovy, ppg/psp-performance-test.groovy, ppg/tarball-parallel-ssl1.groovy, ppg/tarball-parallel-ssl3.groovy, ppg/tarball.groovy, ppg/tde-parallel.groovy, ppg/tde.groovy, vars/moleculeExecuteActionWithScenarioPPG.groovy, vars/moleculeExecuteActionWithVariableAndScenarioPPG.groovy, vars/moleculeExecuteActionWithVariableListAndScenarioPPG.groovy, vars/moleculeParallelPostDestroyPPG.groovy, vars/moleculeParallelTestPPG.groovy
- Updated component versions and testing branch in the PPG Testing Jobs.
- Added dedicated molecule execution scenario files in **vars** folder so that the rest of the pillars are not impacted by any change that we do when needed.
=> Pushing changes for Q2-2025 PPG release.

pxb/v2/docker/run-build, pxb/v2/docker/run-test, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy, pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.yml
https://perconadev.atlassian.net/browse/PKG-682
Remove deprecated platforms. Add new LTS platforms. update asan to use centos 8
=> PKG-682 : Update the platforms for PXB jenkins jobs

pmm/v3/pmm3-ui-tests-nightly.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/998/pipeline/
=> PMM-7: Fixes for the nightly job

pxc/jenkins/pxc-binary-tarball-pro.groovy, pxc/jenkins/pxc-binary-tarball-pro.yml
Test job- test-pxc-binary-tarball-pro-molecule
original job- test-pxc-binary-tarball-pro
=> adding scripts for pxc tarball pro job (molecule)

pml/pml-performance.groovy
Updating variables to make the job less confusing for those using it.
=> PML-151 - Changing variables

cloud/jenkins/pgo-doks-1.yml, cloud/jenkins/pgo-doks-2.yml, cloud/jenkins/pgo_doks.groovy
Add Doks pipeline to run tests for PG
=> K8SPG-776: Add doks pipeline for PG

ppg/docker-parallel.groovy, ppg/docker.groovy, vars/ppgOperatingSystemsALL.groovy, vars/ppgOperatingSystemsAMD.groovy, vars/ppgOperatingSystemsARM.groovy, vars/ppgOperatingSystemsPerformance.groovy, vars/ppgOperatingSystemsSSL1.groovy, vars/ppgOperatingSystemsSSL3.groovy
This change is only specific to PPG workflows.
=> Adding platforms for ppg supported platforms for rhel derivatives. This change is only specific to PPG workflows.

percona-release/jenkins/percona-release.groovy, vars/uploadRPMfromAWS.groovy
Update uploadRPMtoAWS to include el10
=> Update hetzner percona-release job

cloud/jenkins/openshift_cluster_create.groovy
**Jira Ticket:** [PKG-1074](https://perconadev.atlassian.net/browse/PKG-1074) - Enhance OpenShift cluster creation build description with comprehensive details
The Jenkins OpenShift cluster creation job provides minimal information in the build description, making it difficult for operators to quickly access cluster details and connection information.
Enhanced the Jenkins build description to provide comprehensive cluster information directly in the Jenkins UI, including clickable URLs, connection commands, and resource details.
**`cloud/jenkins/openshift_cluster_create.groovy`**:
- Replaced simple build description format with comprehensive HTML-formatted information
- Added clickable access URLs for OpenShift console and API
- Included ready-to-use `oc login` commands with password …
=> PKG-1074: Enhance OpenShift cluster creation build description with comprehensive details

pmm/v3/pmm3-package-testing.groovy, pmm/v3/pmm3-package-tests-matrix.groovy, vars/pmmVersion.groovy
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-package-testing-arm/detail/pmm3-package-testing-arm/4878/pipeline
=> PMM-7: Fix package tests nightly run

pxc/jenkins/pxc57-pipeline.groovy
https://perconadev.atlassian.net/browse/PXC-4760
=> PXC-4760 Post push fix for PXC 5.7 Hetzner support

pxc/jenkins/pxc57-pipeline.groovy
https://perconadev.atlassian.net/browse/PXC-4760
=> PXC-4760 Fixes a syntax error in parameters section

IaC/ps80.cd/JenkinsStack.yml, IaC/psmdb.cd/JenkinsStack.yml, IaC/psmdb.cd/init.groovy.d/cloud.groovy
- psmdb.cd: migrate to al2023 + java17
- ps80.cd: CF template fixups
=> PKG-1123 psmdb.cd: migrate to al2023 + java17
