Percona-Lab/jenkins-pipelines

psmdb/percona-server-for-mongodb-master-template.yml

master-template for PSMDB got broken for building mongo tools, this is to make it the same as 3.4 and 3.6 are.
I already made a change in the currently using jobs, but this is to make it correct here also.

Fix percona-server-for-mongodb-master-template.yml

---

psmdb/percona-server-for-mongodb-master-template.yml

It seems from PSMDB 3.7.8 this is needed for building.
Please don't merge it until I make a comment that it's fully tested.

Added libcurl4-openssl-dev to PSMDB build dependencies

---

psmdb/percona-server-for-mongodb-3.2-template.yml
psmdb/percona-server-for-mongodb-3.4-template.yml
psmdb/percona-server-for-mongodb-3.6-template.yml
psmdb/percona-server-for-mongodb-master-template.yml

THP should be disabled when running PSMDB tests so here we disable THP in the job templates.

Disable THP for PSMDB jobs

---

psmdb/percona-server-for-mongodb-4.0-param.yml
psmdb/percona-server-for-mongodb-4.0-template.yml
psmdb/percona-server-for-mongodb-4.0-trunk.yml

What is done here for PSMDB:
- added 4.0 template, param and trunk jobs
- cleanup of master jobs to look same/similar like 4.0 and cleanup of raw xml tags from master jobs
Jobs which are added (source needs to be pushed to psmdb.cd.percona.com):
percona-server-for-mongodb-4.0-template
percona-server-for-mongodb-4.0-param
percona-server-for-mongodb-4.0-trunk
Jobs which are updated  (source needs to be updated in psmdb.cd.percona.com):
percona-server-for-mongodb-master-param
percona-server-for-mongodb-master-template
percona-server-for-mongodb-master

Add PSMDB 4.0 jenkins jobs and cleanup of PSMDB master jobs

---

psmdb/percona-server-for-mongodb-3.4-template.yml
psmdb/percona-server-for-mongodb-3.6-template.yml
psmdb/percona-server-for-mongodb-4.0-template.yml

This fixes building of mongo-tools in PSMDB templates after upstream changes.
Changes are already applied to ps.cd.percona.com

Fix PSMDB templates for building go-tools

---

psmdb/percona-server-for-mongodb-3.2-trunk.yml
psmdb/percona-server-for-mongodb-3.4-trunk.yml
psmdb/percona-server-for-mongodb-3.6-trunk.yml
psmdb/percona-server-for-mongodb-4.0-trunk.yml
psmdb/percona-server-for-mongodb-master.yml

This is to save on disk space.

Reduce the number of builds kept for PSMDB trunk jobs

---

psmdb/percona-server-for-mongodb-3.2-param.yml
psmdb/percona-server-for-mongodb-3.2-trunk.yml
psmdb/percona-server-for-mongodb-3.4-param.yml
psmdb/percona-server-for-mongodb-3.4-trunk.yml
psmdb/percona-server-for-mongodb-3.6-param.yml
psmdb/percona-server-for-mongodb-3.6-trunk.yml
psmdb/percona-server-for-mongodb-4.0-param.yml
psmdb/percona-server-for-mongodb-4.0-trunk.yml
psmdb/percona-server-for-mongodb-master-param.yml
psmdb/percona-server-for-mongodb-master.yml

Minor change for default number of parallel jobs in PSMDB tests so I'll merge myself.

Change default number of parallel jobs for running PSMDB tests

---

cloud/jenkins/psmdb_operator_gke_version.groovy
cloud/jenkins/pxc_operator_gke_version.groovy

* GKE has limit on lenght of cluster name, we need use shorter
names for our clusters

JEN-1115 remove branch name from name of cluster

---

pmm/pmm-ami.groovy
pmm/pmm2-ami.groovy

AMI builds show pass even though, they failed in the build step, it is because of the piping we are using. This should reflect the real status code and also change the build status

PMM-4309 Adding Pipefail to avoid false positives

---

pmm/pmm2-api-tests.groovy

I have made some changes that can help us to get Jenkins Test Report. instead of checking logs all time tests fails. Please, check if it can be merged and integrated. Maybe it needs a few changes, but it seems it should just work. 
Blocked by and related to https://github.com/Percona-Lab/pmm-api-tests/pull/38

Added tests in jUnit format to proper display in Jenkins.

---

pmm/pmm2-api-tests.groovy

We do not currently use them, but they consume resources and cause timing-sensitive update tests to fail.

Do not start extra services for API tests.

---

cloud/jenkins/psmdb_operator_gke_version.groovy

Since GKE has some issues with immediate metrics resource
availability we have to wait.

Backup cluster fix

---

pmm/pmm2-ami.groovy

This will remove the call to UI test job, which is causing the failure and also change the console log to make it easy to find the latest image tag in ci-channel log.

PMM-5067 Change the UI job trigger, change console log

---

pmm/aws-staging-start.groovy

* as I can see we have a lot of ec2 instance interaptions so
we need to change instance type to prevent it

Change AWS instance type from 'm4.large' to 'm5.large'

---

pmm/pmm2-client-autobuild.groovy

Updated pmm-client pipeline to provide packages for Ubuntu 20.04

PMM-5403 PMM2 Ubuntu 20.04

---

cloud/jenkins/pxc_operator_minikube.groovy

Minikube jenkins job is showing this error below (so moving the options should fix it):
```
java.lang.NoSuchMethodError: No such DSL method 'options' found among steps [archive, bat, catchError, checkout, compareVersions, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, ec2, echo, envVarsForTool, error, fileExists, findFiles, getContext, git, input, isUnix, junit, library, libraryResource, load, mail, node, nodesByLabel, parallel, powershell, properties, publishIssues, pwd, pwsh, readCSV, readFile, readJSON, readManifest, readMavenPom, readProperties, readTrusted, readYaml, recordIssues, resolveScm, retry, scanForIssues, script, sh, sha1, slackSend, slackUploadFile, slackUserIdFromEmail, slackUserIdsFromCommitters, sleep, sshagent, stage, stash, step, tee, timeout, tm, tool, …
```

Fix timeout in pxc_operator_minikube.groovy

---

pxc/docker/install-deps

The `shared_ptr.hpp` being missing on system which causes failure on pipeline run for CentOS 8

PXC-3369: Add boost-devel package

---

cloud/jenkins/psmdb_operator_eks.groovy

Failing here: https://cloud.cd.percona.com/job/psmdb-operator-eks/34/execution/node/8/log/
```
+ /usr/local/bin/helm init --client-only
Error: unknown command "init" for "helm"
Did you mean this?
lint
```

Remove helm init from psmdb_operator_eks.groovy

---

cloud/jenkins/psmdb_operator_minikube.groovy
cloud/jenkins/pxc_operator_minikube.groovy

PSMDB and PXC minikube tests fail like so:
https://cloud.cd.percona.com/job/psmdb-operator-minikube/98/consoleFull
```
+ sudo yum install -y percona-xtrabackup-80 jq kubectl socat
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Error making cache directory: /var/cache/yum/x86_64/2/tools-release-noarch error was: [Errno 17] File exists: '/var/cache/yum/x86_64/2/tools-release-noarch'
...
--- 0 stderr
/mnt/jenkins/workspace/psmdb-operator-minikube/source/e2e-tests/init-deploy/../functions: line 607: kubectl: command not found
```
This clears the cache before installing and also fails the job if the yum install fails so that the tests are not even tried to run.

Add clearing yum cache and stop tests if tools install fails on minikube

---

pmm/pmm2-server-autobuild.groovy

Rebased from: https://github.com/Percona-Lab/jenkins-pipelines/pull/525/files

PMM-6621 Remove deprecated packages from autobuild pipeline

---

pxc/docker/run-test
pxc/docker/run-test57
pxc/jenkins/param.yml
pxc/jenkins/param57.yml
pxc/jenkins/pxc57-pipeline.groovy
pxc/jenkins/pxc57-pipeline.yml
pxc/jenkins/pxc80-pipeline.groovy
pxc/jenkins/pxc80-pipeline.yml
pxc/local/test-binary-pxc
pxc/local/test-binary-pxc57

Issue : 
Currently, PXC-57/80 MTR pipeline jobs do not have the option to set custom MTR workers
Solution:
Added the following parameters to set custom MTR workers
PARALLEL_RUN : This value is used for all test suites except for Galera specific suites.
GALERA_PARALLEL_RUN : This value is used for the Galera specific test suites
MTR_SUITES : mysql-test-run.pl suite names
FULL_MTR : Run MTR suites based on variable MTR_SUITES if the value is `no`. Otherwise, the full MTR will be performed.
PXC-5.7 test run result: https://pxc.cd.percona.com/job/test-pxc-5.7-param
PXC-8.0 test run result: https://pxc.cd.percona.com/job/test-pxc-8.0-param
PS : Removed debian jessie from the OS list as it has reached EOL

PXC-3364 : Make MTR workers configurable for param jobs

---

IaC/rel.cd/init.groovy.d/cloud.groovy

I've installed this cloudinit at https://rel.cd.percona.com/computer/ and checked every AMI
Used official IDs from:
* Debian: https://wiki.debian.org/Cloud/AmazonEC2Image
* Ubuntu: https://cloud-images.ubuntu.com/locator/ec2/
* CentOS: https://wiki.centos.org/Cloud/AWS

ENG-920: Add missing AMIs and update existing to latest versions

---

IaC/ps80.cd/init.groovy.d/cloud.groovy

Hrvoje reported that CentOS 8 doesn't have `git` installed:
With `|| : ` it only installs java package
Here's the sample:
```
++ sudo yum -y install java-1.8.0-openjdk git aws-cli
Last metadata expiration check: 0:00:03 ago on Wed 16 Sep 2020 04:44:46 PM UTC.
No match for argument: aws-cli
Error: Unable to find a match: aws-cli
++ :
<<>>
Dependencies resolved.
==========================================================================================
Package                       Arch    Version                            Repo        Size
==========================================================================================
Installing:
java-1.8.0-openjdk            x86_64  1:1.8.0.262.b10-0.el8_2            AppStream  323 k
Installing dependencies:
```

ENG-906: Fix installation of git on CentOS

---

pmm/aws-staging-start.groovy

Caused because:
In previous implementation, `OWNER` variable had `<NAME>.<SURNAME>` from email and it was used in `OWNER` tag of EC2 instance
I've reworked it so that it has `<NAME>` only in `OWNER` variable, and causes lp-percona.script to send a mail to  `<NAME>@percona.com`
Here's a proof https://github.com/Percona-Lab/jenkins-pipelines/commit/677de66aa3c7a644d0c3287ee8cee762000c488b#diff-cf39489e2a5e3b641bec0e09fa1ee7a4f9f4c076eb1b8a7aa517440fb2e22a9cL115

ENG-921: Fix owner tag in EC2 instances

---

pxb/percona-xtrabackup-8.0-template.yml

Builds passed compilation stage: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param/170/
Also, this requires https://github.com/percona/percona-xtrabackup/pull/996 commit e74a942

PXB-2337: Switch ZLIB & ZSTD to bundled

---

pxc/local/test-binary-pxc56

Post-push fix: Revert to old behavior by not running MTR with root user.
Note to Reviewers
---
Many of the testcases were failing because the tests were run with root user.
```
rpl_gtid_mode
2020-11-16 14:00:49 0 [Warning] The syntax '--master-retry-count' is deprecated and will be removed in a future release. Please use 'CHANGE MASTER TO master_retry_count = <num>' instead.
2020-11-16 14:00:49 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2020-11-16 14:00:49 0 [Warning] Insecure configuration for --secure-file-priv: Data directory is accessible through --secure-file-priv. Consider choosing a different directory.
2020-11-16 14:00:49 0 [Warning] Insecure configuration for …
```

PXC-3472: Updated MTR output process function

---

cloud/jenkins/pxc_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift.groovy
cloud/jenkins/pxc_operator_eks.groovy
cloud/jenkins/pxc_operator_gke_version.groovy
cloud/jenkins/pxc_operator_lke_version.groovy

This is same change that was done here for PR tests:
https://github.com/percona/percona-xtradb-cluster-operator/pull/676
Adding 90min timeout to the command which actually runs the test and recreating the cluster for upgrade tests.

Fix test timeout and upgrade test cleanup for PXC operator jobs

---

pmm/pmm2-api-tests.groovy

This is to avoid test failures, we will enable it once we have DbaaS setup for testing against

Disable DBAAS on PMM-Server for API tests

---

pxb/docker/test-binary-pxb24
pxb/docker/test-binary-pxb80

Required because: https://pxb.cd.percona.com/view/PXB%208.0/job/pxb80-single-platform-run/7/console
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.6.1-0.1ubuntu2.4_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 11.0 MB in 2s (3994 kB/s)
```

PXB-2365: Refresh apt cache before installing anything for PXB 

---

IaC/cloud.cd/JenkinsStack.yml
IaC/fb.cd/JenkinsStack.yml
IaC/pg.cd/JenkinsStack.yml
IaC/ps.cd/JenkinsStack.yml_ps3
IaC/ps56.cd/JenkinsStack.yml
IaC/ps57.cd/JenkinsStack.yml
IaC/ps80.cd/JenkinsStack.yml
IaC/psmdb.cd/JenkinsStack.yml
IaC/pt.cd/JenkinsStack.yml
IaC/pxb.cd/terraform/master_user_data.sh
IaC/pxc.cd/JenkinsStack.yml
IaC/rel.cd/JenkinsStack.yml

As discussed on DS, we'll going to exclude Java from autoupdates and updating Java version stacks to latest

ENG-935: Update IaC Jenkins Java version to latest and exclude Java from cron updates

---

cloud/jenkins/psmdb_operator_aws_openshift-4.groovy
cloud/jenkins/psmdb_operator_aws_openshift.groovy
cloud/jenkins/psmdb_operator_eks.groovy
cloud/jenkins/psmdb_operator_gke_version.groovy
cloud/jenkins/psmdb_operator_lke_version.groovy
cloud/jenkins/pxc_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift.groovy
cloud/jenkins/pxc_operator_eks.groovy
cloud/jenkins/pxc_operator_gke_version.groovy
cloud/jenkins/pxc_operator_lke_version.groovy

We don't support PMM 1.x any more and this test sometimes gets stuck so this will speed up release testing.

Remove monitoring test in cloud tests for PSMDBO

---

pxc/local/build-binary-pxc

Build: https://pxc.cd.percona.com/job/pxc-8.0-pipeline-pxc-3520/1/
It passed the compilation stage with following parameter
I discussed the failure of tests with Kamil and we agreed to open a PR as the main issue was fixed

PXC-3520: Switch -DWITH_ZLIB to bundled

---

IaC/rel.cd/init.groovy.d/cloud.groovy

It's only needed for xenial-x32 AMI, but I think it won't create any downsides for other OS which uses this `initMap`
Tested on REL.cd

ENG-933: Loop the installation of dependencies on REL.cd apt workers

---

IaC/rel.cd/init.groovy.d/matrix.groovy

This script has syntax checker which is awesome feature for our Jenkinses, it won't overwrite configuration if mistake was made:
```
2020-09-22 07:35:35.877+0000 [id=28]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /mnt/rel.cd.percona.com/init.groovy.d/matrix.groovy
Configuring authorization strategy GlobalMatrixAuthorizationStrategy
For user sudokamikaze grant permission Overall Administer.
For user percona*Build Engineers grant permission Overall Administer.
2020-09-22 07:35:36.283+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
```
And when failed:
```
2020-09-22 07:30:43.092+0000 [id=30]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /mnt/rel.cd.percona.com/init.groovy.d/matrix.groovy
Skip configuring matrix authorization strategy …
```

ENG-921: Implement matrix auth as IaaC for rel.cd

---

IaC/cloud.cd/JenkinsStack.yml
IaC/fb.cd/JenkinsStack.yml
IaC/pg.cd/JenkinsStack.yml
IaC/ps.cd/JenkinsStack.yml_ps3
IaC/ps56.cd/JenkinsStack.yml
IaC/ps57.cd/JenkinsStack.yml
IaC/ps80.cd/JenkinsStack.yml
IaC/psmdb.cd/JenkinsStack.yml
IaC/pt.cd/JenkinsStack.yml
IaC/pxb.cd/terraform/master_user_data.sh
IaC/pxc.cd/JenkinsStack.yml
IaC/rel.cd/JenkinsStack.yml

We've discussed this approach in release-team, which is most appropriate to save logs with reason to investigate after shutdown of instance

ENG-939: Copy last log before termination of Jenkins master instance

---

pmm/aws-staging-start.groovy

`t2.large` is having > 20% frequency of interruption, while `t2.large` is < 5%.  All other resource params (memory, CPU) are the same.
So we'll monitor this one to see if it reduces the hassle.

PMM-7277 change instance type

---

pxb/percona-xtrabackup-2.4-param.yml
pxb/percona-xtrabackup-2.4-template.yml
pxb/percona-xtrabackup-8.0-param.yml
pxb/percona-xtrabackup-8.0-template.yml

Builds: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param/128/
https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param/235/
Please ignore failed builds, they failed in "test stage" and they are out-of-scope of this ticket(my opinion)

PXB-2327: Add xenial-32 to PXB 2.4 & 8.0 pipelines

---

IaC/cloud.cd/JenkinsStack.yml
IaC/fb.cd/JenkinsStack.yml
IaC/pg.cd/JenkinsStack.yml
IaC/ps.cd/JenkinsStack.yml_ps3
IaC/ps56.cd/JenkinsStack.yml
IaC/ps57.cd/JenkinsStack.yml
IaC/ps80.cd/JenkinsStack.yml
IaC/psmdb.cd/JenkinsStack.yml
IaC/pt.cd/JenkinsStack.yml
IaC/pxb.cd/terraform/master_user_data.sh
IaC/pxc.cd/JenkinsStack.yml
IaC/rel.cd/JenkinsStack.yml

Deployed on rel:
```
/etc/letsencrypt/live/rel.cd.percona.com/fullchain.pem
Your key file has been saved at:
/etc/letsencrypt/live/rel.cd.percona.com/privkey.pem
Your cert will expire on 2021-04-13. To obtain a new or tweaked version of this certificate in the future, simply run certbot again. To non-interactively renew *all* of your certificates, run "certbot renew"
2021-01-13 15:57:26,586:DEBUG:certbot._internal.reporter:Reporting to user: If you like Certbot, please consider supporting our work by:
```

ENG-966: Rework certbot-auto to certbot for Jenkins

---

pmm/pmm-documentation.groovy

New approach to publishing PMM docs.
Assumes completely built HTML is in publish branch.
Copies all to target web host as-is (no Docker or static website build steps).
Testing at https://pmm.cd.percona.com/job/pmm-documentation/

New for PMM (all) - copy HTML from publish branch

---

IaC/ps57.cd/init.groovy.d/cloud.groovy

Docker executor was failing due to 5-10% interruption rate
Also, this commit includes yesterday's change of M4Large to M5Large due to interruption rate, is used for micro-amazon executor

Correct spot instances configuration for ps57

---

IaC/pxc.cd/init.groovy.d/cloud.groovy

This needed because we don't want to use EOL repositories not intended for any OS except CentOS 6 for ramdisk- workers

PS-7515: Fix PXC's cloud.groovy IaC config

---

pxb/percona-xtrabackup-2.4-template.yml
pxb/percona-xtrabackup-8.0-template.yml

Builds: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/23/
Note, centos 8 failed due to https://github.com/percona/percona-server/commit/933b7d8e42381813be3184a76b4308b50aaa7b1e#diff-ceb99f02755875cbbc03fa36029ddc2cad5ae877881f18eced5a9f7dc79ba028 which is not in release yet

PXB-2411: Execute lsb_release only on apt systems for PXB 2.4 and 8.0

---

pxc/docker/install-deps

This image used for PXC and PXB pipelines which still support CentOS 6.
```
Step 5/5 : USER mysql
---> Running in 8adffbd68e0a
Removing intermediate container 8adffbd68e0a
---> 6047aa5a382e
Successfully built 2513e168ae73
Successfully tagged perconalab/pxc-build:centos-6
+ rm ./Dockerfile-centos-6
```

PS-7515: Use Percona CentOS 6 mirror for PXC CentOS 6 image

---

pxc/docker/install-deps

Fixes backported from ps-build:
* Add CURL for percona-release
* Fix CentOS 8 PowerTools to powertools transition

PS-7515: Fix PXC's docker image

---

pmm/pmm2-testsuite.groovy

The script fails to install nvm because when it already exists (ex: https://pmm.cd.percona.com/job/pmm2-testsuite/4912/console), so we need to perform a check to see if nvm is present.
NodeJS upgraded to latest LTS v12.20.1.

Fix: check if nvm exists, upgrade node to v12.20.1

---

pmm/kubernetes-cluster-staging.groovy

To use a fixed version of minikube until we know the latest one works as expected, to avoid errors like the one we get for config generation. 
Tested here: https://pmm.cd.percona.com/view/all/job/kubernetes-cluster-staging-tests/7/console
Please see https://jira.percona.com/browse/PMM-7404 understand the reason to do this.

Fix Config generation issue with latest minikube version

---

IaC/ps56.cd/JenkinsStack.yml
IaC/psmdb.cd/JenkinsStack.yml

Deployed on ps56 and psmdb
Includes SSL_BACKUP feature
```
systemctl enable jenkins
systemctl start jenkins
```
Is required for proper functioning, as it redirects to chkconfig -- it wont work with `systemctl enable --now` (tested)
`systemctl restart <webserver>` instead of reload was requested from Mykola side

ENG-970: Update ps56/psmdb Jenkins to 2.263.3

---

IaC/fb.cd/init.groovy.d/cloud.groovy

This is required to run fb pipelines

PS-7534: Increase docker-32gb docker2 disk sizes to fit MTR run

---

IaC/cloud.cd/init.groovy.d/matrix.groovy

Corrected typo for proper permissions on cloud

ENG-977: Correct typo in matrix.groovy for cloud.cd

---

cloud/jenkins/psmdb_operator_minikube.groovy

This test cannot work because of antiAffinity on minikube.

Remove rs-shard-migration test for PSMDBO minikube

---

pmm/pmm-server-release.groovy
pmm/pmm2-server-release.groovy

- PMM2 server and client docker images get the tag `:latest` by default
- stop tagging PMM1 server and docker images with `:latest` 
DO NOT MERGE! Hold off until the release of v2.15

PMM-4679 tag pmm2 as latest, remove latest for pmm1

---

pxc/jenkins/pxc80-pipeline.groovy
pxc/jenkins/pxc80-pipeline.yml
pxc/local/checkout

Builds: https://pxc.cd.percona.com/job/pxc-8.0-pipeline-pxc-3558/2/
(Please ignore failed tests, I've disabled them for this run, pay attention to tag which was used for PXB80 and how it was overwritten)

PXC-3558: Add ability to checkout latest PXB80 without specifying

---

pxb/v2/jenkins/percona-xtrabackup-2.4-trunk.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-trunk.yml

It's needed to achieve `Run once a week` option for trunk

PXB-2329: Add missing triggers

---

pmm/pmm2-testsuite.groovy

A test execution was done here: https://pmm.cd.percona.com/view/all/job/pmm2-testsuite-temp/

Add option for PMM_VERSION from submodules

---

IaC/cloud.cd/init.groovy.d/cloud.groovy
IaC/fb.cd/init.groovy.d/cloud.groovy
IaC/ps.cd/init.groovy.d/cloud-ps3.groovy
IaC/ps56.cd/init.groovy.d/cloud.groovy
IaC/ps57.cd/init.groovy.d/cloud.groovy
IaC/ps80.cd/init.groovy.d/cloud.groovy
IaC/pxb.cd/init.groovy.d/cloud.groovy
IaC/pxc.cd/init.groovy.d/cloud.groovy
IaC/rel.cd/init.groovy.d/cloud.groovy

```
2021-03-04 12:02:53.124+0000 [id=31]	WARNING	j.util.groovy.GroovyHookScript#execute: Failed to run script file:/mnt/pxb.cd.percona.com/init.groovy.d/cloud.groovy
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/mnt/pxb.cd.percona.com/init.groovy.d/cloud.groovy: 82: unexpected char: '\' @ line 82, column 61.
-name "*aws*" -exec rm -rf {} \;
^
```
On manual deploy it works, but from config side after reboot it can't load it, appeared on rel and pxb

ENG-981: Correct Jenkins warnings on cloud init

---

IaC/cloud.cd/JenkinsStack.yml
IaC/fb.cd/JenkinsStack.yml
IaC/pg.cd/JenkinsStack.yml
IaC/pmm.cd/JenkinsStack.yml
IaC/ps.cd/JenkinsStack.yml_ps3
IaC/ps56.cd/JenkinsStack.yml
IaC/ps57.cd/JenkinsStack.yml
IaC/ps80.cd/JenkinsStack.yml
IaC/pxc.cd/JenkinsStack.yml
IaC/rel.cd/JenkinsStack.yml

Removed in Jenkins which are using Github OAuth and implemented a fix for Jenkins which use Google OAuth

ENG-983: Add needed Lua module for GSuite OAuth and clean up

---

cloud/jenkins/pxc_operator_gke_version.groovy

GKE_VERSION is not specified to gcloud command so it starts 1.19 instead of 1.20 for alpha clusters:
```
+ gcloud alpha container clusters create --release-channel rapid jenkins-pxc-ac9c7f9d-basic --zone us-central1-a --project **** --preemptible --machine-type n1-standard-4 --num-nodes=4 --enable-autoscaling --min-nodes=4 --max-nodes=6 --network=jenkins-vpc --subnetwork=jenkins-basic
WARNING: Starting with version 1.19, newly created clusters and node-pools will have COS_CONTAINERD as the default node image when no image type is specified.
...
NAME                        LOCATION       MASTER_VERSION   MASTER_IP      MACHINE_TYPE   NODE_VERSION     NUM_NODES  STATUS
jenkins-pxc-ac9c7f9d-basic  us-central1-a  1.19.7-gke.2503  35.202.93.234  n1-standard-4  1.19.7-gke.2503  4 …
```

Cloud - add GKE version parameter for alpha clusters

---

IaC/LambdaVolumeCleanup.yml

Deployed: https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/LambdaVolumeCleanup?tab=code
Tested (results in slack), all resources without tags do not support tagging
```
$ aws ec2 describe-volumes --filters="Name=status,Values=available" --output=text --region=eu-west-1
VOLUMES eu-west-1a      2021-03-09T17:19:51.187000+00:00        False   100     False   1               available       vol-06de1db669bd29beb   gp2
TAGS    Name    Illia-test
sudokamikaze at Sudokamikazes-Work-MacBook-Pro in ~
$ aws lambda invoke --function-name=CleanVolumesLambda --region=us-east-1 awoo
{
"StatusCode": 200,
"ExecutedVersion": "$LATEST"
}
sudokamikaze at Sudokamikazes-Work-MacBook-Pro in ~
$ cat awoo
null%
sudokamikaze at Sudokamikazes-Work-MacBook-Pro in ~
$ aws ec2 describe-volumes …
```

ENG-984: Create Lambda for cleaning unusued volumes

---

IaC/psmdb.cd/JenkinsStack.yml
IaC/psmdb.cd/init.groovy.d/cloud.groovy

Deployed with plugins and workers update
URLS:
https://psmdb.cd.percona.com/job/percona-server-for-mongodb-3.6-trunk/74/
https://psmdb.cd.percona.com/job/percona-server-for-mongodb-4.0-trunk/88/
https://psmdb.cd.percona.com/job/percona-server-for-mongodb-4.2-trunk/62/

ENG-989: Update psmdb.cd to 2.277.1

---

cloud/jenkins/psmdb_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift-4.groovy

Our current OpenShift4 tests use the latest stable OpenShift version which is now 4.7 and it is based on kubernetes 1.20. Officially we support OpenShift 4.6 (which is based on kubernetes 1.19) so we need to be able to specify version used.

Manually set OpenShift4 version used in cloud tests

---

pmm/pmm2-client-autobuild.groovy
pmm/pmm2-server-autobuild.groovy

WIP, please don't merge. 
Update pmm-client docker tags accordingly for RC. 
1) Adds a default RC tag to always get the latest RC candidate -> ex. 2.16.0-rc
2) Uses Experimental Repo to push RC pmm2-client packages -> Don't need to use laboratory 
Changes both pmm-server and pmm-client auto-build job for the release branch.

PMM-6014 Push RC to experimental repo for pmm2-client packages

---

IaC/pmm.cd/init.groovy.d/cloud.groovy

I discussed the PR https://github.com/Percona-Lab/jenkins-pipelines/pull/897 with Puneet regarding installing docker each time and advised to use docker worker, which is designed for such load
But I noticed, that he was using large-amazon, which has t3.xlarge type, and changing to `docker` (which at this moment has t3.large type) will have an performance impact

Change PMM.cd's docker worker to t3.xlarge

---

pxb/percona-xtrabackup-8.0-template.yml

Build URL: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/BUILD_TYPE=debug,Host=min-centos-8-x64,xtrabackuptarget=innodb80/60/console
```
version_check                            w2	[passed]    25
```
Failed before: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/56/BUILD_TYPE=release,Host=min-centos-8-x64,xtrabackuptarget=innodb80/testReport/(root)/t_version_check/sh/

PXB-2469: Add Perl-DBD-MySQL for CentOS 8 on PXB8.0 template job

---

IaC/pmm.cd/init.groovy.d/cloud.groovy

package-testing job uses `/` (root) volume a lot, and usual PMM jobs use `/` volume instead of `/mnt/`

ENG-1006: Correct PMM's runners for package-testing

---

pmm/pmm-documentation.groovy

Changes mainly to eliminate doubt as to why website not being immediately refreshed after rsync.
Changed:
- Remove chmods (I guess not needed as this is just a simple copy of checked out git branch)
- Delete dir before unstashing: Stash was including this repo's files and other miscellaneous rubbish
- ls to see what's actually unstashed
- Stash of specific dirs/files (limits flexibility but will do until this job can be recreated in GHA)
- Change copied path (so rsync deletes EVERYTHING, not just what we copy) - Discovered after looking at web server folder and discovering historical remnants of other rsync's

Stash specifics; delete before unstashing

---

cloud/jenkins/psmdb_operator_gke_version.groovy

PSMDB GKE alpha cluster is not created with desired version.
Comment out default-cr test since it just fails because it's not implemented yet.

Add GKE_VERSION for PSMDB GKE alpha cluster and comment default-cr test

---

pxb/v2/local/build-binary
pxc/local/build-binary-pxc57

This feature implemented in: https://github.com/Percona-Lab/ps-build/blob/8.0/local/build-binary#L54
I haven't implemented this feature for pxc56/57 as it uses build-binary script from PXC repo

ENG-1010: Backport automatic download of boost from ps-build to PXC/PXB pipelines

---

pmm/pmm2-prepare-release-candidate.groovy

Needs to be added by the user while triggering the job.

Default Release version should be empty

---

pxc/docker/install-deps

Builds: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-compile-pipeline-illiatests/
Failed builds: https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-compile-pipeline/419/parameters/

PXB-2509: Correct sphinx errors on PXB build for Debian based OS

---

pxc/local/test-binary-pxc
pxc/local/test-binary-pxc56
pxc/local/test-binary-pxc57

Builds: https://pxc.cd.percona.com/job/pxc-5.7-pipeline-PXC-3662/8/

PXC-3662: Convert non-UTF-8 chars into browser readable UTF-8

---

ps/jenkins/package-testing-ps-5.7.groovy
ps/jenkins/package-testing-ps-5.7.yml
ps/jenkins/package-testing-ps-8.0.groovy
ps/jenkins/package-testing-ps-8.0.yml
ps/jenkins/package-testing-ps-build-5.7.groovy
ps/jenkins/package-testing-ps-build-5.7.yml
ps/jenkins/package-testing-ps-build-8.0.groovy
ps/jenkins/package-testing-ps-build-8.0.yml

This PR adds Jenkins jobs, destined for the `ps80.cd` and `ps57.cd` instances, that run the package-testing PS playbooks, much like how the `package-testing-ps` job in the old Jenkins does it, although it uses the pipeline syntax to do so instead of the matrix configuration plugin.
I have tried to follow [the instructions in Confluence](https://confluence.percona.com/pages/viewpage.action?pageId=60783651) to the best of my ability. A few questions remain:
- I have placed the `.yml` and `.groovy` files under `ps/jenkins`, where there seem to be similar jobs that exist in the same instances. Is this the right place?
- After this PR is merged, I will run `jenkins-jobs` as described in the Confluence instructions to create the jobs in the instances. How do I make them end up in the right …

PS-7730: Add package-testing-ps* jobs

---

pxb/percona-xtrabackup-8.0-template.yml

Builds: https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/80/

PXB-2524: Correct cmake_bin variable for CentOS 8

---

cloud/jenkins/psmdb_operator_eks.groovy
cloud/jenkins/pxc_operator_eks.groovy

Adds parameter for EKS Kubernetes version for PSMDB/PXC operator tests.
Current latest is `1.20`, but the default is `1.19` and the previous jenkins job was running on current default.

K8SPSMDB-488 - Add parameter for EKS kubernetes version for PSMDB/PXC

---

pxc/docker/install-deps

Builds: https://pxc.cd.percona.com/job/pxc-5.7-pipeline-PXC-3683/6/
This needed, because we install python-mysqldb module via pip3, and it's not available for python2 on focal

PXC-3683: Set python3 for focal by default

---

cloud/jenkins/psmdb_operator_minikube.groovy

It doesn't work because of load balancer support.

CLOUD-628 - Remove service-per-pod test in psmdb_operator_minikube.groovy

---

pmm/pmm2-server-autobuild.groovy

This reverts commit 2f41fc3ca24d2bc862ee298e378dfca4a671b53c.

Revert "PMM-8266 remove prometheus from autobuild"

---

cloud/jenkins/pgo_operator_gke_latest.groovy
cloud/jenkins/pgo_operator_gke_version.groovy
cloud/jenkins/psmdb_operator_gke_latest.groovy
cloud/jenkins/psmdb_operator_gke_version.groovy
cloud/jenkins/pxc_operator_gke_latest.groovy
cloud/jenkins/pxc_operator_gke_version.groovy

There can be a collision if running multiple jobs on the same commit when naming the clusters.
So this will keep the PR jobs running without any addition in the name, latest jobs running on schedule with `latest` and parametrized jobs with `param` addition in the name.

Rename GKE clusters in cloud jobs

---

pmm/pmm-ami.groovy
pmm/pmm-ovf.groovy
pmm/pmm2-ami.groovy
pmm/pmm2-ovf.groovy
pmm/pmm2-prepare-release-candidate.groovy

https://github.com/Percona-Lab/pmm-submodules/pull/1892
We have three changes here:
1. We moved the content of percona-images to pmm-server.
2. We use pmm-2.x.y release branch format for ALL repos.
3. I changed the name of GIT_BRANCH to SUBMODULES_GIT_BRANCHES because Jenkins already has GIT_BRANCH variable. I only change it in pmm2-prepare-release-candidate.groovy because we already have an issue with it but I think we'll change it in all pipelines.

PMM-8364 merge pmm-server and percona images content

---

pmm/pmm2-testsuite.groovy

We are running out of space due to some new tests that have been added, we have added docker-cleanup too, https://pmm.cd.percona.com/job/pmm2-testsuite/6964/consoleFull

Change worker from micro to large for pmm-testsuite

---

pxc/local/build-binary-pxc

https://jira.percona.com/browse/PXC-3698
1. Try to get actual Galera repo commit hash
2. If not possible fallback to '0000000' value
@dutow @Sudokamikaze @vorsel , I'm adding all of you guys as the reviewers, because this change needs touching 3 pieces (there will be 3 PRs):
1. Dev Jenkins build script
2. pxc_builder.sh and build-binary.sh scripts used by release/packaging Jenkins pipeline
3. Galera repository

PXC-3698: Error log indicates wrong Galera build commit hash

---

pxc/docker/install-deps

https://jira.percona.com/browse/PXC-3726
Added stunnel dependency for PXC.
Note: This commit also removes the duplicted dependency of `socat`.

PXC-3726 - Add stunnel dependency to PXC Jenkins

---

ps/jenkins/package-testing-ps-5.7.groovy
ps/jenkins/package-testing-ps-5.7.yml
ps/jenkins/package-testing-ps-8.0.groovy
ps/jenkins/package-testing-ps-8.0.yml
ps/jenkins/package-testing-ps-build-5.7.groovy
ps/jenkins/package-testing-ps-build-5.7.yml
ps/jenkins/package-testing-ps-build-8.0.groovy
ps/jenkins/package-testing-ps-build-8.0.yml

This PR adds support for Debian 11 "Bullseye" to the PS 8.0 and PS 5.7 package testing Jenkins jobs.

PS-7851: Add Debian Bullseye support to PS package testing

---

ps/jenkins/package-testing-ps-build-5.7.groovy

This PR is a fixup for #1146: there will never be a 5.6 build for Bullseye, so tests running on Bullseye should not attempt to test upgrading from 5.6.

PS-7851: Exclude Bullseye from tests using PS 5.6

---

ps/jenkins/test-ps-innodb-cluster.groovy
ps/jenkins/test-ps-innodb-cluster.yml

This PR moves the existing [`test-ps-innodb-cluster` job from the old Jenkins](https://jenkins.percona.com/job/test-ps-innodb-cluster/) to the ps80 Jenkins instance.
The corresponding PR for the code changes is at Percona-QA/package-testing#88; lots of additional detail there.
You can see the job running at https://ps80.cd.percona.com/job/wip-test-ps-innodb-cluster/, against the `wip-test-ps-innodb-cluster` branches.

PS-7828: Add job to test PS InnoDB Cluster with EC2 instances

---

pmm/pmm2-testsuite.groovy

Fixes the issue with new changes for ecr docker tag
```
java.lang.NoSuchMethodError: No such DSL method 'installAWSv2' found among steps
```

Fix failing pmm2-testsuite

---

pxc/docker/run-build-pxc
pxc/docker/run-build-pxc56
pxc/docker/run-build-pxc57
pxc/jenkins/param.yml
pxc/jenkins/param56.yml
pxc/jenkins/param57.yml
pxc/jenkins/pxc56-pipeline.groovy
pxc/jenkins/pxc57-pipeline.groovy
pxc/jenkins/pxc57-pipeline.yml
pxc/jenkins/pxc80-pipeline.groovy
pxc/jenkins/pxc80-pipeline.yml
pxc/local/build-binary-pxc
pxc/local/build-binary-pxc56
pxc/local/build-binary-pxc57

This PR adds ASAN support to the PXC build param/pipeline jobs.
Test builds can be found at wip-noemi-pxc-{[8.0](https://pxc.cd.percona.com/job/wip-noemi-pxc-8.0-pipeline/),[5.7](https://pxc.cd.percona.com/job/wip-noemi-pxc-5.7-pipeline/),[5.6](https://pxc.cd.percona.com/job/wip-noemi-pxc-5.6-pipeline/)}-pipeline and wip-noemi-pxc-{[8.0](https://pxc.cd.percona.com/job/wip-noemi-pxc-8.0-param/),[5.7](https://pxc.cd.percona.com/job/wip-noemi-pxc-5.7-param/),[5.6](https://pxc.cd.percona.com/job/wip-noemi-pxc-5.6-param/)}-param.

PXC-3633: Add ASAN support to PXC builds

---

pxc/jenkins/param.yml
pxc/jenkins/param57.yml

This PR adds a weekly schedule trigger to the PXC build jobs for 8.0 and 5.7. 
Verified that the change is correctly added to the configuration on https://pxc.cd.percona.com/job/wip-noemi-pxc-8.0-param/ and https://pxc.cd.percona.com/job/wip-noemi-pxc-5.7-param/.
It should be possible to merge this PR and #1160 in any order, since their changes don't overlap, but if there's any issues let me know and I'll rebase.

PXC-3632: Run PXC param job weekly for 8.0 and 5.7

---

IaC/pxb.cd/init.groovy.d/cloud.groovy

This PR bumps up the maximum amount of `docker-32gb` instances allowed simultaneously in the `pxb.cd` instance. I changed the value from 10 to 40, as it is set to 40 on `pxc.cd`.
When running the `percona-xtrabackup-8.0-multijob` Jenkins job, @altmannmarcelo noticed timeouts in some of the builds. It seems like the `percona-xtrabackup-8.0-test-param` job attempts to launch 32 jobs in parallel, and it will be 36 once Debian 11 support is added. Since the cap is currently set to 10 and the builds take several hours to complete, some of the builds time out before they can have a node assigned to them.

Bump up PXB `docker-32gb` max instances cap

---

pxb/v2/jenkins/percona-xtrabackup-8.0-compile-pipeline.groovy
pxb/v2/jenkins/percona-xtrabackup-8.0-compile-pipeline.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy

This PR removes the `ubuntu:xenial` option from the Jenkins jobs belonging to the PXB build and test pipeline in the `pxb.cd` instance.

PXB-2568: Remove `ubuntu:xenial` DOCKER_OS option from PXB pipeline jobs

---

cloud/jenkins/pgo_operator_gke_latest.groovy
cloud/jenkins/pgo_operator_gke_version.groovy
cloud/jenkins/psmdb_operator_gke_latest.groovy
cloud/jenkins/psmdb_operator_gke_version.groovy
cloud/jenkins/pxc_operator_gke_latest.groovy
cloud/jenkins/pxc_operator_gke_version.groovy

In some cases limit of 40 characters was reached so the error was thrown when creating clusters.

Shorten cluster names for cloud clusters to avoid reaching limit

---

pmm/pmm2-ami-upgrade-tests.groovy
pmm/pmm2-upgrade-tests.groovy

Due to conflict with docker executions for several DB's on the same port, the problem is yet to be identified but this is a workaround fix to create remote and actual db's on separate instances. 
changes tested here: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ami-upgrade-tests-temp/detail/pmm2-ami-upgrade-tests-temp/1/pipeline

PMM-8625 reorganize client instance for AMI upgrade job

---

psmdb/psmdb-regression.groovy
psmdb/psmdb-regression.yml

Refactored regression tests for psmdb
For testing purpose we are using docker images which are stored in ECR here - https://gallery.ecr.aws/e7j3v3n0/psmdb-build
Images could be prebuilt or could be built during job run depending on image parameter in job pipeline: build means building binaries from mongodb sources, tarball means using prebuilt binaries from already prepared tarballs, prebuilt means using already prepared docker image from registry.
To run suites job starts necessary number of nodes (parallelexecutors parameter) in parallel and runs each suite in single container in loop of predefined suites list.  List of suites could be defined directly in testsuites parameter or job can download predefined list of suites from any url defined in listsuites parameter. To avoid …

PSMDB-938 regression tests

---

cloud/jenkins/pg_containers_docker_build.groovy
cloud/jenkins/ps_containers_docker_build.groovy
cloud/jenkins/pxc_containers_docker_build.groovy

the issue on Jenkins
```
USAGE:
trivy [global options] command [command options] target
VERSION:
0.20.2
2021-10-26T10:04:50.130Z	[31mFATAL[0m	flag provided but not defined: -auto-refresh
Incorrect Usage. flag provided but not defined: -auto-refresh
```

remove outdated auto-refresh option

---

cloud/jenkins/pxc_operator_minikube.groovy

because of anti-affinity rules

K8SPXC-895 - default-cr test cannot run on minikube

---

pxb/v2/local/build-binary

https://jira.percona.com/browse/PXB-2638
build-binary was incorrectly appending -DWITH_ASAN to CMAKE_OPTS
variable.

FIXED PXB-2638 - ASAN job ignores CMAKE_OPTIONS

---

vars/pmmVersion.groovy

The latest version is broken now and a temporary solution is to use a static version

PMM-7 use static version

---

cloud/jenkins/pgo_operator_eks.groovy
cloud/jenkins/psmdb_operator_eks.groovy
cloud/jenkins/pxc_operator_eks.groovy

Deleting CloudFormation Stack fails if there are still existing pods, it tries to drain pods in the nodes and fails because of pod disruption budget.
So this should fix it and prevent manual cleanup of CloudFormation stacks.
There was a `--drain=false` option before, but it doesn't seem to exist any more.
Here's how it looks:
```
2021-12-20 14:15:39 [!]  ignoring DaemonSet-managed Pods: kube-system/aws-node-xh5ll, kube-system/kube-proxy-pc7mx
2021-12-20 14:15:39 [!]  pod eviction error ("error evicting pod: default-cr-10000/my-cluster-name-cfg-2: Cannot evict pod as it would violate the pod's disruption budget.") on node ip-192-168-35-185.eu-west-3.compute.internal
2021-12-20 14:15:44 [!]  ignoring DaemonSet-managed Pods: kube-system/aws-node-fkfcj, kube-system/kube-proxy-rr8xw
2021-12-20 …
```

Add --force to eksctl delete in cloud pipelines

---

pxc/docker/install-deps

CMake Warning at cmake/fido2.cmake:28 (MESSAGE):
Cannot find development libraries.  You need to install the required
packages:
Debian/Ubuntu:              apt install libudev-dev
RedHat/Fedora/Oracle Linux: yum install libudev-devel
SuSE:                       zypper install libudev-devel

PXB fails to build without libudev-devel

---

IaC/pmm.cd/init.groovy.d/matrix.groovy

1. New versions of Github auth plugin used team slug instead of team name...
https://github.com/jenkinsci/github-oauth-plugin/commit/fcf8b7721a146e9adcc9d8bf68c88ddc5ed05e52
2. I removed `External Contractors` group because I didn't find it in GitHub and it was disabled a long time ago.

PMM-7 fix auth flow

---

pmm/pmm2-ui-tests-nightly.groovy

Settings tests have moved to nightly. Hence disabling container env variable option

PMM-7 Nightly: UI: Disable Alerting and DBaaS 

---

IaC/pmm.cd/init.groovy.d/cloud.groovy

This PR is related to #1358, split due to different code owners

[ENG-1082] fix: CentOS 6 CA certificates are too old

---

cloud/jenkins/psmdb_docker_build.groovy

Following issue is seen with PSMDB 5.0:
```
+ sg docker -c '
docker login -u '\'****\'' -p '\'****\''
/usr/local/bin/trivy -q --cache-dir /mnt/jenkins/trivy-psmdb-docker-build/ image -o /mnt/jenkins/workspace/psmdb-docker-build/trivy-hight-percona-server-mongodb-operator-main-mongod5.0-debug.log --timeout 10m0s --ignore-unfixed --exit-code 0 --severity HIGH perconalab/percona-server-mongodb-operator:main-mongod5.0-debug
/usr/local/bin/trivy -q --cache-dir /mnt/jenkins/trivy-psmdb-docker-build/ image -o /mnt/jenkins/workspace/psmdb-docker-build/trivy-critical-percona-server-mongodb-operator-main-mongod5.0-debug.log --timeout 10m0s --ignore-unfixed --exit-code 0 --severity CRITICAL perconalab/percona-server-mongodb-operator:main-mongod5.0-debug
'
WARNING! Using --password via the CLI is …
```

Fix trivy timeout for PSMDB 5.0

---

cloud/jenkins/pg_containers_docker_build.groovy
cloud/jenkins/ps_containers_docker_build.groovy
cloud/jenkins/pxc_containers_docker_build.groovy

Following issue was visible in some jenkins jobs:
```
+ sg docker -c '
IMAGE_NAME=percona-postgresql-operator
docker login -u **** -p ****
for PG_VER in 14 13 12; do
TrityHightLog="/mnt/jenkins/workspace/pg-containers-docker-build/trivy-hight-$IMAGE_NAME-ppg${PG_VER}-pgbackrest-repo.log"
TrityCriticaltLog="/mnt/jenkins/workspace/pg-containers-docker-build/trivy-critical-$IMAGE_NAME-ppg${PG_VER}-pgbackrest-repo.log"
/usr/local/bin/trivy -o $TrityHightLog --ignore-unfixed --exit-code 0 --severity HIGH --quiet                         perconalab/$IMAGE_NAME:main-ppg${PG_VER}-pgbackrest-repo
/usr/local/bin/trivy -o $TrityCriticaltLog --ignore-unfixed --exit-code 0 --severity CRITICAL --quiet                         perconalab/$IMAGE_NAME:main-ppg${PG_VER}-pgbackrest-repo
if [ ! -s …
```

Fix trivy invocation

---

pxb/jenkins/pxb80-single-platform-run.yml

*Problem*:
Project pxb80-single-platform-run fails with:
```
CMake Warning at cmake/fido2.cmake:53 (MESSAGE):
Cannot find development libraries.  You need to install the required
packages:
Debian/Ubuntu:              apt install libudev-dev
RedHat/Fedora/Oracle Linux: yum install libudev-devel
SuSE:                       zypper install libudev-devel
Call Stack (most recent call first):
CMakeLists.txt:1856 (WARN_MISSING_SYSTEM_UDEV)
-- CMAKE_MODULE_LINKER_FLAGS_DEBUG  -Wl,-rpath,'$ORIGIN/../../private'
-- CMAKE_SHARED_LINKER_FLAGS_DEBUG  -Wl,-rpath,'$ORIGIN/../../private'
CMake Error at CMakeLists.txt:1880 (ADD_SUBDIRECTORY):
The source directory
/mnt/jenkins/workspace/pxb80-single-platform-run/CMAKE_BUILD_TYPE/RelWithDebInfo/jenkins-pipelines/pxb/sources/pxb80/extra/libkmip
does not …
```

PXB-2422 - Update pxb80 platform for 8.0.28

---

pxb/jenkins/checkout

PS 8.0.28 introduces a submodule for the first time.
If submodules are not initialized the compilation fails with:
```
CMake Error at CMakeLists.txt:1880 (ADD_SUBDIRECTORY):
The source directory
/mnt/jenkins/workspace/pxb80-single-platform-run/CMAKE_BUILD_TYPE/RelWithDebInfo/jenkins-pipelines/pxb/sources/pxb80/extra/libkmip
does not contain a CMakeLists.txt file.
```

PXB-2693 - Initialize PS submodules

---

pxb/jenkins/pxb80-single-platform-run.yml

Newer git versions require "safe.directory" to be set in order to
perform any actions with repo on behalf any other user

PXB-7 fix "unsafe repository" git issue

---

ps/jenkins/package-testing-ps-5.7.groovy
ps/jenkins/package-testing-ps-5.7.yml
ps/jenkins/package-testing-ps-build-5.7.groovy
ps/jenkins/package-testing-ps-build-5.7.yml

Remove unsupported for PS5.7 distros from test:
- bullseye;
- stretch;
- centos6;
- xenial.
Replace Centos8 with Oracle Linux8 . 
Successful test runs:
https://ps57.cd.percona.com/job/package-testing-ps57-eleonora/5/ (note: failed major update is expected due to percona-mysql-shell issue PS-8256).
Fedora epel-repo is used for Oracle Linux8 due to PS-8268.

Remove unsupported distros and add OL8 for ps57 package-testing

---

pdps/orchestrator.groovy
pdps/pdps-upgrade.groovy
pdps/pdps.groovy

A new choice parameter DESTROY_ENV was added for pdps, pdps-upgrade and orchestrator jobs. By default it is set to 'yes'. If set to 'no', the shh key will be uploaded to test env (this part is in package-testing commit) and test env will be preserved on aws.
Tests were run on copied jenkins tasks:
https://ps80.cd.percona.com/job/pdps-upgrade-eleonora/
https://ps80.cd.percona.com/job/orchestrator-eleonora/
https://ps80.cd.percona.com/job/pdps-eleonora/

DISTMYSQL-178: add option to preserve test environment

---

pmm/aws-staging-start.groovy

- Container names allow only `[a-zA-Z0-9][a-zA-Z0-9_.-]`
- This fixes an issue with email address containing "+"

Fix errors due to "+" in email address.

---

pmm/pmm2-dbaas-e2e-tests.groovy

We need to pass PERCONA_TEST_DBAAS_PMM_CLIENT=perconalab/pmm-client:dev-latest as default due to bug https://jira.percona.com/browse/PMM-10361 to make dbaas tests fail less
Before: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1336/tests
After: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests-beata-temp/detail/pmm2-dbaas-e2e-tests-beata-temp/4/tests

PMM-7 pass pmm client version as env var

---

proxysql/build-binary-proxysql

checking whether compiler supports -Wall... Can't locate IPC/Cmd.pm
Solution:
Installed the missing perl module perl-IPC-Cmd

ProxySQL compilation is failing on CentOS 7 due to below Error:

---

ps/jenkins/package-testing-ps-5.7.groovy
ps/jenkins/package-testing-ps-5.7.yml
ps/jenkins/package-testing-ps-build-5.7.groovy
ps/jenkins/package-testing-ps-build-5.7.yml

Modify package-testing-ps-5.7 and package-testing-ps-build-5.7 jenkins jobs .groovy and .yml for adding Debian 11 Bullseye support.

Ps 8342 add debian 11 support for ps 5.7

---

cloud/jenkins/ps_operator_aws_openshift-4.groovy
cloud/jenkins/ps_operator_eks.groovy
cloud/jenkins/ps_operator_gke_version.groovy
cloud/jenkins/ps_operator_minikube.groovy
cloud/jenkins/psmdb_operator_minikube.groovy
cloud/jenkins/pxc_operator_minikube.groovy

`FILE_NAME` variable should always be local in `runTest` function in case we are running tests in parallel.

K8SPS-123 - Make FILE_NAME variable local to fix conflict when running tests in parallel

---

.github/CODEOWNERS

This PR is supposed to reduce the number of code owners on some paths where the number of code owners was already sufficient before the most recent change.  This will allow to reduce the time it takes to review and commit changes to our code.

PMM-7 reduce the number of code owners on some paths

---

pmm/pmm2-ovf-test.groovy

Without this flag ovf tests are failing for mysql bm.

PMM-7 Add mysql bm to ovf tests job

---

pxb/percona-xtrabackup-2.4-param.yml
pxb/percona-xtrabackup-2.4-template.yml

https://jira.percona.com/browse/ENG-1159
* Adds support to install openssl11-libs and cmake3 packages and use cmake3 for compilation on centos-7 platform.
* Removes xenial and stretch platfoms from the configuration matrix since they're EOL and no jenkins nodes exist for them.

ENG-1159 PXB 2.4 jenkins job improvements

---

pxc/docker/install-deps

This is adjusted install-deps script for PXC build images generation
1. ubuntu:jammy added
2. 8.0 toolset by default for ubuntu:bionic
3. oraclelinux:9 added
4. Some refactoring towards unifying images with PS in the future
Please build Docker images for ubuntu:jammy, ubuntu:bionic and oraclelinux:9 at least and upload to the repository to be able to use by Jenkins.
It would be good to rebuild all images as boos tarball has been updated. Having this we will avoid constant downloading of boost tarball.

PXC-3998: Add ubuntu:jammy and oraclelinux:9

---

pxb/jenkins/build-binary-pxb24
pxb/jenkins/pxb24-single-platform-run.groovy
pxc/jenkins/param57.yml
pxc/jenkins/prepare-pxc-build-docker.yml
pxc/jenkins/pxc57-pipeline.groovy
pxc/jenkins/pxc57-pipeline.yml
pxc/jenkins/qa-param57.yml
pxc/jenkins/qa-pxc57-pipeline.groovy
pxc/local/build-binary-pxb24
pxc/local/checkout
pxc/local/checkout56
pxc/local/checkout57
pxc/percona-xtrabackup-2.4-binaries.yml
pxc/percona-xtrabackup-8.0-binary-tarball_for_pxc.yml

https://jira.percona.com/browse/ENG-1164
* Disables some necessary PXC and PXB jobs from running tests on centos:6 since it is already EOL.
* Makes sure that cmake3 is being used to compile PXB in centos:7 images.

ENG-1164 Removes support for centos:6 and use cmake3 for centos:7

---

pdps/pdps-multi-parallel.groovy
pdps/pdps-multi.groovy
pdps/pdps-upgrade-parallel.groovy
pdps/pdps-upgrade.groovy
pdpxc/pdpxc-multi-parallel.groovy
pdpxc/pdpxc-multi.groovy
pdpxc/pdpxc-upgrade-parallel.groovy
pdpxc/pdpxc-upgrade.groovy

For changes in https://github.com/Percona-QA/package-testing/pull/311 we need to rename pd(pxc|ps)-minor-upgrade to pd(pxc|ps)_minor_upgrade and use corresponding names in tests

DISTMYSQL-221: rename pd(pxc|ps)-minor-upgrade to pd(pxc|ps)_minor_upgrade to move tests

---

pmm/kubernetes-cluster-staging.groovy

Operators installation is handled by OLM now. No need to apply operators via script anymore.

PMM-7-remove-psmdb-op-apply-as-default

---

pmm/aws-staging-start.groovy

pmm2-ui-test-nightly fails:
[2023-01-09T00:16:47.013Z] Scheduling project: aws-staging-start
Value for choice parameter 'PDPGSQL_VERSION' is '15.1', but valid choices are [15.0, 14.4, 14.3, 14.2, 14.1, 14.0, 13.7, 13.6, 13.4, 13.2, 13.1, 12.11, 12.10, 12.8, 11.16, 11.15, 11.13]

PMM-7 add pg 15.1 to staging-start

---

pxc/jenkins/param56.yml
pxc/jenkins/pxc56-pipeline.groovy
pxc/jenkins/pxc57-pipeline.groovy
pxc/local/checkout56
pxc/local/test-binary-pxc56

https://jira.percona.com/browse/ENG-1169
* Updates PXC 5.6 pipeline with to use PXB 2.4 scripts instead of 2.3 scripts along with updating the default PXB version parameter.
* Removes centos-06 from the configuration matrix.

ENG 1169: PXC 5.6 jenkins job improvements

---

pxb/v2/jenkins/percona-xtrabackup-8.0-compile-param.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-compile-pipeline.groovy
pxb/v2/jenkins/percona-xtrabackup-8.0-compile-pipeline.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy
pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.yml
pxc/jenkins/param57.yml
pxc/jenkins/pxc57-pipeline.groovy
pxc/jenkins/pxc57-pipeline.yml

https://jira.percona.com/browse/PXC-4093
Adds debian:bullseye, oraclelinux:9 and ubuntu:jammy to the configuration matrix of PXC 5.7 pipeline along with some minor refactoring.

PXC-4093 ADD DEBIAN-11, ORACLE LINUX-9, UBUNTU-22.04 TO PXC 5.7

---

cloud/jenkins/pgo_operator_gke_version.groovy
cloud/jenkins/ps_operator_gke_version.groovy
cloud/jenkins/psmdb_operator_gke_version.groovy
cloud/jenkins/pxc_operator_gke_version.groovy

It turns out we had a bug in the pipeline where ShutdownCluster function was changing currently active service account (always using the alpha one) and that would break the tests currently in progress (eg. one parallel cluster finishes soon and triggers ShutdownCluster function).

CLOUD-749 - Fix GKE pipeline service account

---

pxc/local/test-binary-pxc57

https://jira.percona.com/browse/PXC-4132
Some tests which require python3 are failing in Jenkins looking for python only to find python2 installed in bullseye and python3 in OEL9. So, a symlink is created to so that the tests can be consistent.

PXC-4132 CREATES A SYMLINK FOR PYTHON3

---

pxc/docker/install-deps

https://jira.percona.com/browse/PXC-4132
Installs mysqlclient python package for to support the tests which make use of the 'MySQLdb' module.

PXC-4132 INSTALLS MYSQLCLIENT PACAGE FROM PIP3

---

cloud/jenkins/ps_operator_minikube.groovy
cloud/jenkins/psmdb_operator_minikube.groovy
cloud/jenkins/pxc_operator_minikube.groovy

This WILL NOT speed up the tests, it will just allow to run tests which ask for more reasources.
Eg. we will probably be able to remove this: https://github.com/percona/percona-server-mysql-operator/blob/main/e2e-tests/functions#L137
Also I didn't go with maximum numbers for the current instance type 8cpu 32GB, but left some buffer, not sure if makes sense or not.

CLOUD-777 - Increase resources used for running minikube tests

---

pxc/docker/install-deps

https://jira.percona.com/browse/PXC-4131
Problem
-------
PXB fails to run on OL9 with the following error
bin/xtrabackup: error while loading shared libraries: libcrypt.so.1:
cannot open shared object file: No such file or directory
Solution
--------
Add libxcrypt-compat library dependency to PXC Jenkins
Before fix:
```
bash-5.1$ sudo wget https://downloads.percona.com/downloads/Percona-XtraBackup-2.4/Percona-XtraBackup-2.4.27/binary/tarball/percona-xtrabackup-2.4.27-Linux-x86_64.glibc2.12-minimal.tar.gz
--2023-03-23 10:17:34--  https://downloads.percona.com/downloads/Percona-XtraBackup-2.4/Percona-XtraBackup-2.4.27/binary/tarball/percona-xtrabackup-2.4.27-Linux-x86_64.glibc2.12-minimal.tar.gz
Resolving downloads.percona.com (downloads.percona.com)... 162.220.4.221, 162.220.4.222, …
```

PXC-4131: Merge PS-8.0.32 (Add dependency on libxcrypt-compat on docker)

---

pxc/docker/install-deps

Downgrade sphinx for OL9 to 5.3.0 due to
https://github.com/sphinx-doc/sphinx/issues/11094

ENG-7 downgrade pshinx for OL9

---

vars/ppgOperatingSystems.groovy

DISTPG-567: Moved centos8 to ol-8, and added ol-9 in os list that is used for ppg testing.

DISTPG-567: Add ol-8 & ol-9 to ppg-testing. 

---

IaC/pmm.cd/init.groovy.d/cloud.groovy

Now, we were getting following error:
_Apr 17, 2023 5:20:47 AM hudson.plugins.ec2.EC2Cloud
INFO: Node still not ready. Current status: Your Spot request price of 0.04 is lower than the minimum required Spot request fulfillment price of 0.0417._

PMM-7 Update spot instance price for min-* agents.

---

cloud/jenkins/ps_operator_eks_version.groovy
cloud/jenkins/ps_operator_gke_version.groovy
cloud/jenkins/psmdb_operator_aks_latest.groovy
cloud/jenkins/psmdb_operator_aks_version.groovy
cloud/jenkins/psmdb_operator_aws_openshift-4.groovy
cloud/jenkins/psmdb_operator_aws_openshift-latest.groovy
cloud/jenkins/psmdb_operator_eks_latest.groovy
cloud/jenkins/psmdb_operator_eks_version.groovy
cloud/jenkins/psmdb_operator_gke_latest.groovy
cloud/jenkins/psmdb_operator_gke_version.groovy
cloud/jenkins/pxc_operator_aks_latest.groovy
cloud/jenkins/pxc_operator_aks_version.groovy
cloud/jenkins/pxc_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift-latest.groovy
cloud/jenkins/pxc_operator_eks_latest.groovy
cloud/jenkins/pxc_operator_eks_version.groovy
cloud/jenkins/pxc_operator_gke_latest.groovy
cloud/jenkins/pxc_operator_gke_version.groovy

1. Delete services and other objects before cluster delete so that external objects are cleaned up properly on cluster delete
2. Fix EKS cluster deletion if it fails because of dependencies
3. Run EKS `latest` jobs in `eu-west-3` and `version` jobs in `eu-west-2` region because of quotas
4. Fix some other smaller bugs

CLOUD-783 - Add cluster cleanup before deletion

---

pmm/pmm2-ui-tests-nightly.groovy

--addclient=ms,1 and --setup-replication-ps-pmm2 --group setups are not stable (services go down sometimes which causes mysql dashboard tests failures). This stage checks the services and restarts a service if the address/port is down.
Test run https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly-beata-temp/detail/pmm2-ui-test-nightly-beata-temp/26/pipeline/73

PMM-7 add mysql status and restart check

---

ps/jenkins/package-testing-ps-build-5.7.groovy

Skipping distributions as their packages are not available and they fail by throwing error that No matching packages are available.
Jammy 
Ol9
Bullseye

Skipping some distributions in PS 5.6 to PS 5.7 upgrade job

---

cloud/jenkins/ps_operator_aws_openshift-4.groovy
cloud/jenkins/psmdb_operator_aws_openshift-4.groovy
cloud/jenkins/psmdb_operator_aws_openshift-latest.groovy
cloud/jenkins/psmdb_operator_eks_latest.groovy
cloud/jenkins/psmdb_operator_eks_version.groovy
cloud/jenkins/pxc_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift-latest.groovy
cloud/jenkins/pxc_operator_eks_latest.groovy
cloud/jenkins/pxc_operator_eks_version.groovy

We seem to use one thing for pushing artifacts and another one for marking tests as passed so this makes usage of GIT_SHORT_COMMIT everywhere.

Use GIT_SHORT_COMMIT for pushing test result artifacts

---

pxc/local/test-binary-pxc-parallel-mtr

https://jira.percona.com/browse/PXC-4213
Problem:
If CI_FS test is disabled in disabled.def, it is executed anyway
Cause:
We search for CI_FS tests and explicitly specify the list to be executed by mtr framework. This cause disabled.def exclusions to be skipped.
Solution:
Filter out tests disabled by disabled.def file

PXC-4213: Make possible to disable tests executed in ci_fs

---

pxc/docker/install-deps
pxc/local/build-binary-pxc-parallel-mtr

https://jira.percona.com/browse/PXC-4234
1. Added toolset-12 for centos:8 and oraclelinux:9
2. removed procps-ng-devel-3.3.17-8.el9.x86_64.rpm as procps-ng.x86_64 3.3.17-11.el9 is already installed on base image
3. removed rhel 6 related stuff
4. removed export CC/CXX from build environment allowing CMake scripts to decide which compiler to use (the same behavior as for PS)
5. removed forcing devtoolset-8 build on centos 7. Use default devtoolset-11 from CMakeLists.txt

PXC-4234: Update Jenkins Docker images for centos:8 and oraclelinux:9

---

pxc/docker/install-deps
pxc/local/build-binary-pxc-parallel-mtr

1. Added missing gcc-12 toolset missing packages
2. Added WITH_PACKAGE_FLAGS=OFF compilation flag (unified with PS) It disables LTO (Link Time Optimization) and suppresses ODR (One Definition Rule) violations

Devtoolset 12 adjustments

---

pmm/pmm2-ovf.groovy
vars/launchSpotInstance.groovy

Currently, the aws-staging-start pipeline makes 10 loops with 5s waiting time between the loops before it realizes that there are no AWS instances available at that price. Then it increases the bid price by 15% and tries again. The process loops until AWS can offer an instance at that price. This contributes oftentimes (when the spots are in high demand) to long waiting times to acquire an instance. Example: https://pmm.cd.percona.com/job/aws-staging-start/68442
Our observation is that 2 loops are more than sufficient for that. AWS API is reliable enough, so the first two negative answers should be sufficient to proceed to the another cycle. Anything above 4 mins waiting time is too long (see the second column on the screenshot).
This PR will reduce the time-to-instance, which the team …

PMM-7 reduce time to instance

---

cloud/jenkins/psmdb_operator_aks_latest.groovy
cloud/jenkins/psmdb_operator_aks_version.groovy
cloud/jenkins/pxc_operator_aks_latest.groovy
cloud/jenkins/pxc_operator_aks_version.groovy

Failure:
```
11:40:54  + az login --service-principal -u **** -p **** -t **** --allow-no-subscriptions
11:40:54  urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
11:40:54  ERROR: Error loading command module 'acr': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
11:40:54  ERROR: Error loading command module 'appservice': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
11:40:54  ERROR: Error loading command module …
```

ENG-1203 - Fix python urllib3 library version for azure cli

---

pmm/aws-staging-start.groovy
vars/setupPMMClient.groovy

We want to prevent Jenkins from killing the pmm-agent process when the pipeline terminates.
Ref: https://stackoverflow.com/questions/39169457/how-to-tell-jenkins-not-to-kill-processes-after-successful-execution-of-job-in-m

PMM-11658 prevent Jenkins from killing the process

---

pxb/jenkins/pxb-package-testing-all.groovy

-test was used for testing purpose and was left to be removed.

pxb package testing remove -test from the runNodeBuild groovy function

---

IaC/pmm.cd/init.groovy.d/cloud.groovy

We were unable to launch **_min-ol-8-x64_** agent:
**_Exception in thread "main" java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.0.1.el8.x86_64/lib/tzdb.dat (No such file or directory)_**
We fix this by installing **_tzdata-java_** package

PMM-7 Fix Oracle Linux 8 agents.

---

pmm/aws-staging-start.groovy

It is not clear for most folks how to launch a staging instance of PMM with the Release Candidate version of PMM Client. This PR provides a hint for the `CLIENT_VERSION` input parameter.

PMM-7 Hint on how to launch PMM with RC

---

pxb/jenkins/pxb-package-testing.groovy

Reverted to stable ansible version on ubuntu jammy for avoiding kmip issues

use pip based ansible installation for jammy issues

---

pxb/v2/jenkins/percona-xtrabackup-8.0-test-param.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.groovy
pxb/v2/jenkins/percona-xtrabackup-8.0-test-pipeline.yml
pxb/v2/jenkins/percona-xtrabackup-8.1-test-param.yml
pxb/v2/jenkins/percona-xtrabackup-8.1-test-pipeline.groovy
pxb/v2/jenkins/percona-xtrabackup-8.1-test-pipeline.yml

Enable keyring tests and xbcloud by default on test pipeline used by trunk jobs. Default from multijob is still disabled.

Post-fix: Enable keyring and xbcloud tests by default

---

pxb/v2/local/build-binary

https://jira.percona.com/browse/PXB-3188
Adjust boost logic to look for tar.bz2 boost file instead of tar.gz. Our images already have a tar.bz2 available.

Fix PXB-3188: Use boost from image

---

pxb/v2/local/build-binary

centos-8 uses gcc-toolset instead of devtoolset

bump gcc to version 10 on Centos8

---

pxb/v2/local/build-binary

Centos-8 is missing annobin library:
10:20:00 CMake Error at configure.cmake:337 (MESSAGE): 10:20:00 No mysys timer support detected!
10:20:00 Call Stack (most recent call first):
10:20:00 CMakeLists.txt:1621 (INCLUDE)
This is a temporary fix until the lib is installed on the base image.

Temporary Fix for PXB-3192

---

IaC/pmm.cd/init.groovy.d/cloud.groovy

Hack for proper openjdk-11-jre-headless installation for the ami images that already contain ca-certificates preinstalled.
`dpkg: error processing package ca-certificates-java (--configure):
installed ca-certificates-java package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of openjdk-11-jre-headless:amd64:
openjdk-11-jre-headless:amd64 depends on ca-certificates-java (>= 20190405~); however:
Package ca-certificates-java is not configured yet.
`

PMM-12645 pmm.cd: fix debian buster init script

---

ps/jenkins/percona-server-for-mysql-8.0.groovy

* Add Minitests for PS8.0 build job.
* Minitests have only install stage for all the supported OS after the packages are built and pushed to testing repo.
* add package_tests_ps80() function for install package tests for PS_8.0 in the build job itself along with relevant notifications to the release channel (Minitests). 
* Minitest are subset of package tests, so any failure in Minitest will not trigger package-testing and integration test jobs.

Add Minitests for PS 8.0 Build Job

---

IaC/spot-price-auto-updater.yml

Increasing the number of build upto 1000, which is equal to 10 days and 20 hours.
1 build ~ 40KB, 1000 builds ~ 40MB of space.

ENG-7 spot-price-auto-updater: keep 1000 builds

---

cloud/jenkins/version_service_docker_build.groovy

This is needed so we can use latest image from the main branch in our tests.

K8SPG-358 - Create version-service:main-latest image for testing

---

cloud/jenkins/pgo_operator_aws_openshift-4.groovy
cloud/jenkins/pgo_operator_aws_openshift_latest.groovy
cloud/jenkins/pgo_v1_operator_aws_openshift-4.groovy
cloud/jenkins/pgo_v1_pg12_operator_aws_openshift-4.groovy
cloud/jenkins/pgo_v1_pg13_operator_aws_openshift-4.groovy
cloud/jenkins/ps_operator_aws_openshift-4.groovy
cloud/jenkins/psmdb_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift_latest.groovy

If the job is re-run on same executor it can fail like this:
```
18:28:29  2023-12-18 17:28:28 (204 MB/s) - ‘terraform_0.11.14_linux_amd64.zip.1’ saved [12569267/12569267]
18:28:29  
18:28:29  + unzip terraform_0.11.14_linux_amd64.zip
18:28:29  Archive:  terraform_0.11.14_linux_amd64.zip
18:28:29  replace terraform? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
18:28:29  (EOF or read error, treating as "[N]one" ...)
```

K8SPG-358 - Fix OpenShift pipeline to not fail on unzip if re-run

---

vars/sync2ProdPMMClient.groovy

Before running repopush cmd with "--remove-package" arg we should check
whether such package exists in corresponding debian repo.
Adding the same solution as it is done for sync2ProdAutoBuild.groovy and for sync2ProdPMMClientRepo.groovy

PMM-7 check deb before pkg remove/push

---

cloud/jenkins/psmdb_operator_aks_version.groovy
cloud/jenkins/pxc_operator_aks_version.groovy

Remove `@${OWNER_SLACK}` notification, because it gives this error (and is also redundant):
```
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: percona, channel: @${OWNER_SLACK}, color: #FF0000, botUser: true, tokenCredentialId: 4b9ed281-7282-4684-b250-7a02e4dd6ebb, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
22:40:00  ERROR: Slack notification failed with exception: {"ok":false,"error":"channel_not_found"}
22:40:00  ERROR: Slack notification failed. See Jenkins logs for details.
```

K8SPXC-1295 Remove redundant slackSend calls

---

pmm/pmm2-client-autobuild.groovy
pmm/pmm2-submodules-rewind.groovy
pmm/pmm2-submodules.groovy
pmm/v3/pmm3-aws-staging-start.groovy
pmm/v3/pmm3-submodules-rewind.groovy
pmm/v3/pmm3-submodules.groovy
psmdb/jenkins/percona-server-for-mongodb-6.0.groovy
vars/setupPMMClient.groovy

This PR fixes a couple of issues:
1/ bad upload_path was being passed to pmm2-client-autobuild
2/ rewind jobs cannot use `--recommend-shallow` for they don't allow to properly rewind the submodules' branches.

PMM-7 Fix rewind pipelines

---

pmm/pmm2-submodules.groovy
pmm/v3/pmm3-api-tests.groovy
pmm/v3/pmm3-submodules.groovy

This PR fixes the GIT_COMMIT hash, which currently does not change between subsequent pushes. The problem was due to the use of a standard variable, which was overwritten by Jenkins ([check envvars here](https://pmm.cd.percona.com/env-vars.html/)).

PMM-7 Fix git commit hash

---

cloud/jenkins/version_service_docker_build.groovy

We don't need local build and docker build, just docker build is enough.

CLOUD-842 - Fix build for version service images

---

pxc/local/build-binary-pxc57
pxc/local/test-binary-pxc57

https://perconadev.atlassian.net/browse/PXC-4395
* Creates a symlink for python on debian-bookworm platform.
* Exports CMAKE_OPTS env variable so that it is passed through the scripts appropriately.

PXC-4395 Fix minor jenkins issues

---

pxc/jenkins/pxc57-pipeline.groovy
pxc/local/build-binary-pxc57

https://perconadev.atlassian.net/browse/ENG-1235
When build-binary-pxc57 script invoked build-ps/build-binary.sh the environment variables created from the jenkins job parameters were never propagated to the build-ps/build-binary.sh script since it was being invoked through a sudo session.
Adds -E to the script invocation in order to preserve the environment variables through out the scripts.
Also, updates the default value of PXB24_BRANCH jenkins job parameter.

ENG-1235 Fix environment variable propagation through scripts

---

pxc/local/test-binary-pxc57

https://perconadev.atlassian.net/browse/ENG-1235
Post-push fix. Fix string comparison for WITH_ASAN.

ENG-1235 Adds "--sanitize" to MTR arguments for ASAN runs

---

pxc/docker/install-deps

https://perconadev.atlassian.net/browse/PXC-4369
Fix PXC build failures on CentOS-8 due to incorrect mirror links

PXC-4369: PXC 8.0.36 refresh - Q1 2024 (Fix build errors)

---

vars/ppgOperatingSystems.groovy

Removing centos7 and Debian10 from list of ppg testing platforms as both will be EOL at end of this month.

Removing centos7 and Debian10 from list of ppg testing platforms as both will be EOL at end of this month.

---

pxc/docker/install-deps
pxc/docker/prepare-docker

1. disable BuildKit.
2. centos 7: switch to vault repos.
3. move python2-scons installation after installing wget.
4. install procps-ng-devel/procps-ng from downloads.percona.com/downloads/packaging/ since https://pkgs.dyn.su is unavailable.
5. install MySQL-python for ol8 from https://downloads.percona.com/downloads/packaging/

PKG-89 fix pxc docker builds

---

psmdb/jenkins/percona-server-for-mongodb-6.0.groovy

Re-add Buster Tarball build step to follow upstream until they decommission Debian buster.

PSMDB-1454 psmdb60: add step for debian buster tarball build

---

pmm/aws-staging-start.groovy
pmm/v3/pmm3-release.groovy
pmm/v3/pmm3-submodules.groovy

Let's remove those commands asap since we have identified them as harmful, since they could overwrite the tags of product versions that have already been released.

PMM-7 remove latest tags from v3 release

---

pxc/local/build-binary-pxc57

The sudo binary provided in devtoolset-7 is broken. So, the binary from /usr/bin is used instead.

Use proper sudo for CentOS 7

---

pxb/v2/docker/run-test
pxb/v2/jenkins/percona-xtrabackup-8.1-test-param.yml

1. Fix pxb docker images to use satyapercona instead of marce's image.   
kmip certificate expired and will again expire in an year.
2. Enable xtradb80, that is test pxb against Percona Server

PXB Jenkins fixes

---

cloud/jenkins/psmdb_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift-4.groovy

* we need to use different cluster names for different operators

K8SPG-604 fix openshift jobs

---

pmm/infrastructure/rpm-build.groovy

We have deprecated RHEL7 build, so we no longer need to build the `rpmbuild:2` image. Moreover, it's [failing](https://pmm.cd.percona.com/job/rpm-build/95/) because of RHEL7 EOL.

PMM-7 Remove rpmbuild for RHEL7

---

cloud/jenkins/pgo_operator_aws_openshift-4.groovy
cloud/jenkins/pgo_operator_aws_openshift_latest.groovy
cloud/jenkins/pxc_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift_latest.groovy

oc version older than 4.15.25 requires glibc GLIBC_2.32+
AWS instances used for tests have older glibc version and as a result our tests on jenkins fail with:
11:18:25  + KUBECONFIG=/mnt/jenkins/workspace/psmdb-operator-aws-openshift-latest/openshift/cluster1/auth/kubeconfig
11:18:25  + oc whoami
11:18:25  oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
11:18:25  oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
11:18:25  oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
Fix: use static OC version 4.15.25 till it is possible to install GLIBC_2.32+ on worker nodes.

Use OC_VER 4.15.25 for not latest builds due to GLIBC_2.32+ req

---

pmm/pmm2-ovf-staging-start.groovy
pmm/v3/pmm3-ovf-staging-start.groovy

The droplets are not getting deleted because of the introduction of a new `--force` flag, which is required when calling `doctl compute droplet delete`.
Ref: https://pmm.cd.percona.com/job/pmm3-ovf-staging-start/85/console

PMM-7 FIx deletion of droplets in ovf-staging

---

cloud/jenkins/pxc_operator_aks_latest.groovy
cloud/jenkins/pxc_operator_aks_version.groovy
cloud/jenkins/pxc_operator_aws_openshift-4.groovy
cloud/jenkins/pxc_operator_aws_openshift_latest.groovy
cloud/jenkins/pxc_operator_eks_latest.groovy
cloud/jenkins/pxc_operator_eks_version.groovy
cloud/jenkins/pxc_operator_gke_latest.groovy
cloud/jenkins/pxc_operator_gke_version.groovy
cloud/jenkins/pxc_operator_minikube.groovy
pmm/pmm2-ui-tests-matrix.groovy

Implement usage of `release_versions` file from `percona-xtradb-cluster-operator` repo as a source of IMAGES and supported k8s versions for jenkins job.
Two new parameters are added:
`PILLAR_VERSION` - which pillar version to use. If set, implies a release run.
If any image is provided in job params during run - it will overwrite image from file.
Rename parameter `OPERATOR_IMAGE` to `IMAGE_OPERATOR`
Adding the `--enable-ip-alias` parameter to the `gcloud container clusters create ...` command
To prevent Google from automatically upgrading the GKE cluster midway, we will use `--add-maintenance-exclusion-start` and `--add-maintenance-exclusion-end`
test runs:
**GKE:**
non-release run: https://cloud.cd.percona.com/view/PXC/job/pxc-operator-gke-version/1175/
release run: …

K8SPXC-1508 Enhance pipelines with release run parameters

---

pmm/infrastructure/rpm-build.groovy
pmm/pmm2-client-autobuild-amd.groovy
pmm/pmm2-client-autobuild-arm.groovy
pmm/pmm2-release-candidate.groovy
pmm/pmm2-server-autobuild-el9.groovy
pmm/pmm2-submodules.groovy
pmm/v3/pmm3-server-autobuild.groovy

Background
With the deprecation of RHEL 7 builds, we want to go ahead with following naming for our `rpmbuild` images:
- rpmbuild:2   - PMM2 el9
- rpmbuild:3   - PMM3 el9

PMM-7 Rename PMM2 rpmbuild image

---

pxb/v2/jenkins/percona-xtrabackup-2.4-trunk.yml
pxb/v2/jenkins/percona-xtrabackup-8.0-trunk.yml
pxb/v2/jenkins/percona-xtrabackup-8.1-trunk.yml
pxc/jenkins/param.yml

These are not necessary as nobody is monitoring them

Remove weekly triggers for PXB and PXC jobs.

---

cloud/jenkins/pgo_operator_gke_latest.groovy
cloud/jenkins/pgo_operator_gke_version.groovy
cloud/jenkins/ps_operator_gke_latest.groovy
cloud/jenkins/ps_operator_gke_version.groovy
cloud/jenkins/psmdb_operator_gke_latest.groovy
cloud/jenkins/psmdb_operator_gke_version.groovy
cloud/jenkins/pxco-gke.groovy

the command:
`gcloud container get-server-config --region=$region --flatten=channels --filter='channels.channel=$GKE_RELEASE_CHANNEL' --format='value(channels.defaultVersion)' | cut -d- -f1`
only captures the defaultVersion under the $GKE_RELEASE_CHANNEL channel, but not the highest available version.
we must use this command instead:
`gcloud container get-server-config --region=$region --flatten=channels --filter='channels.channel=$GKE_RELEASE_CHANNEL' --format='value(channels.validVersions)' | cut -d- -f1`

CLOUD-889 Fix the detection of newest GKE version in pipelines

---

cloud/jenkins/psmdbo_aks.groovy
cloud/jenkins/psmdbo_eks.groovy
cloud/jenkins/psmdbo_gke.groovy
cloud/jenkins/psmdbo_minikube.groovy
cloud/jenkins/psmdbo_openshift.groovy
cloud/jenkins/pxco_aks.groovy
cloud/jenkins/pxco_eks.groovy
cloud/jenkins/pxco_gke.groovy
cloud/jenkins/pxco_minikube.groovy
cloud/jenkins/pxco_openshift.groovy

At the moment all the tests in pxc and psmdb playbooks run on jenkins with enabled debug which floods the output and makes analysis of the failures harder. With this PR the debug will be disabled by default. PG and PS tests use kuttl so skipped in this PR.

CLOUD-893: add DEBUG_TESTS param diabled by default

---

pxc/docker/install-deps

1. Add gcc-13 for rhel-8 and rhel-9
2. Added netcat - needed by clone-SST
3. Added pigz - for faster compression of build artifacts

Update PXC docker images used for build/tests

---

IaC/cloud.cd/init.groovy.d/htz.cloud.groovy
IaC/pg.cd/init.groovy.d/htz.cloud.groovy
IaC/pmm.cd/init.groovy.d/htz.cloud.groovy
IaC/ps3.cd/init.groovy.d/htz.cloud.groovy
IaC/ps57.cd/init.groovy.d/htz.cloud.groovy
IaC/ps80.cd/init.groovy.d/htz.cloud.groovy
IaC/psmdb.cd/init.groovy.d/htz.cloud.groovy
IaC/pxb.cd/init.groovy.d/htz.cloud.groovy
IaC/pxc.cd/init.groovy.d/htz.cloud.groovy
IaC/rel.cd/init.groovy.d/htz.cloud.groovy

Delays SSH availability on agents to prevent the Jenkins Hetzner plugin from connecting before cloud-init has completed.
The script now stops sshd and schedules a restart after 5 minutes in the background. A final `systemctl start sshd` is added at the end of the script to ensure SSH is available if provisioning finishes early.
This prevents agent launch failures caused by missing directories or an absent Java runtime.

PKG-1045 hetzner: start worker after cloud-init completion

---

vars/openshiftCluster.groovy
vars/openshiftDiscovery.groovy
vars/openshiftTools.groovy

**Jira Ticket:** [PKG-1073](https://perconadev.atlassian.net/browse/PKG-1073) - Fix OpenShift cluster S3 backup name matching in Jenkins pipelines
The OpenShift cluster list job incorrectly reported clusters as "Missing S3 backup!" even when backups existed. This occurred because:
- AWS resources use cluster names with random suffixes (e.g., `test-cluster-7-qc8lc`)
- S3 backups are stored under base names without suffixes (e.g., `test-cluster-7`)
- The discovery code used exact name matching, causing mismatches
Updated the cluster discovery consolidation logic to use prefix matching instead of exact matching. AWS cluster names are now correctly matched to their S3 backups when the AWS name starts with the S3 base name followed by a hyphen.
1. **`vars/openshiftDiscovery.groovy`**:
- …

PKG-1073: Fix OpenShift cluster S3 backup name matching

---

proxysql/qa-proxysql2-param.yml
proxysql/test-proxysql

https://perconadev.atlassian.net/browse/PSQLADM-567
Fetches the latest versions of PXC packges
Replaces the hardcoded values to fetch the PXC packages to run in the jenkins job with a mechanism to always fetch the latest version of the packages available.
Also, removes centos-7 and debian-buster from the qa-proxysql2-param job.

PSQLADM-567 Port PSQLADM-555 PXC fix to Hetzner branch

---

vars/openshiftDiscovery.groovy

This PR fixes Jenkins Pipeline warnings about unknown `env` parameter in `sh` steps.
The `sh` step in Jenkins Pipeline doesn't support an `env` parameter, which was causing warnings in the console output:
```
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': env
```
- Replaced incorrect `sh(env: awsEnv)` usage with proper `withEnv` blocks
- Changed environment variable setup to use array format required by `withEnv`
- Applied linter recommendations for variable naming
- Fixed 3 occurrences in `vars/openshiftDiscovery.groovy`
- AWS credentials are now properly passed as environment variables using `withEnv` blocks
To test this fix:
1. **Update Jenkins Shared Library**:
- Go to Jenkins → Manage Jenkins → Configure System → …

Fix Jenkins Pipeline sh step warning by replacing env parameter with withEnv block

---

vars/openshiftCluster.groovy

This PR changes the PMM OpenShift route configuration from edge termination to passthrough termination to enable proper GRPC connectivity for PMM clients.
With edge termination, TLS is terminated at the OpenShift router level, which breaks GRPC connections. PMM clients require end-to-end TLS with HTTP/2 for GRPC communication to work correctly.
Changed the route configuration to use passthrough termination, which:
- Preserves TLS end-to-end from client to PMM pod
- Allows both HTTPS web UI access and GRPC API connections to work
- Enables PMM clients to connect and send metrics
Modified `vars/openshiftCluster.groovy`:
- Changed route type from `edge` to `passthrough`
- Changed target port from `http` to `https`
- Removed `--insecure-policy=Redirect` flag (not applicable for passthrough …

Change PMM route from edge to passthrough termination

---

pmm/openshift/openshift-cluster-create.yml
pmm/openshift/openshift_cluster_create.groovy
vars/openshiftCluster.groovy

Adds `PMM_HELM_CHART_BRANCH` parameter to deploy PMM from a specific branch in percona-helm-charts repository instead of published charts.
- When `PMM_HELM_CHART_BRANCH` is set:
- Clones `https://github.com/percona/percona-helm-charts.git` to a temporary location
- Checks out specified branch
- Uses local chart path `<temp-dir>/percona-helm-charts/charts/pmm` in helm command
- Skips `--version` flag (uses chart from source)
- When empty/unset: uses existing behavior (published chart from Helm repo with version)
- `openshift-cluster-create.yml`: Added `PMM_HELM_CHART_BRANCH` string parameter
- `openshift_cluster_create.groovy`: Passes parameter to library, shows branch in summaries
- `openshiftCluster.groovy`: Modified `deployPMM()` to handle branch-based deployment
Test unreleased PMM …

PMM-14304: Add ability to control source branch for PMM Helm chart in openshift-cluster-create job

---

cloud/jenkins/pgo_aks.groovy
cloud/jenkins/psmdbo_aks.groovy
cloud/jenkins/pxco_aks.groovy

Update operator jobs to use Standard Load Balancer since Azure has deprecated Basic.
https://azure.microsoft.com/en-us/updates?id=azure-basic-load-balancer-will-be-retired-on-30-september-2025-upgrade-to-standard-load-balancer

Fix azure loadbalancer type in Operator jobs
